/*
###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID localhost.localdomain)
#  Generated on:      Sun Nov 21 22:21:04 2021
#  Design:            IIR_filter
#  Command:           saveNetlist ../netlist/IIR_filter_innovus.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : O-2018.06-SP4
// Date      : Sun Nov 21 21:52:57 2021
/////////////////////////////////////////////////////////////
module IIR_filter (
	CLK, 
	RST_n, 
	DIN, 
	VIN, 
	b0, 
	b1, 
	a1, 
	DOUT, 
	VOUT);
   input CLK;
   input RST_n;
   input [11:0] DIN;
   input VIN;
   input [11:0] b0;
   input [11:0] b1;
   input [11:0] a1;
   output [11:0] DOUT;
   output VOUT;

   // Internal wires
   wire FE_OFN3_mult_66_n199;
   wire FE_OFN2_mult_68_n219;
   wire FE_OFN1_mult_64_n200;
   wire FE_OFN0_mult_68_n218;
   wire q1;
   wire regX0_n21;
   wire regX0_n20;
   wire regX0_n19;
   wire regX0_n18;
   wire regX0_n17;
   wire regX0_n16;
   wire regX0_n15;
   wire regX0_n14;
   wire regX0_n12;
   wire regX0_n10;
   wire regX0_n9;
   wire regX0_n7;
   wire regX0_n5;
   wire regX0_n3;
   wire regX0_n2;
   wire regU_n4;
   wire regU_n3;
   wire regU_n2;
   wire regU_n1;
   wire regU_n24;
   wire regU_n23;
   wire regU_n22;
   wire regU_n21;
   wire regU_n20;
   wire regU_n19;
   wire regU_n18;
   wire regU_n17;
   wire regU_n16;
   wire regU_n12;
   wire regU_n11;
   wire regU_n10;
   wire regY_n34;
   wire regY_n33;
   wire regY_n32;
   wire regY_n31;
   wire regY_n30;
   wire regY_n29;
   wire regY_n28;
   wire regY_n27;
   wire regY_n26;
   wire regY_n25;
   wire regY_n24;
   wire regY_n12;
   wire regY_n11;
   wire regY_n10;
   wire regY_n9;
   wire regY_n8;
   wire regY_n3;
   wire regY_n2;
   wire regY_n1;
   wire mult_64_n289;
   wire mult_64_n288;
   wire mult_64_n287;
   wire mult_64_n286;
   wire mult_64_n285;
   wire mult_64_n283;
   wire mult_64_n282;
   wire mult_64_n281;
   wire mult_64_n279;
   wire mult_64_n278;
   wire mult_64_n277;
   wire mult_64_n276;
   wire mult_64_n273;
   wire mult_64_n272;
   wire mult_64_n271;
   wire mult_64_n270;
   wire mult_64_n269;
   wire mult_64_n266;
   wire mult_64_n265;
   wire mult_64_n264;
   wire mult_64_n263;
   wire mult_64_n262;
   wire mult_64_n261;
   wire mult_64_n260;
   wire mult_64_n259;
   wire mult_64_n258;
   wire mult_64_n257;
   wire mult_64_n255;
   wire mult_64_n254;
   wire mult_64_n249;
   wire mult_64_n246;
   wire mult_64_n241;
   wire mult_64_n240;
   wire mult_64_n239;
   wire mult_64_n238;
   wire mult_64_n218;
   wire mult_64_n206;
   wire mult_64_n205;
   wire mult_64_n204;
   wire mult_64_n203;
   wire mult_64_n201;
   wire mult_64_n200;
   wire mult_64_n199;
   wire mult_64_n198;
   wire mult_64_n197;
   wire mult_64_n196;
   wire mult_64_n194;
   wire mult_64_n193;
   wire mult_64_n192;
   wire mult_64_n182;
   wire mult_64_n181;
   wire mult_64_n180;
   wire mult_64_n179;
   wire mult_64_n178;
   wire mult_64_n177;
   wire mult_64_n176;
   wire mult_64_n175;
   wire mult_64_n174;
   wire mult_64_n173;
   wire mult_64_n172;
   wire mult_64_n171;
   wire mult_64_n170;
   wire mult_64_n169;
   wire mult_64_n168;
   wire mult_64_n167;
   wire mult_64_n166;
   wire mult_64_n165;
   wire mult_64_n164;
   wire mult_64_n163;
   wire mult_64_n162;
   wire mult_64_n161;
   wire mult_64_n160;
   wire mult_64_n159;
   wire mult_64_n158;
   wire mult_64_n157;
   wire mult_64_n156;
   wire mult_64_n155;
   wire mult_64_n153;
   wire mult_64_n152;
   wire mult_64_n151;
   wire mult_64_n150;
   wire mult_64_n149;
   wire mult_64_n148;
   wire mult_64_n147;
   wire mult_64_n146;
   wire mult_64_n145;
   wire mult_64_n144;
   wire mult_64_n143;
   wire mult_64_n142;
   wire mult_64_n141;
   wire mult_64_n140;
   wire mult_64_n139;
   wire mult_64_n138;
   wire mult_64_n137;
   wire mult_64_n136;
   wire mult_64_n135;
   wire mult_64_n134;
   wire mult_64_n133;
   wire mult_64_n132;
   wire mult_64_n131;
   wire mult_64_n130;
   wire mult_64_n129;
   wire mult_64_n128;
   wire mult_64_n127;
   wire mult_64_n126;
   wire mult_64_n125;
   wire mult_64_n124;
   wire mult_64_n122;
   wire mult_64_n121;
   wire mult_64_n120;
   wire mult_64_n119;
   wire mult_64_n118;
   wire mult_64_n116;
   wire mult_64_n115;
   wire mult_64_n114;
   wire mult_64_n113;
   wire mult_64_n111;
   wire mult_64_n109;
   wire mult_64_n108;
   wire mult_64_n106;
   wire mult_64_n105;
   wire mult_64_n103;
   wire mult_64_n102;
   wire mult_64_n101;
   wire mult_64_n100;
   wire mult_64_n99;
   wire mult_64_n98;
   wire mult_64_n97;
   wire mult_64_n96;
   wire mult_64_n95;
   wire mult_64_n94;
   wire mult_64_n93;
   wire mult_64_n92;
   wire mult_64_n91;
   wire mult_64_n90;
   wire mult_64_n89;
   wire mult_64_n88;
   wire mult_64_n87;
   wire mult_64_n86;
   wire mult_64_n85;
   wire mult_64_n84;
   wire mult_64_n83;
   wire mult_64_n82;
   wire mult_64_n81;
   wire mult_64_n80;
   wire mult_64_n79;
   wire mult_64_n78;
   wire mult_64_n77;
   wire mult_64_n76;
   wire mult_64_n75;
   wire mult_64_n74;
   wire mult_64_n73;
   wire mult_64_n72;
   wire mult_64_n71;
   wire mult_64_n70;
   wire mult_64_n69;
   wire mult_64_n68;
   wire mult_64_n67;
   wire mult_64_n66;
   wire mult_64_n65;
   wire mult_64_n64;
   wire mult_64_n63;
   wire mult_64_n62;
   wire mult_64_n59;
   wire mult_64_n55;
   wire mult_64_n54;
   wire mult_64_n53;
   wire mult_64_n52;
   wire mult_64_n47;
   wire mult_64_n46;
   wire mult_64_n45;
   wire mult_64_n44;
   wire mult_64_n39;
   wire mult_64_n38;
   wire mult_64_n37;
   wire mult_64_n36;
   wire mult_64_n35;
   wire mult_64_n34;
   wire mult_64_n32;
   wire mult_64_n31;
   wire mult_64_n30;
   wire mult_64_n29;
   wire mult_64_n28;
   wire mult_64_n27;
   wire mult_64_n26;
   wire mult_64_n25;
   wire mult_64_n24;
   wire mult_64_n23;
   wire mult_64_n22;
   wire mult_64_n21;
   wire mult_64_n20;
   wire mult_64_n19;
   wire mult_64_n18;
   wire mult_64_n17;
   wire mult_64_n15;
   wire mult_64_n13;
   wire mult_64_n12;
   wire mult_64_n11;
   wire mult_64_n10;
   wire mult_64_n6;
   wire mult_64_n4;
   wire mult_64_n3;
   wire mult_64_n2;
   wire mult_64_n1;
   wire add_56_n95;
   wire add_56_n94;
   wire add_56_n92;
   wire add_56_n91;
   wire add_56_n90;
   wire add_56_n89;
   wire add_56_n88;
   wire add_56_n87;
   wire add_56_n86;
   wire add_56_n85;
   wire add_56_n82;
   wire add_56_n50;
   wire add_56_n49;
   wire add_56_n45;
   wire add_56_n44;
   wire add_56_n41;
   wire add_56_n39;
   wire add_56_n38;
   wire add_56_n34;
   wire add_56_n33;
   wire add_56_n32;
   wire add_56_n31;
   wire add_56_n30;
   wire add_56_n29;
   wire add_56_n28;
   wire add_56_n27;
   wire add_56_n26;
   wire add_56_n25;
   wire add_56_n24;
   wire add_56_n23;
   wire add_56_n22;
   wire add_56_n19;
   wire add_56_n17;
   wire add_56_n16;
   wire add_56_n15;
   wire add_56_n14;
   wire add_56_n12;
   wire add_56_n10;
   wire add_56_n9;
   wire add_56_n8;
   wire add_56_n3;
   wire add_56_n1;
   wire mult_68_n247;
   wire mult_68_n246;
   wire mult_68_n245;
   wire mult_68_n244;
   wire mult_68_n243;
   wire mult_68_n242;
   wire mult_68_n241;
   wire mult_68_n240;
   wire mult_68_n220;
   wire mult_68_n219;
   wire mult_68_n218;
   wire mult_68_n217;
   wire mult_68_n216;
   wire mult_68_n215;
   wire mult_68_n214;
   wire mult_68_n208;
   wire mult_68_n207;
   wire mult_68_n206;
   wire mult_68_n196;
   wire mult_68_n195;
   wire mult_68_n194;
   wire mult_68_n184;
   wire mult_68_n183;
   wire mult_68_n182;
   wire mult_68_n181;
   wire mult_68_n180;
   wire mult_68_n179;
   wire mult_68_n178;
   wire mult_68_n177;
   wire mult_68_n176;
   wire mult_68_n175;
   wire mult_68_n174;
   wire mult_68_n173;
   wire mult_68_n172;
   wire mult_68_n171;
   wire mult_68_n170;
   wire mult_68_n169;
   wire mult_68_n168;
   wire mult_68_n167;
   wire mult_68_n166;
   wire mult_68_n165;
   wire mult_68_n164;
   wire mult_68_n163;
   wire mult_68_n162;
   wire mult_68_n161;
   wire mult_68_n160;
   wire mult_68_n159;
   wire mult_68_n158;
   wire mult_68_n157;
   wire mult_68_n155;
   wire mult_68_n154;
   wire mult_68_n153;
   wire mult_68_n152;
   wire mult_68_n151;
   wire mult_68_n150;
   wire mult_68_n149;
   wire mult_68_n148;
   wire mult_68_n147;
   wire mult_68_n146;
   wire mult_68_n145;
   wire mult_68_n144;
   wire mult_68_n143;
   wire mult_68_n142;
   wire mult_68_n141;
   wire mult_68_n140;
   wire mult_68_n139;
   wire mult_68_n138;
   wire mult_68_n137;
   wire mult_68_n136;
   wire mult_68_n135;
   wire mult_68_n134;
   wire mult_68_n133;
   wire mult_68_n132;
   wire mult_68_n131;
   wire mult_68_n130;
   wire mult_68_n129;
   wire mult_68_n128;
   wire mult_68_n127;
   wire mult_68_n125;
   wire mult_68_n124;
   wire mult_68_n123;
   wire mult_68_n122;
   wire mult_68_n121;
   wire mult_68_n120;
   wire mult_68_n119;
   wire mult_68_n118;
   wire mult_68_n117;
   wire mult_68_n116;
   wire mult_68_n115;
   wire mult_68_n113;
   wire mult_68_n111;
   wire mult_68_n110;
   wire mult_68_n108;
   wire mult_68_n107;
   wire mult_68_n106;
   wire mult_68_n104;
   wire mult_68_n103;
   wire mult_68_n102;
   wire mult_68_n101;
   wire mult_68_n100;
   wire mult_68_n99;
   wire mult_68_n98;
   wire mult_68_n97;
   wire mult_68_n96;
   wire mult_68_n95;
   wire mult_68_n94;
   wire mult_68_n93;
   wire mult_68_n92;
   wire mult_68_n91;
   wire mult_68_n90;
   wire mult_68_n89;
   wire mult_68_n88;
   wire mult_68_n87;
   wire mult_68_n86;
   wire mult_68_n85;
   wire mult_68_n84;
   wire mult_68_n83;
   wire mult_68_n82;
   wire mult_68_n81;
   wire mult_68_n80;
   wire mult_68_n79;
   wire mult_68_n78;
   wire mult_68_n77;
   wire mult_68_n76;
   wire mult_68_n75;
   wire mult_68_n74;
   wire mult_68_n73;
   wire mult_68_n72;
   wire mult_68_n71;
   wire mult_68_n70;
   wire mult_68_n69;
   wire mult_68_n68;
   wire mult_68_n67;
   wire mult_68_n66;
   wire mult_68_n65;
   wire mult_68_n64;
   wire mult_68_n63;
   wire mult_68_n62;
   wire mult_68_n61;
   wire mult_68_n60;
   wire mult_68_n51;
   wire mult_68_n50;
   wire mult_68_n49;
   wire mult_68_n48;
   wire mult_68_n47;
   wire mult_68_n46;
   wire mult_68_n45;
   wire mult_68_n44;
   wire mult_68_n39;
   wire mult_68_n38;
   wire mult_68_n37;
   wire mult_68_n36;
   wire mult_68_n35;
   wire mult_68_n34;
   wire mult_68_n33;
   wire mult_68_n32;
   wire mult_68_n31;
   wire mult_68_n30;
   wire mult_68_n29;
   wire mult_68_n28;
   wire mult_68_n27;
   wire mult_68_n26;
   wire mult_68_n25;
   wire mult_68_n24;
   wire mult_68_n23;
   wire mult_68_n22;
   wire mult_68_n21;
   wire mult_68_n20;
   wire mult_68_n19;
   wire mult_68_n18;
   wire mult_68_n17;
   wire mult_68_n15;
   wire mult_68_n13;
   wire mult_68_n12;
   wire mult_68_n11;
   wire mult_68_n10;
   wire mult_68_n8;
   wire mult_68_n7;
   wire mult_68_n6;
   wire mult_68_n5;
   wire mult_68_n4;
   wire mult_68_n3;
   wire mult_68_n2;
   wire mult_68_n1;
   wire add_72_n92;
   wire add_72_n91;
   wire add_72_n90;
   wire add_72_n85;
   wire add_72_n81;
   wire add_72_n79;
   wire add_72_n78;
   wire add_72_n76;
   wire add_72_n42;
   wire add_72_n41;
   wire add_72_n40;
   wire add_72_n38;
   wire add_72_n36;
   wire add_72_n35;
   wire add_72_n34;
   wire add_72_n33;
   wire add_72_n32;
   wire add_72_n31;
   wire add_72_n30;
   wire add_72_n29;
   wire add_72_n28;
   wire add_72_n27;
   wire add_72_n26;
   wire add_72_n25;
   wire add_72_n24;
   wire add_72_n23;
   wire add_72_n22;
   wire add_72_n21;
   wire add_72_n20;
   wire add_72_n19;
   wire add_72_n18;
   wire add_72_n16;
   wire add_72_n15;
   wire add_72_n13;
   wire add_72_n11;
   wire add_72_n10;
   wire add_72_n9;
   wire add_72_n6;
   wire add_72_n5;
   wire add_72_n3;
   wire add_72_n2;
   wire add_72_n1;
   wire mult_66_n278;
   wire mult_66_n277;
   wire mult_66_n276;
   wire mult_66_n275;
   wire mult_66_n274;
   wire mult_66_n273;
   wire mult_66_n272;
   wire mult_66_n271;
   wire mult_66_n270;
   wire mult_66_n269;
   wire mult_66_n268;
   wire mult_66_n267;
   wire mult_66_n265;
   wire mult_66_n262;
   wire mult_66_n261;
   wire mult_66_n260;
   wire mult_66_n256;
   wire mult_66_n254;
   wire mult_66_n253;
   wire mult_66_n247;
   wire mult_66_n246;
   wire mult_66_n245;
   wire mult_66_n243;
   wire mult_66_n239;
   wire mult_66_n238;
   wire mult_66_n237;
   wire mult_66_n217;
   wire mult_66_n205;
   wire mult_66_n204;
   wire mult_66_n203;
   wire mult_66_n202;
   wire mult_66_n200;
   wire mult_66_n199;
   wire mult_66_n198;
   wire mult_66_n197;
   wire mult_66_n196;
   wire mult_66_n195;
   wire mult_66_n193;
   wire mult_66_n192;
   wire mult_66_n191;
   wire mult_66_n181;
   wire mult_66_n180;
   wire mult_66_n179;
   wire mult_66_n178;
   wire mult_66_n177;
   wire mult_66_n176;
   wire mult_66_n175;
   wire mult_66_n174;
   wire mult_66_n173;
   wire mult_66_n172;
   wire mult_66_n171;
   wire mult_66_n170;
   wire mult_66_n169;
   wire mult_66_n168;
   wire mult_66_n167;
   wire mult_66_n166;
   wire mult_66_n165;
   wire mult_66_n164;
   wire mult_66_n163;
   wire mult_66_n162;
   wire mult_66_n161;
   wire mult_66_n160;
   wire mult_66_n159;
   wire mult_66_n158;
   wire mult_66_n157;
   wire mult_66_n156;
   wire mult_66_n155;
   wire mult_66_n154;
   wire mult_66_n152;
   wire mult_66_n151;
   wire mult_66_n150;
   wire mult_66_n149;
   wire mult_66_n148;
   wire mult_66_n147;
   wire mult_66_n146;
   wire mult_66_n145;
   wire mult_66_n144;
   wire mult_66_n143;
   wire mult_66_n142;
   wire mult_66_n141;
   wire mult_66_n140;
   wire mult_66_n139;
   wire mult_66_n138;
   wire mult_66_n137;
   wire mult_66_n136;
   wire mult_66_n135;
   wire mult_66_n134;
   wire mult_66_n133;
   wire mult_66_n132;
   wire mult_66_n131;
   wire mult_66_n130;
   wire mult_66_n129;
   wire mult_66_n128;
   wire mult_66_n127;
   wire mult_66_n126;
   wire mult_66_n125;
   wire mult_66_n124;
   wire mult_66_n123;
   wire mult_66_n122;
   wire mult_66_n120;
   wire mult_66_n119;
   wire mult_66_n118;
   wire mult_66_n117;
   wire mult_66_n116;
   wire mult_66_n115;
   wire mult_66_n114;
   wire mult_66_n113;
   wire mult_66_n112;
   wire mult_66_n110;
   wire mult_66_n108;
   wire mult_66_n107;
   wire mult_66_n105;
   wire mult_66_n104;
   wire mult_66_n102;
   wire mult_66_n101;
   wire mult_66_n100;
   wire mult_66_n99;
   wire mult_66_n98;
   wire mult_66_n97;
   wire mult_66_n96;
   wire mult_66_n95;
   wire mult_66_n94;
   wire mult_66_n93;
   wire mult_66_n92;
   wire mult_66_n91;
   wire mult_66_n90;
   wire mult_66_n89;
   wire mult_66_n88;
   wire mult_66_n87;
   wire mult_66_n86;
   wire mult_66_n85;
   wire mult_66_n84;
   wire mult_66_n83;
   wire mult_66_n82;
   wire mult_66_n81;
   wire mult_66_n80;
   wire mult_66_n79;
   wire mult_66_n78;
   wire mult_66_n77;
   wire mult_66_n76;
   wire mult_66_n75;
   wire mult_66_n74;
   wire mult_66_n73;
   wire mult_66_n72;
   wire mult_66_n71;
   wire mult_66_n70;
   wire mult_66_n69;
   wire mult_66_n68;
   wire mult_66_n67;
   wire mult_66_n66;
   wire mult_66_n65;
   wire mult_66_n64;
   wire mult_66_n63;
   wire mult_66_n62;
   wire mult_66_n59;
   wire mult_66_n58;
   wire mult_66_n57;
   wire mult_66_n56;
   wire mult_66_n48;
   wire mult_66_n47;
   wire mult_66_n46;
   wire mult_66_n45;
   wire mult_66_n40;
   wire mult_66_n39;
   wire mult_66_n38;
   wire mult_66_n37;
   wire mult_66_n36;
   wire mult_66_n32;
   wire mult_66_n31;
   wire mult_66_n30;
   wire mult_66_n29;
   wire mult_66_n28;
   wire mult_66_n27;
   wire mult_66_n26;
   wire mult_66_n25;
   wire mult_66_n24;
   wire mult_66_n23;
   wire mult_66_n22;
   wire mult_66_n21;
   wire mult_66_n20;
   wire mult_66_n19;
   wire mult_66_n18;
   wire mult_66_n17;
   wire mult_66_n16;
   wire mult_66_n15;
   wire mult_66_n13;
   wire mult_66_n11;
   wire mult_66_n10;
   wire mult_66_n8;
   wire mult_66_n5;
   wire mult_66_n3;
   wire mult_66_n2;
   wire mult_66_n1;
   wire [6:0] din_del;
   wire [7:0] u;
   wire [7:0] u_del_vec;
   wire [12:6] mula1;
   wire [12:6] mulb0;
   wire [12:6] mulb1;
   wire [7:0] y;

   assign DOUT[0] = 1'b0 ;
   assign DOUT[1] = 1'b0 ;
   assign DOUT[2] = 1'b0 ;
   assign DOUT[3] = 1'b0 ;

   CLKBUF_X2 FE_OFC3_mult_66_n199 (.A(mult_66_n199),
	.Z(FE_OFN3_mult_66_n199));
   CLKBUF_X2 FE_OFC2_mult_68_n219 (.A(mult_68_n219),
	.Z(FE_OFN2_mult_68_n219));
   CLKBUF_X2 FE_OFC1_mult_64_n200 (.A(mult_64_n200),
	.Z(FE_OFN1_mult_64_n200));
   CLKBUF_X2 FE_OFC0_mult_68_n218 (.A(mult_68_n218),
	.Z(FE_OFN0_mult_68_n218));
   AOI21_X1 FE_RC_3_0 (.A(mult_66_n155),
	.B1(mult_66_n195),
	.B2(FE_OFN3_mult_66_n199),
	.ZN(mult_66_n104));
   AOI21_X1 FE_RC_2_0 (.A(mult_66_n164),
	.B1(mult_66_n196),
	.B2(mult_66_n200),
	.ZN(mult_66_n107));
   AOI21_X1 FE_RC_1_0 (.A(mult_64_n156),
	.B1(mult_64_n196),
	.B2(FE_OFN1_mult_64_n200),
	.ZN(mult_64_n105));
   AOI21_X1 FE_RC_0_0 (.A(mult_64_n165),
	.B1(mult_64_n197),
	.B2(mult_64_n201),
	.ZN(mult_64_n108));
   MUX2_X1 regX0_U12 (.A(din_del[5]),
	.B(DIN[10]),
	.S(VIN),
	.Z(regX0_n20));
   MUX2_X1 regX0_U11 (.A(din_del[3]),
	.B(DIN[8]),
	.S(VIN),
	.Z(regX0_n18));
   MUX2_X1 regX0_U10 (.A(din_del[0]),
	.B(DIN[5]),
	.S(VIN),
	.Z(regX0_n15));
   NAND2_X1 regX0_U9 (.A1(DIN[11]),
	.A2(VIN),
	.ZN(regX0_n7));
   OAI21_X1 regX0_U8 (.A(regX0_n7),
	.B1(regX0_n14),
	.B2(VIN),
	.ZN(regX0_n21));
   NAND2_X1 regX0_U7 (.A1(DIN[9]),
	.A2(VIN),
	.ZN(regX0_n5));
   OAI21_X1 regX0_U6 (.A(regX0_n5),
	.B1(regX0_n12),
	.B2(VIN),
	.ZN(regX0_n19));
   NAND2_X1 regX0_U5 (.A1(DIN[7]),
	.A2(VIN),
	.ZN(regX0_n3));
   OAI21_X1 regX0_U4 (.A(regX0_n3),
	.B1(regX0_n10),
	.B2(VIN),
	.ZN(regX0_n17));
   NAND2_X1 regX0_U3 (.A1(DIN[6]),
	.A2(VIN),
	.ZN(regX0_n2));
   OAI21_X1 regX0_U2 (.A(regX0_n2),
	.B1(regX0_n9),
	.B2(VIN),
	.ZN(regX0_n16));
   DFFR_X1 regX0_Q_reg_0_ (.D(regX0_n15),
	.RN(RST_n),
	.CK(CLK),
	.Q(din_del[0]));
   DFFR_X1 regX0_Q_reg_1_ (.D(regX0_n16),
	.RN(RST_n),
	.CK(CLK),
	.Q(din_del[1]),
	.QN(regX0_n9));
   DFFR_X1 regX0_Q_reg_2_ (.D(regX0_n17),
	.RN(RST_n),
	.CK(CLK),
	.Q(din_del[2]),
	.QN(regX0_n10));
   DFFR_X1 regX0_Q_reg_3_ (.D(regX0_n18),
	.RN(RST_n),
	.CK(CLK),
	.Q(din_del[3]));
   DFFR_X1 regX0_Q_reg_4_ (.D(regX0_n19),
	.RN(RST_n),
	.CK(CLK),
	.Q(din_del[4]),
	.QN(regX0_n12));
   DFFR_X1 regX0_Q_reg_5_ (.D(regX0_n20),
	.RN(RST_n),
	.CK(CLK),
	.Q(din_del[5]));
   DFFR_X1 regX0_Q_reg_6_ (.D(regX0_n21),
	.RN(RST_n),
	.CK(CLK),
	.Q(din_del[6]),
	.QN(regX0_n14));
   MUX2_X1 regU_U13 (.A(regU_n3),
	.B(u[7]),
	.S(q1),
	.Z(regU_n24));
   MUX2_X1 regU_U12 (.A(u_del_vec[6]),
	.B(u[6]),
	.S(q1),
	.Z(regU_n23));
   MUX2_X1 regU_U11 (.A(u_del_vec[5]),
	.B(u[5]),
	.S(q1),
	.Z(regU_n22));
   MUX2_X1 regU_U10 (.A(u_del_vec[4]),
	.B(u[4]),
	.S(q1),
	.Z(regU_n21));
   MUX2_X1 regU_U9 (.A(regU_n2),
	.B(u[3]),
	.S(q1),
	.Z(regU_n20));
   MUX2_X1 regU_U8 (.A(regU_n4),
	.B(u[2]),
	.S(q1),
	.Z(regU_n19));
   MUX2_X1 regU_U7 (.A(regU_n1),
	.B(u[1]),
	.S(q1),
	.Z(regU_n18));
   MUX2_X1 regU_U6 (.A(u_del_vec[0]),
	.B(u[0]),
	.S(q1),
	.Z(regU_n17));
   INV_X1 regU_U5 (.A(regU_n12),
	.ZN(u_del_vec[3]));
   INV_X1 regU_U4 (.A(regU_n10),
	.ZN(u_del_vec[1]));
   INV_X1 regU_U3 (.A(regU_n16),
	.ZN(u_del_vec[7]));
   INV_X1 regU_U2 (.A(regU_n11),
	.ZN(u_del_vec[2]));
   DFFR_X1 regU_Q_reg_7_ (.D(regU_n24),
	.RN(RST_n),
	.CK(CLK),
	.Q(regU_n3),
	.QN(regU_n16));
   DFFR_X1 regU_Q_reg_1_ (.D(regU_n18),
	.RN(RST_n),
	.CK(CLK),
	.Q(regU_n1),
	.QN(regU_n10));
   DFFR_X1 regU_Q_reg_2_ (.D(regU_n19),
	.RN(RST_n),
	.CK(CLK),
	.Q(regU_n4),
	.QN(regU_n11));
   DFFR_X1 regU_Q_reg_3_ (.D(regU_n20),
	.RN(RST_n),
	.CK(CLK),
	.Q(regU_n2),
	.QN(regU_n12));
   DFFR_X1 regU_Q_reg_6_ (.D(regU_n23),
	.RN(RST_n),
	.CK(CLK),
	.Q(u_del_vec[6]));
   DFFR_X1 regU_Q_reg_0_ (.D(regU_n17),
	.RN(RST_n),
	.CK(CLK),
	.Q(u_del_vec[0]));
   DFFR_X1 regU_Q_reg_4_ (.D(regU_n21),
	.RN(RST_n),
	.CK(CLK),
	.Q(u_del_vec[4]));
   DFFR_X1 regU_Q_reg_5_ (.D(regU_n22),
	.RN(RST_n),
	.CK(CLK),
	.Q(u_del_vec[5]));
   NAND2_X1 regY_U16 (.A1(y[7]),
	.A2(q1),
	.ZN(regY_n11));
   NAND2_X1 regY_U15 (.A1(y[6]),
	.A2(q1),
	.ZN(regY_n10));
   NAND2_X1 regY_U14 (.A1(y[5]),
	.A2(q1),
	.ZN(regY_n9));
   OAI21_X1 regY_U13 (.A(regY_n8),
	.B1(regY_n34),
	.B2(q1),
	.ZN(regY_n26));
   NAND2_X1 regY_U12 (.A1(y[4]),
	.A2(q1),
	.ZN(regY_n8));
   MUX2_X1 regY_U11 (.A(DOUT[7]),
	.B(y[3]),
	.S(q1),
	.Z(regY_n27));
   MUX2_X1 regY_U10 (.A(DOUT[6]),
	.B(y[2]),
	.S(q1),
	.Z(regY_n28));
   MUX2_X1 regY_U9 (.A(DOUT[5]),
	.B(y[1]),
	.S(q1),
	.Z(regY_n29));
   MUX2_X1 regY_U8 (.A(DOUT[4]),
	.B(y[0]),
	.S(q1),
	.Z(regY_n30));
   NAND2_X1 regY_U7 (.A1(regY_n10),
	.A2(regY_n3),
	.ZN(regY_n24));
   OR2_X1 regY_U6 (.A1(regY_n32),
	.A2(q1),
	.ZN(regY_n3));
   NAND2_X1 regY_U5 (.A1(regY_n11),
	.A2(regY_n2),
	.ZN(regY_n12));
   OR2_X1 regY_U4 (.A1(regY_n31),
	.A2(q1),
	.ZN(regY_n2));
   NAND2_X1 regY_U3 (.A1(regY_n9),
	.A2(regY_n1),
	.ZN(regY_n25));
   OR2_X1 regY_U2 (.A1(regY_n33),
	.A2(q1),
	.ZN(regY_n1));
   DFFR_X2 regY_Q_reg_5_ (.D(regY_n25),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[9]),
	.QN(regY_n33));
   DFFR_X2 regY_Q_reg_6_ (.D(regY_n24),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[10]),
	.QN(regY_n32));
   DFFR_X1 regY_Q_reg_0_ (.D(regY_n30),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[4]));
   DFFR_X1 regY_Q_reg_1_ (.D(regY_n29),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[5]));
   DFFR_X1 regY_Q_reg_2_ (.D(regY_n28),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[6]));
   DFFR_X1 regY_Q_reg_3_ (.D(regY_n27),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[7]));
   DFFR_X1 regY_Q_reg_4_ (.D(regY_n26),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[8]),
	.QN(regY_n34));
   DFFR_X1 regY_Q_reg_7_ (.D(regY_n12),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[11]),
	.QN(regY_n31));
   DFFR_X1 ff1_Q_reg (.D(VIN),
	.RN(RST_n),
	.CK(CLK),
	.Q(q1));
   DFFR_X1 ff2_Q_reg (.D(q1),
	.RN(RST_n),
	.CK(CLK),
	.Q(VOUT));
   XNOR2_X1 mult_64_U408 (.A(u_del_vec[1]),
	.B(a1[8]),
	.ZN(mult_64_n171));
   XNOR2_X1 mult_64_U407 (.A(u_del_vec[1]),
	.B(a1[6]),
	.ZN(mult_64_n180));
   XNOR2_X1 mult_64_U406 (.A(u_del_vec[1]),
	.B(a1[11]),
	.ZN(mult_64_n153));
   XNOR2_X1 mult_64_U405 (.A(u_del_vec[1]),
	.B(a1[10]),
	.ZN(mult_64_n162));
   OAI21_X1 mult_64_U404 (.A(mult_64_n13),
	.B1(mult_64_n1),
	.B2(mult_64_n12),
	.ZN(mult_64_n11));
   OAI21_X1 mult_64_U403 (.A(mult_64_n20),
	.B1(mult_64_n1),
	.B2(mult_64_n19),
	.ZN(mult_64_n18));
   OAI21_X1 mult_64_U402 (.A(mult_64_n27),
	.B1(mult_64_n1),
	.B2(mult_64_n26),
	.ZN(mult_64_n25));
   XNOR2_X1 mult_64_U401 (.A(u_del_vec[3]),
	.B(a1[6]),
	.ZN(mult_64_n178));
   XNOR2_X1 mult_64_U400 (.A(u_del_vec[3]),
	.B(a1[8]),
	.ZN(mult_64_n169));
   XNOR2_X1 mult_64_U399 (.A(u_del_vec[3]),
	.B(a1[10]),
	.ZN(mult_64_n160));
   XNOR2_X1 mult_64_U398 (.A(u_del_vec[3]),
	.B(a1[11]),
	.ZN(mult_64_n151));
   NOR2_X1 mult_64_U397 (.A1(mult_64_n100),
	.A2(mult_64_n101),
	.ZN(mult_64_n45));
   XNOR2_X1 mult_64_U396 (.A(u_del_vec[2]),
	.B(a1[6]),
	.ZN(mult_64_n179));
   XNOR2_X1 mult_64_U395 (.A(u_del_vec[2]),
	.B(a1[8]),
	.ZN(mult_64_n170));
   XNOR2_X1 mult_64_U394 (.A(u_del_vec[2]),
	.B(a1[11]),
	.ZN(mult_64_n152));
   XNOR2_X1 mult_64_U393 (.A(u_del_vec[2]),
	.B(a1[10]),
	.ZN(mult_64_n161));
   NAND2_X1 mult_64_U392 (.A1(mult_64_n146),
	.A2(mult_64_n139),
	.ZN(mult_64_n54));
   XNOR2_X1 mult_64_U391 (.A(u_del_vec[7]),
	.B(a1[6]),
	.ZN(mult_64_n174));
   XNOR2_X1 mult_64_U390 (.A(u_del_vec[7]),
	.B(a1[8]),
	.ZN(mult_64_n165));
   XNOR2_X1 mult_64_U389 (.A(u_del_vec[7]),
	.B(a1[10]),
	.ZN(mult_64_n156));
   XNOR2_X1 mult_64_U388 (.A(u_del_vec[6]),
	.B(a1[8]),
	.ZN(mult_64_n166));
   XNOR2_X1 mult_64_U387 (.A(u_del_vec[6]),
	.B(a1[10]),
	.ZN(mult_64_n157));
   XNOR2_X1 mult_64_U386 (.A(u_del_vec[6]),
	.B(a1[6]),
	.ZN(mult_64_n175));
   XNOR2_X1 mult_64_U385 (.A(u_del_vec[6]),
	.B(a1[11]),
	.ZN(mult_64_n148));
   OAI22_X1 mult_64_U384 (.A1(mult_64_n171),
	.A2(mult_64_n201),
	.B1(mult_64_n197),
	.B2(mult_64_n172),
	.ZN(mult_64_n138));
   OAI22_X1 mult_64_U383 (.A1(mult_64_n170),
	.A2(mult_64_n201),
	.B1(mult_64_n281),
	.B2(mult_64_n197),
	.ZN(mult_64_n137));
   OAI22_X1 mult_64_U382 (.A1(mult_64_n162),
	.A2(FE_OFN1_mult_64_n200),
	.B1(mult_64_n196),
	.B2(mult_64_n163),
	.ZN(mult_64_n129));
   OAI22_X1 mult_64_U381 (.A1(mult_64_n161),
	.A2(FE_OFN1_mult_64_n200),
	.B1(mult_64_n289),
	.B2(mult_64_n196),
	.ZN(mult_64_n128));
   OAI21_X1 mult_64_U380 (.A(mult_64_n31),
	.B1(mult_64_n30),
	.B2(mult_64_n34),
	.ZN(mult_64_n29));
   OAI22_X1 mult_64_U379 (.A1(mult_64_n178),
	.A2(mult_64_n198),
	.B1(mult_64_n177),
	.B2(mult_64_n218),
	.ZN(mult_64_n144));
   OAI22_X1 mult_64_U378 (.A1(mult_64_n179),
	.A2(mult_64_n198),
	.B1(mult_64_n178),
	.B2(mult_64_n218),
	.ZN(mult_64_n145));
   AOI21_X1 mult_64_U377 (.A(mult_64_n15),
	.B1(mult_64_n22),
	.B2(mult_64_n286),
	.ZN(mult_64_n13));
   OAI22_X1 mult_64_U376 (.A1(mult_64_n166),
	.A2(mult_64_n201),
	.B1(mult_64_n197),
	.B2(mult_64_n167),
	.ZN(mult_64_n133));
   OAI22_X1 mult_64_U375 (.A1(mult_64_n165),
	.A2(mult_64_n201),
	.B1(mult_64_n166),
	.B2(mult_64_n197),
	.ZN(mult_64_n132));
   NOR2_X1 mult_64_U374 (.A1(mult_64_n92),
	.A2(mult_64_n94),
	.ZN(mult_64_n37));
   NAND2_X1 mult_64_U373 (.A1(mult_64_n92),
	.A2(mult_64_n94),
	.ZN(mult_64_n38));
   OAI21_X1 mult_64_U372 (.A(mult_64_n38),
	.B1(mult_64_n39),
	.B2(mult_64_n37),
	.ZN(mult_64_n36));
   OAI22_X1 mult_64_U371 (.A1(mult_64_n161),
	.A2(mult_64_n196),
	.B1(mult_64_n160),
	.B2(FE_OFN1_mult_64_n200),
	.ZN(mult_64_n127));
   OAI22_X1 mult_64_U370 (.A1(mult_64_n196),
	.A2(mult_64_n160),
	.B1(FE_OFN1_mult_64_n200),
	.B2(mult_64_n159),
	.ZN(mult_64_n126));
   NOR2_X1 mult_64_U369 (.A1(mult_64_n30),
	.A2(mult_64_n282),
	.ZN(mult_64_n28));
   OAI21_X1 mult_64_U368 (.A(mult_64_n34),
	.B1(mult_64_n35),
	.B2(mult_64_n282),
	.ZN(mult_64_n32));
   INV_X1 mult_64_U367 (.A(mult_64_n36),
	.ZN(mult_64_n35));
   INV_X1 mult_64_U366 (.A(mult_64_n111),
	.ZN(mult_64_n140));
   OAI21_X1 mult_64_U365 (.A(mult_64_n46),
	.B1(mult_64_n45),
	.B2(mult_64_n47),
	.ZN(mult_64_n44));
   OAI21_X1 mult_64_U364 (.A(mult_64_n24),
	.B1(mult_64_n23),
	.B2(mult_64_n27),
	.ZN(mult_64_n22));
   XNOR2_X1 mult_64_U363 (.A(mult_64_n25),
	.B(mult_64_n4),
	.ZN(mula1[10]));
   OAI22_X1 mult_64_U362 (.A1(mult_64_n197),
	.A2(mult_64_n170),
	.B1(mult_64_n201),
	.B2(mult_64_n169),
	.ZN(mult_64_n136));
   OAI22_X1 mult_64_U361 (.A1(mult_64_n246),
	.A2(mult_64_n197),
	.B1(mult_64_n201),
	.B2(mult_64_n168),
	.ZN(mult_64_n135));
   NOR2_X1 mult_64_U360 (.A1(mult_64_n26),
	.A2(mult_64_n23),
	.ZN(mult_64_n21));
   NAND2_X1 mult_64_U359 (.A1(mult_64_n21),
	.A2(mult_64_n286),
	.ZN(mult_64_n12));
   INV_X1 mult_64_U358 (.A(mult_64_n21),
	.ZN(mult_64_n19));
   NAND2_X1 mult_64_U357 (.A1(mult_64_n86),
	.A2(mult_64_n91),
	.ZN(mult_64_n34));
   OAI22_X1 mult_64_U356 (.A1(mult_64_n288),
	.A2(mult_64_n198),
	.B1(mult_64_n174),
	.B2(mult_64_n218),
	.ZN(mult_64_n111));
   AOI21_X1 mult_64_U355 (.A(mult_64_n257),
	.B1(mult_64_n255),
	.B2(mult_64_n52),
	.ZN(mult_64_n47));
   NAND2_X1 mult_64_U354 (.A1(mult_64_n100),
	.A2(mult_64_n101),
	.ZN(mult_64_n46));
   INV_X1 mult_64_U353 (.A(mult_64_n37),
	.ZN(mult_64_n62));
   NAND2_X1 mult_64_U352 (.A1(mult_64_n80),
	.A2(mult_64_n85),
	.ZN(mult_64_n31));
   NAND2_X1 mult_64_U351 (.A1(mult_64_n70),
	.A2(mult_64_n73),
	.ZN(mult_64_n24));
   NAND2_X1 mult_64_U350 (.A1(mult_64_n74),
	.A2(mult_64_n79),
	.ZN(mult_64_n27));
   XNOR2_X1 mult_64_U349 (.A(mult_64_n18),
	.B(mult_64_n3),
	.ZN(mula1[11]));
   XNOR2_X1 mult_64_U348 (.A(u_del_vec[1]),
	.B(a1[10]),
	.ZN(mult_64_n289));
   XNOR2_X1 mult_64_U347 (.A(mult_64_n11),
	.B(mult_64_n2),
	.ZN(mula1[12]));
   XNOR2_X1 mult_64_U346 (.A(u_del_vec[7]),
	.B(a1[6]),
	.ZN(mult_64_n288));
   INV_X1 mult_64_U345 (.A(a1[11]),
	.ZN(mult_64_n203));
   INV_X1 mult_64_U344 (.A(a1[8]),
	.ZN(mult_64_n205));
   INV_X1 mult_64_U343 (.A(a1[10]),
	.ZN(mult_64_n204));
   INV_X1 mult_64_U342 (.A(a1[6]),
	.ZN(mult_64_n206));
   INV_X1 mult_64_U341 (.A(mult_64_n201),
	.ZN(mult_64_n109));
   AND2_X1 mult_64_U340 (.A1(u_del_vec[0]),
	.A2(mult_64_n109),
	.ZN(mult_64_n139));
   OR2_X1 mult_64_U339 (.A1(u_del_vec[0]),
	.A2(mult_64_n204),
	.ZN(mult_64_n164));
   OAI22_X1 mult_64_U338 (.A1(mult_64_n196),
	.A2(mult_64_n204),
	.B1(mult_64_n164),
	.B2(FE_OFN1_mult_64_n200),
	.ZN(mult_64_n114));
   OAI22_X1 mult_64_U337 (.A1(mult_64_n198),
	.A2(mult_64_n177),
	.B1(mult_64_n176),
	.B2(mult_64_n218),
	.ZN(mult_64_n143));
   XNOR2_X1 mult_64_U336 (.A(a1[8]),
	.B(u_del_vec[0]),
	.ZN(mult_64_n172));
   XOR2_X1 mult_64_U335 (.A(a1[5]),
	.B(a1[6]),
	.Z(mult_64_n194));
   NAND2_X1 mult_64_U334 (.A1(mult_64_n194),
	.A2(mult_64_n218),
	.ZN(mult_64_n198));
   XOR2_X1 mult_64_U333 (.A(a1[7]),
	.B(a1[8]),
	.Z(mult_64_n193));
   NAND2_X1 mult_64_U332 (.A1(mult_64_n193),
	.A2(mult_64_n201),
	.ZN(mult_64_n197));
   XNOR2_X1 mult_64_U331 (.A(a1[6]),
	.B(u_del_vec[0]),
	.ZN(mult_64_n181));
   INV_X1 mult_64_U330 (.A(a1[5]),
	.ZN(mult_64_n218));
   XNOR2_X1 mult_64_U329 (.A(a1[11]),
	.B(u_del_vec[5]),
	.ZN(mult_64_n149));
   NOR2_X1 mult_64_U328 (.A1(mult_64_n199),
	.A2(mult_64_n149),
	.ZN(mult_64_n67));
   OR2_X1 mult_64_U327 (.A1(u_del_vec[0]),
	.A2(mult_64_n203),
	.ZN(mult_64_n155));
   OAI22_X1 mult_64_U326 (.A1(mult_64_n197),
	.A2(mult_64_n168),
	.B1(mult_64_n201),
	.B2(mult_64_n167),
	.ZN(mult_64_n134));
   NOR2_X1 mult_64_U325 (.A1(mult_64_n155),
	.A2(mult_64_n199),
	.ZN(mult_64_n113));
   XOR2_X1 mult_64_U324 (.A(a1[9]),
	.B(a1[10]),
	.Z(mult_64_n192));
   NAND2_X1 mult_64_U323 (.A1(mult_64_n192),
	.A2(FE_OFN1_mult_64_n200),
	.ZN(mult_64_n196));
   XNOR2_X1 mult_64_U322 (.A(a1[8]),
	.B(u_del_vec[5]),
	.ZN(mult_64_n167));
   XNOR2_X1 mult_64_U321 (.A(a1[6]),
	.B(u_del_vec[4]),
	.ZN(mult_64_n177));
   XNOR2_X1 mult_64_U320 (.A(a1[8]),
	.B(u_del_vec[4]),
	.ZN(mult_64_n168));
   XNOR2_X1 mult_64_U319 (.A(a1[10]),
	.B(u_del_vec[4]),
	.ZN(mult_64_n159));
   XNOR2_X1 mult_64_U318 (.A(a1[6]),
	.B(u_del_vec[5]),
	.ZN(mult_64_n176));
   XNOR2_X1 mult_64_U317 (.A(a1[10]),
	.B(u_del_vec[5]),
	.ZN(mult_64_n158));
   OR2_X1 mult_64_U316 (.A1(u_del_vec[0]),
	.A2(mult_64_n206),
	.ZN(mult_64_n182));
   OAI22_X1 mult_64_U315 (.A1(mult_64_n180),
	.A2(mult_64_n218),
	.B1(mult_64_n198),
	.B2(mult_64_n181),
	.ZN(mult_64_n147));
   OAI22_X1 mult_64_U314 (.A1(mult_64_n198),
	.A2(mult_64_n206),
	.B1(mult_64_n182),
	.B2(mult_64_n218),
	.ZN(mult_64_n116));
   NAND2_X1 mult_64_U313 (.A1(mult_64_n147),
	.A2(mult_64_n116),
	.ZN(mult_64_n55));
   XNOR2_X1 mult_64_U312 (.A(a1[10]),
	.B(u_del_vec[0]),
	.ZN(mult_64_n163));
   XNOR2_X1 mult_64_U311 (.A(a1[11]),
	.B(u_del_vec[4]),
	.ZN(mult_64_n150));
   OAI22_X1 mult_64_U310 (.A1(mult_64_n157),
	.A2(FE_OFN1_mult_64_n200),
	.B1(mult_64_n196),
	.B2(mult_64_n158),
	.ZN(mult_64_n125));
   NOR2_X1 mult_64_U309 (.A1(mult_64_n199),
	.A2(mult_64_n150),
	.ZN(mult_64_n118));
   NOR2_X1 mult_64_U308 (.A1(mult_64_n153),
	.A2(mult_64_n199),
	.ZN(mult_64_n121));
   AND2_X1 mult_64_U307 (.A1(u_del_vec[0]),
	.A2(mult_64_n106),
	.ZN(mult_64_n130));
   OAI22_X1 mult_64_U306 (.A1(mult_64_n175),
	.A2(mult_64_n218),
	.B1(mult_64_n198),
	.B2(mult_64_n176),
	.ZN(mult_64_n142));
   OAI22_X1 mult_64_U305 (.A1(mult_64_n288),
	.A2(mult_64_n218),
	.B1(mult_64_n175),
	.B2(mult_64_n198),
	.ZN(mult_64_n141));
   OR2_X1 mult_64_U304 (.A1(u_del_vec[0]),
	.A2(mult_64_n205),
	.ZN(mult_64_n173));
   OAI22_X1 mult_64_U303 (.A1(mult_64_n197),
	.A2(mult_64_n205),
	.B1(mult_64_n173),
	.B2(mult_64_n201),
	.ZN(mult_64_n115));
   INV_X1 mult_64_U302 (.A(mult_64_n199),
	.ZN(mult_64_n103));
   AND2_X1 mult_64_U301 (.A1(u_del_vec[0]),
	.A2(mult_64_n103),
	.ZN(mult_64_n122));
   INV_X1 mult_64_U300 (.A(FE_OFN1_mult_64_n200),
	.ZN(mult_64_n106));
   OAI22_X1 mult_64_U299 (.A1(mult_64_n196),
	.A2(mult_64_n159),
	.B1(FE_OFN1_mult_64_n200),
	.B2(mult_64_n158),
	.ZN(mult_64_n77));
   NOR2_X1 mult_64_U298 (.A1(mult_64_n151),
	.A2(mult_64_n199),
	.ZN(mult_64_n119));
   INV_X1 mult_64_U297 (.A(mult_64_n77),
	.ZN(mult_64_n78));
   NOR2_X1 mult_64_U296 (.A1(mult_64_n152),
	.A2(mult_64_n199),
	.ZN(mult_64_n120));
   INV_X1 mult_64_U294 (.A(mult_64_n108),
	.ZN(mult_64_n131));
   OR2_X1 mult_64_U293 (.A1(mult_64_n126),
	.A2(mult_64_n89),
	.ZN(mult_64_n83));
   XNOR2_X1 mult_64_U292 (.A(mult_64_n126),
	.B(mult_64_n89),
	.ZN(mult_64_n84));
   OAI21_X1 mult_64_U291 (.A(mult_64_n54),
	.B1(mult_64_n53),
	.B2(mult_64_n55),
	.ZN(mult_64_n52));
   NOR2_X1 mult_64_U290 (.A1(mult_64_n146),
	.A2(mult_64_n139),
	.ZN(mult_64_n53));
   OAI22_X1 mult_64_U289 (.A1(mult_64_n179),
	.A2(mult_64_n218),
	.B1(mult_64_n180),
	.B2(mult_64_n198),
	.ZN(mult_64_n146));
   OAI22_X1 mult_64_U288 (.A1(mult_64_n156),
	.A2(FE_OFN1_mult_64_n200),
	.B1(mult_64_n157),
	.B2(mult_64_n196),
	.ZN(mult_64_n124));
   INV_X1 mult_64_U287 (.A(mult_64_n67),
	.ZN(mult_64_n68));
   OR2_X1 mult_64_U285 (.A1(mult_64_n65),
	.A2(mult_64_n64),
	.ZN(mult_64_n287));
   NAND2_X1 mult_64_U284 (.A1(mult_64_n66),
	.A2(mult_64_n69),
	.ZN(mult_64_n17));
   NAND2_X1 mult_64_U283 (.A1(mult_64_n65),
	.A2(mult_64_n64),
	.ZN(mult_64_n10));
   NOR2_X1 mult_64_U282 (.A1(mult_64_n79),
	.A2(mult_64_n74),
	.ZN(mult_64_n26));
   NAND2_X1 mult_64_U281 (.A1(mult_64_n279),
	.A2(mult_64_n31),
	.ZN(mult_64_n6));
   XNOR2_X1 mult_64_U280 (.A(mult_64_n32),
	.B(mult_64_n6),
	.ZN(mula1[8]));
   INV_X1 mult_64_U279 (.A(mult_64_n17),
	.ZN(mult_64_n15));
   NAND2_X1 mult_64_U278 (.A1(mult_64_n287),
	.A2(mult_64_n10),
	.ZN(mult_64_n2));
   NAND2_X1 mult_64_U277 (.A1(mult_64_n286),
	.A2(mult_64_n17),
	.ZN(mult_64_n3));
   INV_X1 mult_64_U276 (.A(mult_64_n26),
	.ZN(mult_64_n59));
   NAND2_X1 mult_64_U275 (.A1(mult_64_n262),
	.A2(mult_64_n24),
	.ZN(mult_64_n4));
   INV_X1 mult_64_U274 (.A(mult_64_n22),
	.ZN(mult_64_n20));
   NOR2_X1 mult_64_U273 (.A1(mult_64_n148),
	.A2(mult_64_n199),
	.ZN(mult_64_n285));
   XNOR2_X1 mult_64_U272 (.A(mult_64_n105),
	.B(mult_64_n285),
	.ZN(mult_64_n63));
   OR2_X1 mult_64_U271 (.A1(mult_64_n66),
	.A2(mult_64_n69),
	.ZN(mult_64_n286));
   AND2_X1 mult_64_U269 (.A1(mult_64_n273),
	.A2(mult_64_n34),
	.ZN(mult_64_n283));
   XNOR2_X1 mult_64_U268 (.A(mult_64_n35),
	.B(mult_64_n283),
	.ZN(mula1[7]));
   NOR2_X1 mult_64_U267 (.A1(mult_64_n86),
	.A2(mult_64_n91),
	.ZN(mult_64_n282));
   XNOR2_X1 mult_64_U266 (.A(u_del_vec[1]),
	.B(a1[8]),
	.ZN(mult_64_n281));
   NOR2_X1 mult_64_U265 (.A1(mult_64_n80),
	.A2(mult_64_n85),
	.ZN(mult_64_n30));
   OR2_X1 mult_64_U263 (.A1(mult_64_n80),
	.A2(mult_64_n85),
	.ZN(mult_64_n279));
   NAND3_X1 mult_64_U262 (.A1(mult_64_n276),
	.A2(mult_64_n277),
	.A3(mult_64_n278),
	.ZN(mult_64_n79));
   NAND2_X1 mult_64_U261 (.A1(mult_64_n87),
	.A2(mult_64_n84),
	.ZN(mult_64_n278));
   NAND2_X1 mult_64_U260 (.A1(mult_64_n82),
	.A2(mult_64_n84),
	.ZN(mult_64_n277));
   NAND2_X1 mult_64_U259 (.A1(mult_64_n82),
	.A2(mult_64_n87),
	.ZN(mult_64_n276));
   OR2_X1 mult_64_U257 (.A1(mult_64_n86),
	.A2(mult_64_n91),
	.ZN(mult_64_n273));
   NAND3_X1 mult_64_U256 (.A1(mult_64_n270),
	.A2(mult_64_n271),
	.A3(mult_64_n272),
	.ZN(mult_64_n91));
   NAND2_X1 mult_64_U255 (.A1(mult_64_n128),
	.A2(mult_64_n142),
	.ZN(mult_64_n272));
   NAND2_X1 mult_64_U254 (.A1(mult_64_n95),
	.A2(mult_64_n142),
	.ZN(mult_64_n271));
   NAND2_X1 mult_64_U253 (.A1(mult_64_n95),
	.A2(mult_64_n128),
	.ZN(mult_64_n270));
   XNOR2_X1 mult_64_U251 (.A(mult_64_n87),
	.B(mult_64_n84),
	.ZN(mult_64_n269));
   XNOR2_X1 mult_64_U250 (.A(mult_64_n269),
	.B(mult_64_n82),
	.ZN(mult_64_n80));
   AOI21_X1 mult_64_U249 (.A(mult_64_n29),
	.B1(mult_64_n36),
	.B2(mult_64_n28),
	.ZN(mult_64_n1));
   AOI21_X1 mult_64_U248 (.A(mult_64_n241),
	.B1(mult_64_n44),
	.B2(mult_64_n240),
	.ZN(mult_64_n39));
   XNOR2_X1 mult_64_U245 (.A(mult_64_n128),
	.B(mult_64_n142),
	.ZN(mult_64_n266));
   XNOR2_X1 mult_64_U244 (.A(mult_64_n95),
	.B(mult_64_n266),
	.ZN(mult_64_n92));
   NAND3_X1 mult_64_U243 (.A1(mult_64_n263),
	.A2(mult_64_n264),
	.A3(mult_64_n265),
	.ZN(mult_64_n85));
   NAND2_X1 mult_64_U242 (.A1(mult_64_n239),
	.A2(mult_64_n141),
	.ZN(mult_64_n265));
   NAND2_X1 mult_64_U241 (.A1(mult_64_n88),
	.A2(mult_64_n141),
	.ZN(mult_64_n264));
   NAND2_X1 mult_64_U240 (.A1(mult_64_n88),
	.A2(mult_64_n239),
	.ZN(mult_64_n263));
   NOR2_X1 mult_64_U239 (.A1(mult_64_n70),
	.A2(mult_64_n73),
	.ZN(mult_64_n23));
   OR2_X1 mult_64_U238 (.A1(mult_64_n70),
	.A2(mult_64_n73),
	.ZN(mult_64_n262));
   XNOR2_X1 mult_64_U237 (.A(mult_64_n93),
	.B(mult_64_n141),
	.ZN(mult_64_n261));
   XNOR2_X1 mult_64_U236 (.A(mult_64_n261),
	.B(mult_64_n88),
	.ZN(mult_64_n86));
   NAND3_X1 mult_64_U235 (.A1(mult_64_n258),
	.A2(mult_64_n259),
	.A3(mult_64_n260),
	.ZN(mult_64_n71));
   NAND2_X1 mult_64_U234 (.A1(mult_64_n118),
	.A2(mult_64_n77),
	.ZN(mult_64_n260));
   NAND2_X1 mult_64_U233 (.A1(mult_64_n125),
	.A2(mult_64_n77),
	.ZN(mult_64_n259));
   NAND2_X1 mult_64_U232 (.A1(mult_64_n125),
	.A2(mult_64_n118),
	.ZN(mult_64_n258));
   AND2_X1 mult_64_U231 (.A1(mult_64_n102),
	.A2(mult_64_n145),
	.ZN(mult_64_n257));
   OR2_X1 mult_64_U229 (.A1(mult_64_n102),
	.A2(mult_64_n145),
	.ZN(mult_64_n255));
   AND2_X1 mult_64_U228 (.A1(mult_64_n62),
	.A2(mult_64_n38),
	.ZN(mult_64_n254));
   XNOR2_X1 mult_64_U227 (.A(mult_64_n254),
	.B(mult_64_n39),
	.ZN(mula1[6]));
   XNOR2_X1 mult_64_U224 (.A(mult_64_n118),
	.B(mult_64_n77),
	.ZN(mult_64_n249));
   XNOR2_X1 mult_64_U223 (.A(mult_64_n125),
	.B(mult_64_n249),
	.ZN(mult_64_n72));
   XNOR2_X1 mult_64_U220 (.A(u_del_vec[3]),
	.B(a1[8]),
	.ZN(mult_64_n246));
   AND2_X1 mult_64_U212 (.A1(mult_64_n96),
	.A2(mult_64_n99),
	.ZN(mult_64_n241));
   OR2_X1 mult_64_U211 (.A1(mult_64_n96),
	.A2(mult_64_n99),
	.ZN(mult_64_n240));
   XNOR2_X1 mult_64_U210 (.A(a1[7]),
	.B(a1[6]),
	.ZN(mult_64_n201));
   XNOR2_X1 mult_64_U209 (.A(a1[9]),
	.B(a1[8]),
	.ZN(mult_64_n200));
   XNOR2_X1 mult_64_U208 (.A(a1[11]),
	.B(a1[10]),
	.ZN(mult_64_n199));
   FA_X1 mult_64_U207 (.A(mult_64_n97),
	.B(mult_64_n122),
	.CI(mult_64_n135),
	.CO(mult_64_n239));
   AND2_X1 mult_64_U206 (.A1(mult_64_n59),
	.A2(mult_64_n27),
	.ZN(mult_64_n238));
   XNOR2_X1 mult_64_U205 (.A(mult_64_n1),
	.B(mult_64_n238),
	.ZN(mula1[9]));
   HA_X1 mult_64_U91 (.A(mult_64_n138),
	.B(mult_64_n115),
	.CO(mult_64_n101),
	.S(mult_64_n102));
   FA_X1 mult_64_U90 (.A(mult_64_n137),
	.B(mult_64_n130),
	.CI(mult_64_n144),
	.CO(mult_64_n99),
	.S(mult_64_n100));
   HA_X1 mult_64_U89 (.A(mult_64_n143),
	.B(mult_64_n114),
	.CO(mult_64_n97),
	.S(mult_64_n98));
   FA_X1 mult_64_U88 (.A(mult_64_n129),
	.B(mult_64_n98),
	.CI(mult_64_n136),
	.CO(mult_64_n95),
	.S(mult_64_n96));
   FA_X1 mult_64_U87 (.A(mult_64_n97),
	.B(mult_64_n122),
	.CI(mult_64_n135),
	.CO(mult_64_n93),
	.S(mult_64_n94));
   HA_X1 mult_64_U85 (.A(mult_64_n134),
	.B(mult_64_n113),
	.CO(mult_64_n89),
	.S(mult_64_n90));
   FA_X1 mult_64_U84 (.A(mult_64_n121),
	.B(mult_64_n90),
	.CI(mult_64_n127),
	.CO(mult_64_n87),
	.S(mult_64_n88));
   FA_X1 mult_64_U80 (.A(mult_64_n140),
	.B(mult_64_n133),
	.CI(mult_64_n120),
	.CO(mult_64_n81),
	.S(mult_64_n82));
   FA_X1 mult_64_U77 (.A(mult_64_n119),
	.B(mult_64_n78),
	.CI(mult_64_n132),
	.CO(mult_64_n75),
	.S(mult_64_n76));
   FA_X1 mult_64_U76 (.A(mult_64_n81),
	.B(mult_64_n83),
	.CI(mult_64_n76),
	.CO(mult_64_n73),
	.S(mult_64_n74));
   FA_X1 mult_64_U74 (.A(mult_64_n75),
	.B(mult_64_n131),
	.CI(mult_64_n72),
	.CO(mult_64_n69),
	.S(mult_64_n70));
   FA_X1 mult_64_U72 (.A(mult_64_n124),
	.B(mult_64_n68),
	.CI(mult_64_n71),
	.CO(mult_64_n65),
	.S(mult_64_n66));
   XOR2_X1 mult_64_U70 (.A(mult_64_n67),
	.B(mult_64_n63),
	.Z(mult_64_n64));
   OAI21_X1 add_56_U117 (.A(add_56_n17),
	.B1(add_56_n22),
	.B2(add_56_n16),
	.ZN(add_56_n15));
   OAI21_X1 add_56_U116 (.A(add_56_n10),
	.B1(add_56_n22),
	.B2(add_56_n9),
	.ZN(add_56_n8));
   NAND2_X1 add_56_U115 (.A1(mula1[7]),
	.A2(din_del[1]),
	.ZN(add_56_n38));
   OAI21_X1 add_56_U114 (.A(add_56_n26),
	.B1(add_56_n29),
	.B2(add_56_n25),
	.ZN(add_56_n24));
   NOR2_X1 add_56_U113 (.A1(add_56_n25),
	.A2(add_56_n28),
	.ZN(add_56_n23));
   INV_X1 add_56_U112 (.A(add_56_n25),
	.ZN(add_56_n44));
   INV_X1 add_56_U111 (.A(add_56_n41),
	.ZN(add_56_n39));
   INV_X1 add_56_U110 (.A(add_56_n8),
	.ZN(u[7]));
   INV_X1 add_56_U109 (.A(add_56_n31),
	.ZN(add_56_n30));
   NAND2_X1 add_56_U108 (.A1(add_56_n95),
	.A2(add_56_n85),
	.ZN(add_56_n9));
   AOI21_X1 add_56_U107 (.A(add_56_n12),
	.B1(add_56_n95),
	.B2(add_56_n19),
	.ZN(add_56_n10));
   NAND2_X1 add_56_U106 (.A1(add_56_n95),
	.A2(add_56_n14),
	.ZN(add_56_n1));
   NAND2_X1 add_56_U105 (.A1(mula1[10]),
	.A2(din_del[4]),
	.ZN(add_56_n26));
   NAND2_X1 add_56_U104 (.A1(mula1[6]),
	.A2(din_del[0]),
	.ZN(add_56_n41));
   INV_X1 add_56_U103 (.A(add_56_n14),
	.ZN(add_56_n12));
   NOR2_X1 add_56_U102 (.A1(mula1[10]),
	.A2(din_del[4]),
	.ZN(add_56_n25));
   NAND2_X1 add_56_U100 (.A1(mula1[11]),
	.A2(din_del[5]),
	.ZN(add_56_n17));
   NAND2_X1 add_56_U99 (.A1(mula1[9]),
	.A2(din_del[3]),
	.ZN(add_56_n29));
   NOR2_X1 add_56_U98 (.A1(mula1[9]),
	.A2(din_del[3]),
	.ZN(add_56_n28));
   INV_X1 add_56_U97 (.A(din_del[6]),
	.ZN(add_56_n50));
   NAND2_X1 add_56_U96 (.A1(mula1[8]),
	.A2(din_del[2]),
	.ZN(add_56_n33));
   NAND2_X1 add_56_U95 (.A1(add_56_n49),
	.A2(add_56_n50),
	.ZN(add_56_n14));
   INV_X1 add_56_U94 (.A(add_56_n17),
	.ZN(add_56_n19));
   AND2_X1 add_56_U93 (.A1(add_56_n85),
	.A2(add_56_n17),
	.ZN(add_56_n94));
   INV_X1 add_56_U92 (.A(add_56_n28),
	.ZN(add_56_n45));
   NAND2_X1 add_56_U91 (.A1(add_56_n44),
	.A2(add_56_n26),
	.ZN(add_56_n3));
   INV_X1 add_56_U90 (.A(mula1[12]),
	.ZN(add_56_n49));
   AOI21_X1 add_56_U89 (.A(add_56_n24),
	.B1(add_56_n23),
	.B2(add_56_n92),
	.ZN(add_56_n22));
   XNOR2_X1 add_56_U87 (.A(add_56_n27),
	.B(add_56_n3),
	.ZN(u[4]));
   OAI21_X1 add_56_U86 (.A(add_56_n33),
	.B1(add_56_n32),
	.B2(add_56_n34),
	.ZN(add_56_n31));
   OAI21_X1 add_56_U85 (.A(add_56_n33),
	.B1(add_56_n34),
	.B2(add_56_n32),
	.ZN(add_56_n92));
   OAI21_X1 add_56_U84 (.A(add_56_n29),
	.B1(add_56_n30),
	.B2(add_56_n28),
	.ZN(add_56_n27));
   NOR2_X1 add_56_U83 (.A1(din_del[2]),
	.A2(mula1[8]),
	.ZN(add_56_n32));
   XNOR2_X1 add_56_U82 (.A(add_56_n15),
	.B(add_56_n1),
	.ZN(u[6]));
   XNOR2_X1 add_56_U81 (.A(add_56_n22),
	.B(add_56_n94),
	.ZN(u[5]));
   XNOR2_X1 add_56_U80 (.A(add_56_n34),
	.B(add_56_n91),
	.ZN(u[2]));
   AND2_X1 add_56_U79 (.A1(add_56_n33),
	.A2(add_56_n86),
	.ZN(add_56_n91));
   OR2_X1 add_56_U78 (.A1(add_56_n49),
	.A2(add_56_n50),
	.ZN(add_56_n95));
   AND2_X1 add_56_U77 (.A1(mula1[7]),
	.A2(din_del[1]),
	.ZN(add_56_n90));
   AND2_X1 add_56_U76 (.A1(add_56_n45),
	.A2(add_56_n29),
	.ZN(add_56_n88));
   XNOR2_X1 add_56_U75 (.A(add_56_n30),
	.B(add_56_n88),
	.ZN(u[3]));
   NAND2_X1 add_56_U74 (.A1(add_56_n89),
	.A2(add_56_n38),
	.ZN(add_56_n87));
   AOI21_X1 add_56_U73 (.A(add_56_n90),
	.B1(add_56_n89),
	.B2(add_56_n39),
	.ZN(add_56_n34));
   OR2_X1 add_56_U72 (.A1(din_del[2]),
	.A2(mula1[8]),
	.ZN(add_56_n86));
   OR2_X1 add_56_U71 (.A1(mula1[11]),
	.A2(din_del[5]),
	.ZN(add_56_n85));
   OR2_X1 add_56_U69 (.A1(mula1[7]),
	.A2(din_del[1]),
	.ZN(add_56_n89));
   XNOR2_X1 add_56_U67 (.A(add_56_n87),
	.B(add_56_n39),
	.ZN(u[1]));
   OR2_X1 add_56_U66 (.A1(mula1[6]),
	.A2(din_del[0]),
	.ZN(add_56_n82));
   AND2_X1 add_56_U65 (.A1(add_56_n82),
	.A2(add_56_n41),
	.ZN(u[0]));
   INV_X1 add_56_U64 (.A(add_56_n85),
	.ZN(add_56_n16));
   XNOR2_X1 mult_68_U375 (.A(b1[11]),
	.B(u_del_vec[1]),
	.ZN(mult_68_n155));
   XNOR2_X1 mult_68_U374 (.A(b1[8]),
	.B(u_del_vec[1]),
	.ZN(mult_68_n173));
   XNOR2_X1 mult_68_U373 (.A(b1[6]),
	.B(u_del_vec[1]),
	.ZN(mult_68_n182));
   XNOR2_X1 mult_68_U372 (.A(b1[10]),
	.B(u_del_vec[1]),
	.ZN(mult_68_n164));
   XNOR2_X1 mult_68_U371 (.A(b1[6]),
	.B(u_del_vec[3]),
	.ZN(mult_68_n180));
   XNOR2_X1 mult_68_U370 (.A(b1[10]),
	.B(u_del_vec[3]),
	.ZN(mult_68_n162));
   XNOR2_X1 mult_68_U369 (.A(b1[11]),
	.B(u_del_vec[3]),
	.ZN(mult_68_n153));
   XNOR2_X1 mult_68_U368 (.A(b1[8]),
	.B(u_del_vec[3]),
	.ZN(mult_68_n171));
   XNOR2_X1 mult_68_U367 (.A(b1[6]),
	.B(u_del_vec[2]),
	.ZN(mult_68_n181));
   XNOR2_X1 mult_68_U366 (.A(b1[10]),
	.B(u_del_vec[2]),
	.ZN(mult_68_n163));
   XNOR2_X1 mult_68_U365 (.A(b1[11]),
	.B(u_del_vec[2]),
	.ZN(mult_68_n154));
   XNOR2_X1 mult_68_U364 (.A(b1[8]),
	.B(u_del_vec[2]),
	.ZN(mult_68_n172));
   XNOR2_X1 mult_68_U363 (.A(b1[8]),
	.B(u_del_vec[7]),
	.ZN(mult_68_n167));
   XNOR2_X1 mult_68_U362 (.A(b1[10]),
	.B(u_del_vec[7]),
	.ZN(mult_68_n158));
   XNOR2_X1 mult_68_U361 (.A(b1[6]),
	.B(u_del_vec[7]),
	.ZN(mult_68_n176));
   XNOR2_X1 mult_68_U360 (.A(b1[8]),
	.B(u_del_vec[6]),
	.ZN(mult_68_n168));
   XNOR2_X1 mult_68_U359 (.A(b1[10]),
	.B(u_del_vec[6]),
	.ZN(mult_68_n159));
   XNOR2_X1 mult_68_U358 (.A(b1[6]),
	.B(u_del_vec[6]),
	.ZN(mult_68_n177));
   XNOR2_X1 mult_68_U357 (.A(b1[11]),
	.B(u_del_vec[6]),
	.ZN(mult_68_n150));
   INV_X1 mult_68_U356 (.A(b1[5]),
	.ZN(mult_68_n220));
   XOR2_X1 mult_68_U353 (.A(b1[5]),
	.B(b1[6]),
	.Z(mult_68_n196));
   NAND2_X1 mult_68_U352 (.A1(mult_68_n196),
	.A2(mult_68_n220),
	.ZN(mult_68_n216));
   XOR2_X1 mult_68_U350 (.A(b1[7]),
	.B(b1[8]),
	.Z(mult_68_n195));
   NAND2_X1 mult_68_U349 (.A1(mult_68_n195),
	.A2(FE_OFN2_mult_68_n219),
	.ZN(mult_68_n215));
   XOR2_X1 mult_68_U347 (.A(b1[9]),
	.B(b1[10]),
	.Z(mult_68_n194));
   NAND2_X1 mult_68_U346 (.A1(mult_68_n194),
	.A2(FE_OFN0_mult_68_n218),
	.ZN(mult_68_n214));
   INV_X1 mult_68_U344 (.A(mult_68_n247),
	.ZN(mult_68_n217));
   XOR2_X1 mult_68_U343 (.A(b1[11]),
	.B(b1[10]),
	.Z(mult_68_n247));
   XNOR2_X1 mult_68_U342 (.A(b1[6]),
	.B(u_del_vec[5]),
	.ZN(mult_68_n178));
   XNOR2_X1 mult_68_U341 (.A(b1[6]),
	.B(u_del_vec[4]),
	.ZN(mult_68_n179));
   XNOR2_X1 mult_68_U340 (.A(b1[8]),
	.B(u_del_vec[5]),
	.ZN(mult_68_n169));
   XNOR2_X1 mult_68_U339 (.A(b1[8]),
	.B(u_del_vec[4]),
	.ZN(mult_68_n170));
   XNOR2_X1 mult_68_U338 (.A(b1[10]),
	.B(u_del_vec[5]),
	.ZN(mult_68_n160));
   XNOR2_X1 mult_68_U337 (.A(b1[10]),
	.B(u_del_vec[4]),
	.ZN(mult_68_n161));
   XNOR2_X1 mult_68_U336 (.A(b1[7]),
	.B(b1[6]),
	.ZN(mult_68_n219));
   XNOR2_X1 mult_68_U335 (.A(b1[9]),
	.B(b1[8]),
	.ZN(mult_68_n218));
   XNOR2_X1 mult_68_U331 (.A(b1[11]),
	.B(u_del_vec[5]),
	.ZN(mult_68_n151));
   INV_X1 mult_68_U330 (.A(mult_68_n69),
	.ZN(mult_68_n70));
   NOR2_X1 mult_68_U329 (.A1(mult_68_n217),
	.A2(mult_68_n151),
	.ZN(mult_68_n120));
   XNOR2_X1 mult_68_U328 (.A(b1[11]),
	.B(u_del_vec[4]),
	.ZN(mult_68_n152));
   NOR2_X1 mult_68_U327 (.A1(mult_68_n217),
	.A2(mult_68_n152),
	.ZN(mult_68_n121));
   INV_X1 mult_68_U326 (.A(b1[11]),
	.ZN(mult_68_n106));
   OR2_X1 mult_68_U325 (.A1(u_del_vec[0]),
	.A2(mult_68_n206),
	.ZN(mult_68_n166));
   OR2_X1 mult_68_U324 (.A1(u_del_vec[0]),
	.A2(mult_68_n208),
	.ZN(mult_68_n184));
   XNOR2_X1 mult_68_U323 (.A(b1[10]),
	.B(u_del_vec[0]),
	.ZN(mult_68_n165));
   XNOR2_X1 mult_68_U322 (.A(b1[6]),
	.B(u_del_vec[0]),
	.ZN(mult_68_n183));
   INV_X1 mult_68_U321 (.A(FE_OFN2_mult_68_n219),
	.ZN(mult_68_n111));
   AND2_X1 mult_68_U320 (.A1(u_del_vec[0]),
	.A2(mult_68_n111),
	.ZN(mult_68_n141));
   OR2_X1 mult_68_U316 (.A1(u_del_vec[0]),
	.A2(mult_68_n207),
	.ZN(mult_68_n175));
   INV_X1 mult_68_U315 (.A(b1[8]),
	.ZN(mult_68_n207));
   OAI22_X1 mult_68_U314 (.A1(mult_68_n215),
	.A2(mult_68_n207),
	.B1(mult_68_n175),
	.B2(FE_OFN2_mult_68_n219),
	.ZN(mult_68_n117));
   XNOR2_X1 mult_68_U313 (.A(mult_68_n107),
	.B(mult_68_n119),
	.ZN(mult_68_n65));
   OR2_X1 mult_68_U312 (.A1(mult_68_n67),
	.A2(mult_68_n66),
	.ZN(mult_68_n246));
   OR2_X1 mult_68_U311 (.A1(u_del_vec[0]),
	.A2(mult_68_n106),
	.ZN(mult_68_n157));
   NOR2_X1 mult_68_U310 (.A1(mult_68_n217),
	.A2(mult_68_n155),
	.ZN(mult_68_n124));
   NOR2_X1 mult_68_U309 (.A1(mult_68_n157),
	.A2(mult_68_n217),
	.ZN(mult_68_n115));
   INV_X1 mult_68_U308 (.A(b1[6]),
	.ZN(mult_68_n208));
   OAI22_X1 mult_68_U307 (.A1(mult_68_n216),
	.A2(mult_68_n183),
	.B1(mult_68_n182),
	.B2(mult_68_n220),
	.ZN(mult_68_n149));
   OAI22_X1 mult_68_U306 (.A1(mult_68_n216),
	.A2(mult_68_n208),
	.B1(mult_68_n184),
	.B2(mult_68_n220),
	.ZN(mult_68_n118));
   INV_X1 mult_68_U305 (.A(b1[10]),
	.ZN(mult_68_n206));
   OAI22_X1 mult_68_U304 (.A1(mult_68_n214),
	.A2(mult_68_n165),
	.B1(FE_OFN0_mult_68_n218),
	.B2(mult_68_n164),
	.ZN(mult_68_n132));
   OAI22_X1 mult_68_U303 (.A1(mult_68_n214),
	.A2(mult_68_n206),
	.B1(mult_68_n166),
	.B2(FE_OFN0_mult_68_n218),
	.ZN(mult_68_n116));
   INV_X1 mult_68_U302 (.A(mult_68_n79),
	.ZN(mult_68_n80));
   NOR2_X1 mult_68_U301 (.A1(mult_68_n217),
	.A2(mult_68_n153),
	.ZN(mult_68_n122));
   OAI22_X1 mult_68_U300 (.A1(mult_68_n214),
	.A2(mult_68_n161),
	.B1(FE_OFN0_mult_68_n218),
	.B2(mult_68_n160),
	.ZN(mult_68_n128));
   NAND2_X1 mult_68_U299 (.A1(mult_68_n72),
	.A2(mult_68_n75),
	.ZN(mult_68_n24));
   NAND2_X1 mult_68_U298 (.A1(mult_68_n68),
	.A2(mult_68_n71),
	.ZN(mult_68_n17));
   NAND2_X1 mult_68_U297 (.A1(mult_68_n67),
	.A2(mult_68_n66),
	.ZN(mult_68_n10));
   OAI22_X1 mult_68_U296 (.A1(mult_68_n215),
	.A2(mult_68_n171),
	.B1(FE_OFN2_mult_68_n219),
	.B2(mult_68_n170),
	.ZN(mult_68_n137));
   OAI22_X1 mult_68_U295 (.A1(mult_68_n216),
	.A2(mult_68_n178),
	.B1(mult_68_n177),
	.B2(mult_68_n220),
	.ZN(mult_68_n144));
   AND2_X1 mult_68_U294 (.A1(u_del_vec[0]),
	.A2(mult_68_n247),
	.ZN(mult_68_n125));
   OAI22_X1 mult_68_U293 (.A1(mult_68_n214),
	.A2(mult_68_n163),
	.B1(FE_OFN0_mult_68_n218),
	.B2(mult_68_n162),
	.ZN(mult_68_n130));
   OAI22_X1 mult_68_U292 (.A1(mult_68_n216),
	.A2(mult_68_n177),
	.B1(mult_68_n176),
	.B2(mult_68_n220),
	.ZN(mult_68_n143));
   OAI22_X1 mult_68_U291 (.A1(mult_68_n215),
	.A2(mult_68_n170),
	.B1(FE_OFN2_mult_68_n219),
	.B2(mult_68_n169),
	.ZN(mult_68_n136));
   AOI21_X1 mult_68_U290 (.A(mult_68_n176),
	.B1(mult_68_n216),
	.B2(mult_68_n220),
	.ZN(mult_68_n113));
   INV_X1 mult_68_U289 (.A(mult_68_n113),
	.ZN(mult_68_n142));
   OAI22_X1 mult_68_U288 (.A1(mult_68_n214),
	.A2(mult_68_n162),
	.B1(FE_OFN0_mult_68_n218),
	.B2(mult_68_n161),
	.ZN(mult_68_n129));
   AOI21_X1 mult_68_U287 (.A(mult_68_n167),
	.B1(mult_68_n215),
	.B2(FE_OFN2_mult_68_n219),
	.ZN(mult_68_n110));
   INV_X1 mult_68_U286 (.A(mult_68_n110),
	.ZN(mult_68_n134));
   OAI22_X1 mult_68_U285 (.A1(mult_68_n214),
	.A2(mult_68_n160),
	.B1(FE_OFN0_mult_68_n218),
	.B2(mult_68_n159),
	.ZN(mult_68_n127));
   AOI21_X1 mult_68_U284 (.A(mult_68_n158),
	.B1(mult_68_n214),
	.B2(FE_OFN0_mult_68_n218),
	.ZN(mult_68_n107));
   OAI22_X1 mult_68_U283 (.A1(mult_68_n215),
	.A2(mult_68_n172),
	.B1(FE_OFN2_mult_68_n219),
	.B2(mult_68_n171),
	.ZN(mult_68_n138));
   OAI22_X1 mult_68_U282 (.A1(mult_68_n216),
	.A2(mult_68_n179),
	.B1(mult_68_n178),
	.B2(mult_68_n220),
	.ZN(mult_68_n145));
   OR2_X1 mult_68_U281 (.A1(mult_68_n135),
	.A2(mult_68_n123),
	.ZN(mult_68_n85));
   OAI22_X1 mult_68_U280 (.A1(mult_68_n216),
	.A2(mult_68_n180),
	.B1(mult_68_n179),
	.B2(mult_68_n220),
	.ZN(mult_68_n146));
   OAI22_X1 mult_68_U279 (.A1(mult_68_n215),
	.A2(mult_68_n173),
	.B1(FE_OFN2_mult_68_n219),
	.B2(mult_68_n172),
	.ZN(mult_68_n139));
   AND2_X1 mult_68_U278 (.A1(u_del_vec[0]),
	.A2(mult_68_n108),
	.ZN(mult_68_n133));
   XNOR2_X1 mult_68_U277 (.A(mult_68_n135),
	.B(mult_68_n123),
	.ZN(mult_68_n86));
   OAI22_X1 mult_68_U276 (.A1(mult_68_n214),
	.A2(mult_68_n164),
	.B1(FE_OFN0_mult_68_n218),
	.B2(mult_68_n163),
	.ZN(mult_68_n131));
   OAI22_X1 mult_68_U275 (.A1(mult_68_n215),
	.A2(mult_68_n169),
	.B1(FE_OFN2_mult_68_n219),
	.B2(mult_68_n168),
	.ZN(mult_68_n135));
   OAI22_X1 mult_68_U274 (.A1(mult_68_n216),
	.A2(mult_68_n182),
	.B1(mult_68_n181),
	.B2(mult_68_n220),
	.ZN(mult_68_n148));
   XNOR2_X1 mult_68_U273 (.A(b1[8]),
	.B(u_del_vec[0]),
	.ZN(mult_68_n174));
   OAI22_X1 mult_68_U272 (.A1(mult_68_n215),
	.A2(mult_68_n174),
	.B1(FE_OFN2_mult_68_n219),
	.B2(mult_68_n173),
	.ZN(mult_68_n140));
   OAI22_X1 mult_68_U271 (.A1(mult_68_n216),
	.A2(mult_68_n181),
	.B1(mult_68_n180),
	.B2(mult_68_n220),
	.ZN(mult_68_n147));
   OAI22_X1 mult_68_U270 (.A1(mult_68_n214),
	.A2(mult_68_n159),
	.B1(FE_OFN0_mult_68_n218),
	.B2(mult_68_n158),
	.ZN(mult_68_n69));
   OAI22_X1 mult_68_U269 (.A1(mult_68_n215),
	.A2(mult_68_n168),
	.B1(FE_OFN2_mult_68_n219),
	.B2(mult_68_n167),
	.ZN(mult_68_n79));
   INV_X1 mult_68_U268 (.A(FE_OFN0_mult_68_n218),
	.ZN(mult_68_n108));
   NAND2_X1 mult_68_U267 (.A1(mult_68_n104),
	.A2(mult_68_n117),
	.ZN(mult_68_n50));
   NOR2_X1 mult_68_U266 (.A1(mult_68_n104),
	.A2(mult_68_n117),
	.ZN(mult_68_n49));
   OAI21_X1 mult_68_U265 (.A(mult_68_n50),
	.B1(mult_68_n49),
	.B2(mult_68_n51),
	.ZN(mult_68_n48));
   INV_X1 mult_68_U264 (.A(mult_68_n48),
	.ZN(mult_68_n47));
   OAI21_X1 mult_68_U263 (.A(mult_68_n13),
	.B1(mult_68_n1),
	.B2(mult_68_n12),
	.ZN(mult_68_n11));
   NAND2_X1 mult_68_U262 (.A1(mult_68_n246),
	.A2(mult_68_n10),
	.ZN(mult_68_n2));
   XNOR2_X1 mult_68_U261 (.A(mult_68_n11),
	.B(mult_68_n2),
	.ZN(mulb1[12]));
   INV_X1 mult_68_U260 (.A(mult_68_n23),
	.ZN(mult_68_n60));
   NAND2_X1 mult_68_U259 (.A1(mult_68_n60),
	.A2(mult_68_n24),
	.ZN(mult_68_n4));
   OAI21_X1 mult_68_U258 (.A(mult_68_n27),
	.B1(mult_68_n1),
	.B2(mult_68_n26),
	.ZN(mult_68_n25));
   XNOR2_X1 mult_68_U257 (.A(mult_68_n25),
	.B(mult_68_n4),
	.ZN(mulb1[10]));
   INV_X1 mult_68_U256 (.A(mult_68_n22),
	.ZN(mult_68_n20));
   NAND2_X1 mult_68_U255 (.A1(mult_68_n241),
	.A2(mult_68_n17),
	.ZN(mult_68_n3));
   OAI21_X1 mult_68_U254 (.A(mult_68_n20),
	.B1(mult_68_n1),
	.B2(mult_68_n19),
	.ZN(mult_68_n18));
   XNOR2_X1 mult_68_U253 (.A(mult_68_n18),
	.B(mult_68_n3),
	.ZN(mulb1[11]));
   NAND2_X1 mult_68_U252 (.A1(mult_68_n102),
	.A2(mult_68_n103),
	.ZN(mult_68_n46));
   NAND2_X1 mult_68_U251 (.A1(mult_68_n94),
	.A2(mult_68_n97),
	.ZN(mult_68_n38));
   NAND2_X1 mult_68_U250 (.A1(mult_68_n82),
	.A2(mult_68_n87),
	.ZN(mult_68_n31));
   NOR2_X1 mult_68_U249 (.A1(mult_68_n102),
	.A2(mult_68_n103),
	.ZN(mult_68_n45));
   NAND2_X1 mult_68_U248 (.A1(mult_68_n76),
	.A2(mult_68_n81),
	.ZN(mult_68_n27));
   NAND2_X1 mult_68_U247 (.A1(mult_68_n88),
	.A2(mult_68_n93),
	.ZN(mult_68_n34));
   INV_X1 mult_68_U246 (.A(mult_68_n17),
	.ZN(mult_68_n15));
   AOI21_X1 mult_68_U245 (.A(mult_68_n15),
	.B1(mult_68_n22),
	.B2(mult_68_n241),
	.ZN(mult_68_n13));
   AOI21_X1 mult_68_U244 (.A(mult_68_n240),
	.B1(mult_68_n244),
	.B2(mult_68_n242),
	.ZN(mult_68_n51));
   NOR2_X1 mult_68_U243 (.A1(mult_68_n26),
	.A2(mult_68_n23),
	.ZN(mult_68_n21));
   OAI21_X1 mult_68_U242 (.A(mult_68_n24),
	.B1(mult_68_n23),
	.B2(mult_68_n27),
	.ZN(mult_68_n22));
   INV_X1 mult_68_U241 (.A(mult_68_n21),
	.ZN(mult_68_n19));
   NAND2_X1 mult_68_U240 (.A1(mult_68_n21),
	.A2(mult_68_n241),
	.ZN(mult_68_n12));
   INV_X1 mult_68_U239 (.A(mult_68_n30),
	.ZN(mult_68_n62));
   NAND2_X1 mult_68_U238 (.A1(mult_68_n62),
	.A2(mult_68_n31),
	.ZN(mult_68_n6));
   OAI21_X1 mult_68_U237 (.A(mult_68_n34),
	.B1(mult_68_n35),
	.B2(mult_68_n33),
	.ZN(mult_68_n32));
   XNOR2_X1 mult_68_U236 (.A(mult_68_n32),
	.B(mult_68_n6),
	.ZN(mulb1[8]));
   INV_X1 mult_68_U235 (.A(mult_68_n33),
	.ZN(mult_68_n63));
   NAND2_X1 mult_68_U234 (.A1(mult_68_n63),
	.A2(mult_68_n34),
	.ZN(mult_68_n7));
   XOR2_X1 mult_68_U233 (.A(mult_68_n35),
	.B(mult_68_n7),
	.Z(mulb1[7]));
   OAI21_X1 mult_68_U232 (.A(mult_68_n46),
	.B1(mult_68_n45),
	.B2(mult_68_n47),
	.ZN(mult_68_n44));
   AOI21_X1 mult_68_U231 (.A(mult_68_n243),
	.B1(mult_68_n245),
	.B2(mult_68_n44),
	.ZN(mult_68_n39));
   INV_X1 mult_68_U230 (.A(mult_68_n26),
	.ZN(mult_68_n61));
   NAND2_X1 mult_68_U229 (.A1(mult_68_n61),
	.A2(mult_68_n27),
	.ZN(mult_68_n5));
   XOR2_X1 mult_68_U228 (.A(mult_68_n1),
	.B(mult_68_n5),
	.Z(mulb1[9]));
   OAI21_X1 mult_68_U227 (.A(mult_68_n31),
	.B1(mult_68_n30),
	.B2(mult_68_n34),
	.ZN(mult_68_n29));
   NOR2_X1 mult_68_U226 (.A1(mult_68_n30),
	.A2(mult_68_n33),
	.ZN(mult_68_n28));
   AOI21_X1 mult_68_U225 (.A(mult_68_n29),
	.B1(mult_68_n28),
	.B2(mult_68_n36),
	.ZN(mult_68_n1));
   INV_X1 mult_68_U224 (.A(mult_68_n37),
	.ZN(mult_68_n64));
   NAND2_X1 mult_68_U223 (.A1(mult_68_n64),
	.A2(mult_68_n38),
	.ZN(mult_68_n8));
   XOR2_X1 mult_68_U222 (.A(mult_68_n8),
	.B(mult_68_n39),
	.Z(mulb1[6]));
   INV_X1 mult_68_U221 (.A(mult_68_n36),
	.ZN(mult_68_n35));
   NOR2_X1 mult_68_U220 (.A1(mult_68_n217),
	.A2(mult_68_n150),
	.ZN(mult_68_n119));
   NOR2_X1 mult_68_U219 (.A1(mult_68_n94),
	.A2(mult_68_n97),
	.ZN(mult_68_n37));
   NOR2_X1 mult_68_U218 (.A1(mult_68_n76),
	.A2(mult_68_n81),
	.ZN(mult_68_n26));
   OAI21_X1 mult_68_U217 (.A(mult_68_n38),
	.B1(mult_68_n37),
	.B2(mult_68_n39),
	.ZN(mult_68_n36));
   OR2_X1 mult_68_U216 (.A1(mult_68_n98),
	.A2(mult_68_n101),
	.ZN(mult_68_n245));
   OR2_X1 mult_68_U215 (.A1(mult_68_n148),
	.A2(mult_68_n141),
	.ZN(mult_68_n244));
   AND2_X1 mult_68_U214 (.A1(mult_68_n98),
	.A2(mult_68_n101),
	.ZN(mult_68_n243));
   AND2_X1 mult_68_U213 (.A1(mult_68_n149),
	.A2(mult_68_n118),
	.ZN(mult_68_n242));
   OR2_X1 mult_68_U212 (.A1(mult_68_n68),
	.A2(mult_68_n71),
	.ZN(mult_68_n241));
   AND2_X1 mult_68_U211 (.A1(mult_68_n148),
	.A2(mult_68_n141),
	.ZN(mult_68_n240));
   NOR2_X1 mult_68_U210 (.A1(mult_68_n82),
	.A2(mult_68_n87),
	.ZN(mult_68_n30));
   NOR2_X1 mult_68_U209 (.A1(mult_68_n88),
	.A2(mult_68_n93),
	.ZN(mult_68_n33));
   NOR2_X1 mult_68_U208 (.A1(mult_68_n72),
	.A2(mult_68_n75),
	.ZN(mult_68_n23));
   NOR2_X1 mult_68_U207 (.A1(mult_68_n217),
	.A2(mult_68_n154),
	.ZN(mult_68_n123));
   HA_X1 mult_68_U93 (.A(mult_68_n140),
	.B(mult_68_n147),
	.CO(mult_68_n103),
	.S(mult_68_n104));
   FA_X1 mult_68_U92 (.A(mult_68_n146),
	.B(mult_68_n133),
	.CI(mult_68_n139),
	.CO(mult_68_n101),
	.S(mult_68_n102));
   HA_X1 mult_68_U91 (.A(mult_68_n116),
	.B(mult_68_n132),
	.CO(mult_68_n99),
	.S(mult_68_n100));
   FA_X1 mult_68_U90 (.A(mult_68_n138),
	.B(mult_68_n145),
	.CI(mult_68_n100),
	.CO(mult_68_n97),
	.S(mult_68_n98));
   FA_X1 mult_68_U89 (.A(mult_68_n144),
	.B(mult_68_n125),
	.CI(mult_68_n137),
	.CO(mult_68_n95),
	.S(mult_68_n96));
   FA_X1 mult_68_U88 (.A(mult_68_n99),
	.B(mult_68_n131),
	.CI(mult_68_n96),
	.CO(mult_68_n93),
	.S(mult_68_n94));
   HA_X1 mult_68_U87 (.A(mult_68_n115),
	.B(mult_68_n124),
	.CO(mult_68_n91),
	.S(mult_68_n92));
   FA_X1 mult_68_U86 (.A(mult_68_n130),
	.B(mult_68_n143),
	.CI(mult_68_n136),
	.CO(mult_68_n89),
	.S(mult_68_n90));
   FA_X1 mult_68_U85 (.A(mult_68_n95),
	.B(mult_68_n92),
	.CI(mult_68_n90),
	.CO(mult_68_n87),
	.S(mult_68_n88));
   FA_X1 mult_68_U82 (.A(mult_68_n142),
	.B(mult_68_n129),
	.CI(mult_68_n91),
	.CO(mult_68_n83),
	.S(mult_68_n84));
   FA_X1 mult_68_U81 (.A(mult_68_n89),
	.B(mult_68_n86),
	.CI(mult_68_n84),
	.CO(mult_68_n81),
	.S(mult_68_n82));
   FA_X1 mult_68_U79 (.A(mult_68_n122),
	.B(mult_68_n128),
	.CI(mult_68_n80),
	.CO(mult_68_n77),
	.S(mult_68_n78));
   FA_X1 mult_68_U78 (.A(mult_68_n83),
	.B(mult_68_n85),
	.CI(mult_68_n78),
	.CO(mult_68_n75),
	.S(mult_68_n76));
   FA_X1 mult_68_U77 (.A(mult_68_n127),
	.B(mult_68_n79),
	.CI(mult_68_n134),
	.CO(mult_68_n73),
	.S(mult_68_n74));
   FA_X1 mult_68_U76 (.A(mult_68_n77),
	.B(mult_68_n121),
	.CI(mult_68_n74),
	.CO(mult_68_n71),
	.S(mult_68_n72));
   FA_X1 mult_68_U74 (.A(mult_68_n70),
	.B(mult_68_n120),
	.CI(mult_68_n73),
	.CO(mult_68_n67),
	.S(mult_68_n68));
   XOR2_X1 mult_68_U72 (.A(mult_68_n69),
	.B(mult_68_n65),
	.Z(mult_68_n66));
   OAI21_X1 add_72_U115 (.A(add_72_n25),
	.B1(add_72_n1),
	.B2(add_72_n24),
	.ZN(add_72_n23));
   OAI21_X1 add_72_U114 (.A(add_72_n18),
	.B1(add_72_n1),
	.B2(add_72_n85),
	.ZN(add_72_n16));
   OAI21_X1 add_72_U113 (.A(add_72_n11),
	.B1(add_72_n1),
	.B2(add_72_n10),
	.ZN(add_72_n9));
   XNOR2_X1 add_72_U112 (.A(add_72_n16),
	.B(add_72_n2),
	.ZN(y[6]));
   INV_X1 add_72_U111 (.A(add_72_n9),
	.ZN(y[7]));
   XNOR2_X1 add_72_U110 (.A(add_72_n23),
	.B(add_72_n3),
	.ZN(y[5]));
   NAND2_X1 add_72_U109 (.A1(mulb0[9]),
	.A2(mulb1[9]),
	.ZN(add_72_n29));
   OAI21_X1 add_72_U108 (.A(add_72_n29),
	.B1(add_72_n28),
	.B2(add_72_n32),
	.ZN(add_72_n27));
   NOR2_X1 add_72_U107 (.A1(add_72_n28),
	.A2(add_72_n31),
	.ZN(add_72_n26));
   INV_X1 add_72_U106 (.A(add_72_n28),
	.ZN(add_72_n42));
   NAND2_X1 add_72_U105 (.A1(mulb0[10]),
	.A2(mulb1[10]),
	.ZN(add_72_n25));
   NOR2_X1 add_72_U104 (.A1(mulb1[10]),
	.A2(mulb0[10]),
	.ZN(add_72_n24));
   INV_X1 add_72_U103 (.A(add_72_n21),
	.ZN(add_72_n40));
   NAND2_X1 add_72_U102 (.A1(add_72_n19),
	.A2(add_72_n91),
	.ZN(add_72_n10));
   AOI21_X1 add_72_U101 (.A(add_72_n13),
	.B1(add_72_n92),
	.B2(add_72_n91),
	.ZN(add_72_n11));
   NAND2_X1 add_72_U100 (.A1(add_72_n15),
	.A2(add_72_n91),
	.ZN(add_72_n2));
   NOR2_X1 add_72_U99 (.A1(add_72_n21),
	.A2(add_72_n24),
	.ZN(add_72_n19));
   OAI21_X1 add_72_U98 (.A(add_72_n36),
	.B1(add_72_n35),
	.B2(add_72_n38),
	.ZN(add_72_n34));
   INV_X1 add_72_U97 (.A(add_72_n20),
	.ZN(add_72_n18));
   NOR2_X1 add_72_U96 (.A1(mulb0[7]),
	.A2(mulb1[7]),
	.ZN(add_72_n35));
   OAI21_X1 add_72_U95 (.A(add_72_n22),
	.B1(add_72_n25),
	.B2(add_72_n21),
	.ZN(add_72_n20));
   INV_X1 add_72_U94 (.A(add_72_n24),
	.ZN(add_72_n41));
   INV_X1 add_72_U93 (.A(add_72_n15),
	.ZN(add_72_n13));
   AOI21_X1 add_72_U92 (.A(add_72_n27),
	.B1(add_72_n26),
	.B2(add_72_n34),
	.ZN(add_72_n1));
   OAI21_X1 add_72_U90 (.A(add_72_n22),
	.B1(add_72_n21),
	.B2(add_72_n25),
	.ZN(add_72_n92));
   NAND2_X1 add_72_U89 (.A1(mulb0[11]),
	.A2(mulb1[11]),
	.ZN(add_72_n22));
   NAND2_X1 add_72_U88 (.A1(mulb0[8]),
	.A2(mulb1[8]),
	.ZN(add_72_n32));
   NOR2_X1 add_72_U87 (.A1(mulb0[8]),
	.A2(mulb1[8]),
	.ZN(add_72_n31));
   NAND2_X1 add_72_U86 (.A1(mulb0[7]),
	.A2(mulb1[7]),
	.ZN(add_72_n36));
   NAND2_X1 add_72_U85 (.A1(add_72_n32),
	.A2(add_72_n79),
	.ZN(add_72_n6));
   XOR2_X1 add_72_U84 (.A(add_72_n6),
	.B(add_72_n33),
	.Z(y[2]));
   NAND2_X1 add_72_U83 (.A1(add_72_n42),
	.A2(add_72_n29),
	.ZN(add_72_n5));
   XNOR2_X1 add_72_U82 (.A(add_72_n5),
	.B(add_72_n30),
	.ZN(y[3]));
   NAND2_X1 add_72_U81 (.A1(add_72_n40),
	.A2(add_72_n22),
	.ZN(add_72_n3));
   OR2_X1 add_72_U80 (.A1(mulb0[6]),
	.A2(mulb1[6]),
	.ZN(add_72_n90));
   NAND2_X1 add_72_U79 (.A1(mulb0[6]),
	.A2(mulb1[6]),
	.ZN(add_72_n38));
   NOR2_X1 add_72_U78 (.A1(mulb0[9]),
	.A2(mulb1[9]),
	.ZN(add_72_n28));
   OAI21_X1 add_72_U77 (.A(add_72_n32),
	.B1(add_72_n33),
	.B2(add_72_n31),
	.ZN(add_72_n30));
   INV_X1 add_72_U76 (.A(add_72_n34),
	.ZN(add_72_n33));
   AND2_X1 add_72_U75 (.A1(add_72_n38),
	.A2(add_72_n90),
	.ZN(y[0]));
   OR2_X1 add_72_U72 (.A1(mulb0[12]),
	.A2(mulb1[12]),
	.ZN(add_72_n15));
   OR2_X1 add_72_U70 (.A1(add_72_n24),
	.A2(add_72_n21),
	.ZN(add_72_n85));
   NOR2_X1 add_72_U69 (.A1(mulb0[11]),
	.A2(mulb1[11]),
	.ZN(add_72_n21));
   NAND2_X1 add_72_U67 (.A1(mulb0[12]),
	.A2(mulb1[12]),
	.ZN(add_72_n91));
   NAND2_X1 add_72_U66 (.A1(add_72_n25),
	.A2(add_72_n41),
	.ZN(add_72_n81));
   XOR2_X1 add_72_U65 (.A(add_72_n1),
	.B(add_72_n81),
	.Z(y[4]));
   OR2_X1 add_72_U62 (.A1(mulb0[8]),
	.A2(mulb1[8]),
	.ZN(add_72_n79));
   OR2_X1 add_72_U61 (.A1(mulb0[7]),
	.A2(mulb1[7]),
	.ZN(add_72_n78));
   NAND2_X1 add_72_U60 (.A1(add_72_n78),
	.A2(add_72_n36),
	.ZN(add_72_n76));
   XOR2_X1 add_72_U59 (.A(add_72_n76),
	.B(add_72_n38),
	.Z(y[1]));
   XNOR2_X1 mult_66_U391 (.A(u[6]),
	.B(b0[6]),
	.ZN(mult_66_n174));
   XNOR2_X1 mult_66_U390 (.A(u[6]),
	.B(b0[8]),
	.ZN(mult_66_n165));
   XNOR2_X1 mult_66_U389 (.A(u[6]),
	.B(b0[10]),
	.ZN(mult_66_n156));
   XNOR2_X1 mult_66_U388 (.A(u[6]),
	.B(b0[11]),
	.ZN(mult_66_n147));
   XNOR2_X1 mult_66_U387 (.A(u[4]),
	.B(b0[10]),
	.ZN(mult_66_n158));
   XNOR2_X1 mult_66_U386 (.A(u[4]),
	.B(b0[8]),
	.ZN(mult_66_n167));
   XNOR2_X1 mult_66_U385 (.A(u[4]),
	.B(b0[6]),
	.ZN(mult_66_n176));
   OAI22_X1 mult_66_U384 (.A1(FE_OFN3_mult_66_n199),
	.A2(mult_66_n243),
	.B1(mult_66_n159),
	.B2(mult_66_n195),
	.ZN(mult_66_n125));
   XNOR2_X1 mult_66_U383 (.A(u[4]),
	.B(b0[11]),
	.ZN(mult_66_n149));
   OAI22_X1 mult_66_U382 (.A1(mult_66_n157),
	.A2(FE_OFN3_mult_66_n199),
	.B1(mult_66_n158),
	.B2(mult_66_n195),
	.ZN(mult_66_n124));
   OAI21_X1 mult_66_U381 (.A(mult_66_n20),
	.B1(mult_66_n19),
	.B2(mult_66_n1),
	.ZN(mult_66_n18));
   OAI21_X1 mult_66_U380 (.A(mult_66_n13),
	.B1(mult_66_n1),
	.B2(mult_66_n272),
	.ZN(mult_66_n11));
   XNOR2_X1 mult_66_U379 (.A(u[5]),
	.B(b0[6]),
	.ZN(mult_66_n175));
   XNOR2_X1 mult_66_U378 (.A(u[5]),
	.B(b0[8]),
	.ZN(mult_66_n166));
   XNOR2_X1 mult_66_U377 (.A(u[5]),
	.B(b0[10]),
	.ZN(mult_66_n157));
   XNOR2_X1 mult_66_U376 (.A(u[5]),
	.B(b0[11]),
	.ZN(mult_66_n148));
   XNOR2_X1 mult_66_U375 (.A(u[2]),
	.B(b0[8]),
	.ZN(mult_66_n169));
   XNOR2_X1 mult_66_U374 (.A(u[2]),
	.B(b0[6]),
	.ZN(mult_66_n178));
   XNOR2_X1 mult_66_U373 (.A(u[2]),
	.B(b0[10]),
	.ZN(mult_66_n160));
   XNOR2_X1 mult_66_U372 (.A(u[2]),
	.B(b0[11]),
	.ZN(mult_66_n151));
   OAI22_X1 mult_66_U371 (.A1(mult_66_n175),
	.A2(mult_66_n217),
	.B1(mult_66_n176),
	.B2(mult_66_n197),
	.ZN(mult_66_n142));
   OAI22_X1 mult_66_U370 (.A1(mult_66_n174),
	.A2(mult_66_n217),
	.B1(mult_66_n175),
	.B2(mult_66_n197),
	.ZN(mult_66_n141));
   NOR2_X1 mult_66_U369 (.A1(mult_66_n95),
	.A2(mult_66_n98),
	.ZN(mult_66_n38));
   OAI22_X1 mult_66_U368 (.A1(mult_66_n253),
	.A2(mult_66_n197),
	.B1(mult_66_n173),
	.B2(mult_66_n217),
	.ZN(mult_66_n110));
   INV_X1 mult_66_U367 (.A(mult_66_n110),
	.ZN(mult_66_n139));
   OAI22_X1 mult_66_U366 (.A1(mult_66_n174),
	.A2(mult_66_n197),
	.B1(mult_66_n253),
	.B2(mult_66_n217),
	.ZN(mult_66_n140));
   OAI21_X1 mult_66_U365 (.A(mult_66_n24),
	.B1(mult_66_n23),
	.B2(mult_66_n27),
	.ZN(mult_66_n22));
   OAI21_X1 mult_66_U364 (.A(mult_66_n27),
	.B1(mult_66_n28),
	.B2(mult_66_n26),
	.ZN(mult_66_n25));
   XNOR2_X1 mult_66_U363 (.A(mult_66_n11),
	.B(mult_66_n2),
	.ZN(mulb0[12]));
   XNOR2_X1 mult_66_U362 (.A(mult_66_n18),
	.B(mult_66_n3),
	.ZN(mulb0[11]));
   OAI22_X1 mult_66_U361 (.A1(mult_66_n178),
	.A2(mult_66_n217),
	.B1(mult_66_n179),
	.B2(mult_66_n197),
	.ZN(mult_66_n145));
   XNOR2_X1 mult_66_U360 (.A(mult_66_n8),
	.B(mult_66_n37),
	.ZN(mulb0[6]));
   XNOR2_X1 mult_66_U358 (.A(u[7]),
	.B(b0[8]),
	.ZN(mult_66_n164));
   INV_X1 mult_66_U357 (.A(mult_66_n76),
	.ZN(mult_66_n77));
   NOR2_X1 mult_66_U356 (.A1(mult_66_n23),
	.A2(mult_66_n26),
	.ZN(mult_66_n21));
   INV_X1 mult_66_U355 (.A(mult_66_n23),
	.ZN(mult_66_n58));
   OAI22_X1 mult_66_U354 (.A1(mult_66_n160),
	.A2(FE_OFN3_mult_66_n199),
	.B1(mult_66_n246),
	.B2(mult_66_n195),
	.ZN(mult_66_n127));
   OAI22_X1 mult_66_U353 (.A1(mult_66_n245),
	.A2(FE_OFN3_mult_66_n199),
	.B1(mult_66_n160),
	.B2(mult_66_n195),
	.ZN(mult_66_n126));
   INV_X1 mult_66_U352 (.A(mult_66_n29),
	.ZN(mult_66_n28));
   OAI22_X1 mult_66_U351 (.A1(mult_66_n165),
	.A2(mult_66_n196),
	.B1(mult_66_n164),
	.B2(mult_66_n200),
	.ZN(mult_66_n131));
   NAND2_X1 mult_66_U350 (.A1(mult_66_n65),
	.A2(mult_66_n68),
	.ZN(mult_66_n17));
   INV_X1 mult_66_U349 (.A(mult_66_n107),
	.ZN(mult_66_n130));
   OAI21_X1 mult_66_U348 (.A(mult_66_n31),
	.B1(mult_66_n32),
	.B2(mult_66_n30),
	.ZN(mult_66_n29));
   XNOR2_X1 mult_66_U347 (.A(mult_66_n25),
	.B(mult_66_n5),
	.ZN(mulb0[9]));
   OAI22_X1 mult_66_U346 (.A1(mult_66_n166),
	.A2(mult_66_n200),
	.B1(mult_66_n167),
	.B2(mult_66_n196),
	.ZN(mult_66_n133));
   OAI22_X1 mult_66_U345 (.A1(mult_66_n165),
	.A2(mult_66_n200),
	.B1(mult_66_n166),
	.B2(mult_66_n196),
	.ZN(mult_66_n132));
   NAND2_X1 mult_66_U344 (.A1(mult_66_n79),
	.A2(mult_66_n84),
	.ZN(mult_66_n27));
   XNOR2_X1 mult_66_U343 (.A(u[1]),
	.B(b0[10]),
	.ZN(mult_66_n161));
   OAI22_X1 mult_66_U342 (.A1(mult_66_n161),
	.A2(FE_OFN3_mult_66_n199),
	.B1(mult_66_n162),
	.B2(mult_66_n195),
	.ZN(mult_66_n128));
   XNOR2_X1 mult_66_U341 (.A(u[7]),
	.B(b0[6]),
	.ZN(mult_66_n173));
   XNOR2_X1 mult_66_U340 (.A(mult_66_n88),
	.B(mult_66_n118),
	.ZN(mult_66_n83));
   XNOR2_X1 mult_66_U339 (.A(u[3]),
	.B(b0[11]),
	.ZN(mult_66_n150));
   XNOR2_X1 mult_66_U338 (.A(u[1]),
	.B(b0[8]),
	.ZN(mult_66_n170));
   XNOR2_X1 mult_66_U337 (.A(u[1]),
	.B(b0[11]),
	.ZN(mult_66_n152));
   XNOR2_X1 mult_66_U336 (.A(u[1]),
	.B(b0[6]),
	.ZN(mult_66_n179));
   NAND2_X1 mult_66_U335 (.A1(mult_66_n73),
	.A2(mult_66_n78),
	.ZN(mult_66_n24));
   AOI21_X1 mult_66_U334 (.A(mult_66_n22),
	.B1(mult_66_n21),
	.B2(mult_66_n29),
	.ZN(mult_66_n1));
   OAI22_X1 mult_66_U332 (.A1(mult_66_n156),
	.A2(FE_OFN3_mult_66_n199),
	.B1(mult_66_n237),
	.B2(mult_66_n195),
	.ZN(mult_66_n123));
   NAND2_X1 mult_66_U331 (.A1(mult_66_n90),
	.A2(mult_66_n85),
	.ZN(mult_66_n31));
   XNOR2_X1 mult_66_U330 (.A(u[3]),
	.B(b0[8]),
	.ZN(mult_66_n168));
   XNOR2_X1 mult_66_U329 (.A(u[3]),
	.B(b0[6]),
	.ZN(mult_66_n177));
   XNOR2_X1 mult_66_U328 (.A(u[3]),
	.B(b0[10]),
	.ZN(mult_66_n159));
   XNOR2_X1 mult_66_U327 (.A(u[7]),
	.B(b0[10]),
	.ZN(mult_66_n155));
   INV_X1 mult_66_U326 (.A(b0[11]),
	.ZN(mult_66_n202));
   INV_X1 mult_66_U325 (.A(b0[10]),
	.ZN(mult_66_n203));
   INV_X1 mult_66_U324 (.A(b0[6]),
	.ZN(mult_66_n205));
   INV_X1 mult_66_U323 (.A(b0[8]),
	.ZN(mult_66_n204));
   XOR2_X1 mult_66_U322 (.A(b0[5]),
	.B(b0[6]),
	.Z(mult_66_n193));
   NAND2_X1 mult_66_U321 (.A1(mult_66_n193),
	.A2(mult_66_n217),
	.ZN(mult_66_n197));
   INV_X1 mult_66_U320 (.A(b0[5]),
	.ZN(mult_66_n217));
   XOR2_X1 mult_66_U319 (.A(b0[9]),
	.B(b0[10]),
	.Z(mult_66_n191));
   NAND2_X1 mult_66_U318 (.A1(mult_66_n191),
	.A2(FE_OFN3_mult_66_n199),
	.ZN(mult_66_n195));
   XOR2_X1 mult_66_U317 (.A(b0[7]),
	.B(b0[8]),
	.Z(mult_66_n192));
   NAND2_X1 mult_66_U316 (.A1(mult_66_n192),
	.A2(mult_66_n200),
	.ZN(mult_66_n196));
   XNOR2_X1 mult_66_U315 (.A(u[0]),
	.B(b0[6]),
	.ZN(mult_66_n180));
   NOR2_X1 mult_66_U314 (.A1(mult_66_n148),
	.A2(mult_66_n198),
	.ZN(mult_66_n66));
   XNOR2_X1 mult_66_U313 (.A(u[0]),
	.B(b0[10]),
	.ZN(mult_66_n162));
   NOR2_X1 mult_66_U312 (.A1(mult_66_n149),
	.A2(mult_66_n198),
	.ZN(mult_66_n117));
   XNOR2_X1 mult_66_U311 (.A(u[0]),
	.B(b0[8]),
	.ZN(mult_66_n171));
   NOR2_X1 mult_66_U310 (.A1(mult_66_n151),
	.A2(mult_66_n198),
	.ZN(mult_66_n118));
   OR2_X1 mult_66_U309 (.A1(u[0]),
	.A2(mult_66_n205),
	.ZN(mult_66_n181));
   INV_X1 mult_66_U308 (.A(mult_66_n200),
	.ZN(mult_66_n108));
   AND2_X1 mult_66_U307 (.A1(u[0]),
	.A2(mult_66_n108),
	.ZN(mult_66_n138));
   OR2_X1 mult_66_U306 (.A1(u[0]),
	.A2(mult_66_n203),
	.ZN(mult_66_n163));
   OAI22_X1 mult_66_U305 (.A1(mult_66_n163),
	.A2(FE_OFN3_mult_66_n199),
	.B1(mult_66_n195),
	.B2(mult_66_n203),
	.ZN(mult_66_n113));
   OR2_X1 mult_66_U304 (.A1(u[0]),
	.A2(mult_66_n202),
	.ZN(mult_66_n154));
   NOR2_X1 mult_66_U303 (.A1(mult_66_n152),
	.A2(mult_66_n198),
	.ZN(mult_66_n119));
   NOR2_X1 mult_66_U302 (.A1(mult_66_n154),
	.A2(mult_66_n198),
	.ZN(mult_66_n112));
   INV_X1 mult_66_U301 (.A(mult_66_n198),
	.ZN(mult_66_n102));
   AND2_X1 mult_66_U300 (.A1(u[0]),
	.A2(mult_66_n102),
	.ZN(mult_66_n120));
   OAI22_X1 mult_66_U299 (.A1(mult_66_n167),
	.A2(mult_66_n200),
	.B1(mult_66_n168),
	.B2(mult_66_n196),
	.ZN(mult_66_n134));
   INV_X1 mult_66_U298 (.A(FE_OFN3_mult_66_n199),
	.ZN(mult_66_n105));
   OAI22_X1 mult_66_U297 (.A1(mult_66_n169),
	.A2(mult_66_n200),
	.B1(mult_66_n170),
	.B2(mult_66_n196),
	.ZN(mult_66_n136));
   AND2_X1 mult_66_U296 (.A1(u[0]),
	.A2(mult_66_n105),
	.ZN(mult_66_n129));
   OAI22_X1 mult_66_U295 (.A1(mult_66_n156),
	.A2(mult_66_n195),
	.B1(mult_66_n155),
	.B2(FE_OFN3_mult_66_n199),
	.ZN(mult_66_n122));
   INV_X1 mult_66_U294 (.A(mult_66_n66),
	.ZN(mult_66_n67));
   OAI22_X1 mult_66_U293 (.A1(mult_66_n168),
	.A2(mult_66_n200),
	.B1(mult_66_n169),
	.B2(mult_66_n196),
	.ZN(mult_66_n135));
   XNOR2_X1 mult_66_U292 (.A(mult_66_n104),
	.B(mult_66_n116),
	.ZN(mult_66_n62));
   OR2_X1 mult_66_U291 (.A1(u[0]),
	.A2(mult_66_n204),
	.ZN(mult_66_n172));
   OAI22_X1 mult_66_U290 (.A1(mult_66_n170),
	.A2(mult_66_n200),
	.B1(mult_66_n171),
	.B2(mult_66_n196),
	.ZN(mult_66_n137));
   OAI22_X1 mult_66_U289 (.A1(mult_66_n172),
	.A2(mult_66_n200),
	.B1(mult_66_n196),
	.B2(mult_66_n204),
	.ZN(mult_66_n114));
   OAI22_X1 mult_66_U288 (.A1(mult_66_n176),
	.A2(mult_66_n217),
	.B1(mult_66_n177),
	.B2(mult_66_n197),
	.ZN(mult_66_n143));
   OAI22_X1 mult_66_U287 (.A1(mult_66_n179),
	.A2(mult_66_n217),
	.B1(mult_66_n180),
	.B2(mult_66_n197),
	.ZN(mult_66_n146));
   OAI22_X1 mult_66_U286 (.A1(mult_66_n181),
	.A2(mult_66_n217),
	.B1(mult_66_n197),
	.B2(mult_66_n205),
	.ZN(mult_66_n115));
   NAND2_X1 mult_66_U284 (.A1(mult_66_n64),
	.A2(mult_66_n63),
	.ZN(mult_66_n10));
   AND2_X1 mult_66_U283 (.A1(mult_66_n99),
	.A2(mult_66_n143),
	.ZN(mult_66_n278));
   OR2_X1 mult_66_U282 (.A1(mult_66_n99),
	.A2(mult_66_n143),
	.ZN(mult_66_n277));
   OR2_X1 mult_66_U281 (.A1(mult_66_n64),
	.A2(mult_66_n63),
	.ZN(mult_66_n276));
   OR2_X1 mult_66_U280 (.A1(mult_66_n145),
	.A2(mult_66_n138),
	.ZN(mult_66_n275));
   AND2_X1 mult_66_U279 (.A1(mult_66_n145),
	.A2(mult_66_n138),
	.ZN(mult_66_n274));
   NAND2_X1 mult_66_U278 (.A1(mult_66_n69),
	.A2(mult_66_n72),
	.ZN(mult_66_n20));
   NOR2_X1 mult_66_U277 (.A1(mult_66_n144),
	.A2(mult_66_n101),
	.ZN(mult_66_n46));
   NAND2_X1 mult_66_U276 (.A1(mult_66_n144),
	.A2(mult_66_n101),
	.ZN(mult_66_n47));
   AOI21_X1 mult_66_U275 (.A(mult_66_n274),
	.B1(mult_66_n275),
	.B2(mult_66_n270),
	.ZN(mult_66_n48));
   NOR2_X1 mult_66_U274 (.A1(mult_66_n85),
	.A2(mult_66_n90),
	.ZN(mult_66_n30));
   AOI21_X1 mult_66_U273 (.A(mult_66_n278),
	.B1(mult_66_n277),
	.B2(mult_66_n45),
	.ZN(mult_66_n40));
   NAND2_X1 mult_66_U272 (.A1(mult_66_n95),
	.A2(mult_66_n98),
	.ZN(mult_66_n39));
   OR2_X1 mult_66_U271 (.A1(mult_66_n19),
	.A2(mult_66_n16),
	.ZN(mult_66_n272));
   OAI21_X1 mult_66_U270 (.A(mult_66_n17),
	.B1(mult_66_n20),
	.B2(mult_66_n16),
	.ZN(mult_66_n15));
   INV_X1 mult_66_U269 (.A(mult_66_n15),
	.ZN(mult_66_n13));
   NAND2_X1 mult_66_U268 (.A1(mult_66_n276),
	.A2(mult_66_n10),
	.ZN(mult_66_n2));
   NAND2_X1 mult_66_U267 (.A1(mult_66_n58),
	.A2(mult_66_n24),
	.ZN(mult_66_n5));
   XNOR2_X1 mult_66_U266 (.A(mult_66_n1),
	.B(mult_66_n271),
	.ZN(mulb0[10]));
   INV_X1 mult_66_U265 (.A(mult_66_n26),
	.ZN(mult_66_n59));
   INV_X1 mult_66_U264 (.A(mult_66_n16),
	.ZN(mult_66_n56));
   NAND2_X1 mult_66_U263 (.A1(mult_66_n56),
	.A2(mult_66_n17),
	.ZN(mult_66_n3));
   NAND2_X1 mult_66_U262 (.A1(mult_66_n36),
	.A2(mult_66_n273),
	.ZN(mult_66_n8));
   AND2_X1 mult_66_U261 (.A1(mult_66_n146),
	.A2(mult_66_n115),
	.ZN(mult_66_n270));
   NOR2_X1 mult_66_U260 (.A1(mult_66_n147),
	.A2(mult_66_n198),
	.ZN(mult_66_n116));
   OAI21_X1 mult_66_U259 (.A(mult_66_n47),
	.B1(mult_66_n46),
	.B2(mult_66_n48),
	.ZN(mult_66_n45));
   AND2_X1 mult_66_U258 (.A1(mult_66_n57),
	.A2(mult_66_n20),
	.ZN(mult_66_n271));
   NOR2_X1 mult_66_U257 (.A1(mult_66_n150),
	.A2(mult_66_n198),
	.ZN(mult_66_n76));
   NAND3_X1 mult_66_U256 (.A1(mult_66_n267),
	.A2(mult_66_n268),
	.A3(mult_66_n269),
	.ZN(mult_66_n78));
   NAND2_X1 mult_66_U255 (.A1(mult_66_n86),
	.A2(mult_66_n132),
	.ZN(mult_66_n269));
   NAND2_X1 mult_66_U254 (.A1(mult_66_n81),
	.A2(mult_66_n132),
	.ZN(mult_66_n268));
   NAND2_X1 mult_66_U253 (.A1(mult_66_n81),
	.A2(mult_66_n86),
	.ZN(mult_66_n267));
   NOR2_X1 mult_66_U252 (.A1(mult_66_n73),
	.A2(mult_66_n78),
	.ZN(mult_66_n23));
   OR2_X1 mult_66_U250 (.A1(mult_66_n85),
	.A2(mult_66_n90),
	.ZN(mult_66_n265));
   AOI21_X1 mult_66_U249 (.A(mult_66_n256),
	.B1(mult_66_n273),
	.B2(mult_66_n37),
	.ZN(mult_66_n32));
   NOR2_X1 mult_66_U246 (.A1(mult_66_n79),
	.A2(mult_66_n84),
	.ZN(mult_66_n26));
   NAND3_X1 mult_66_U245 (.A1(mult_66_n260),
	.A2(mult_66_n261),
	.A3(mult_66_n262),
	.ZN(mult_66_n84));
   NAND2_X1 mult_66_U244 (.A1(mult_66_n140),
	.A2(mult_66_n92),
	.ZN(mult_66_n262));
   NAND2_X1 mult_66_U243 (.A1(mult_66_n87),
	.A2(mult_66_n92),
	.ZN(mult_66_n261));
   NAND2_X1 mult_66_U242 (.A1(mult_66_n87),
	.A2(mult_66_n140),
	.ZN(mult_66_n260));
   OR2_X1 mult_66_U239 (.A1(mult_66_n118),
	.A2(mult_66_n88),
	.ZN(mult_66_n82));
   XNOR2_X1 mult_66_U238 (.A(mult_66_n86),
	.B(mult_66_n132),
	.ZN(mult_66_n254));
   XNOR2_X1 mult_66_U237 (.A(mult_66_n254),
	.B(mult_66_n81),
	.ZN(mult_66_n79));
   XNOR2_X1 mult_66_U235 (.A(u[7]),
	.B(b0[6]),
	.ZN(mult_66_n253));
   XNOR2_X1 mult_66_U229 (.A(mult_66_n140),
	.B(mult_66_n92),
	.ZN(mult_66_n247));
   XNOR2_X1 mult_66_U228 (.A(mult_66_n87),
	.B(mult_66_n247),
	.ZN(mult_66_n85));
   XNOR2_X1 mult_66_U227 (.A(u[1]),
	.B(b0[10]),
	.ZN(mult_66_n246));
   AND2_X1 mult_66_U226 (.A1(mult_66_n91),
	.A2(mult_66_n94),
	.ZN(mult_66_n256));
   INV_X1 mult_66_U225 (.A(mult_66_n256),
	.ZN(mult_66_n36));
   OAI21_X1 mult_66_U224 (.A(mult_66_n39),
	.B1(mult_66_n38),
	.B2(mult_66_n40),
	.ZN(mult_66_n37));
   XNOR2_X1 mult_66_U222 (.A(u[3]),
	.B(b0[10]),
	.ZN(mult_66_n245));
   XNOR2_X1 mult_66_U220 (.A(u[4]),
	.B(b0[10]),
	.ZN(mult_66_n243));
   AND2_X1 mult_66_U216 (.A1(mult_66_n265),
	.A2(mult_66_n31),
	.ZN(mult_66_n239));
   XNOR2_X1 mult_66_U215 (.A(mult_66_n239),
	.B(mult_66_n32),
	.ZN(mulb0[7]));
   AND2_X1 mult_66_U214 (.A1(mult_66_n59),
	.A2(mult_66_n27),
	.ZN(mult_66_n238));
   XNOR2_X1 mult_66_U213 (.A(mult_66_n28),
	.B(mult_66_n238),
	.ZN(mulb0[8]));
   INV_X1 mult_66_U212 (.A(mult_66_n19),
	.ZN(mult_66_n57));
   XNOR2_X1 mult_66_U211 (.A(b0[7]),
	.B(b0[6]),
	.ZN(mult_66_n200));
   NOR2_X1 mult_66_U210 (.A1(mult_66_n65),
	.A2(mult_66_n68),
	.ZN(mult_66_n16));
   XNOR2_X1 mult_66_U209 (.A(b0[9]),
	.B(b0[8]),
	.ZN(mult_66_n199));
   OAI22_X1 mult_66_U208 (.A1(mult_66_n177),
	.A2(mult_66_n217),
	.B1(mult_66_n178),
	.B2(mult_66_n197),
	.ZN(mult_66_n144));
   XNOR2_X1 mult_66_U207 (.A(b0[11]),
	.B(b0[10]),
	.ZN(mult_66_n198));
   NOR2_X1 mult_66_U206 (.A1(mult_66_n69),
	.A2(mult_66_n72),
	.ZN(mult_66_n19));
   XNOR2_X1 mult_66_U205 (.A(u[5]),
	.B(b0[10]),
	.ZN(mult_66_n237));
   OR2_X1 mult_66_U204 (.A1(mult_66_n91),
	.A2(mult_66_n94),
	.ZN(mult_66_n273));
   HA_X1 mult_66_U90 (.A(mult_66_n137),
	.B(mult_66_n114),
	.CO(mult_66_n100),
	.S(mult_66_n101));
   FA_X1 mult_66_U89 (.A(mult_66_n100),
	.B(mult_66_n129),
	.CI(mult_66_n136),
	.CO(mult_66_n98),
	.S(mult_66_n99));
   HA_X1 mult_66_U88 (.A(mult_66_n128),
	.B(mult_66_n113),
	.CO(mult_66_n96),
	.S(mult_66_n97));
   FA_X1 mult_66_U87 (.A(mult_66_n142),
	.B(mult_66_n97),
	.CI(mult_66_n135),
	.CO(mult_66_n94),
	.S(mult_66_n95));
   FA_X1 mult_66_U86 (.A(mult_66_n127),
	.B(mult_66_n120),
	.CI(mult_66_n96),
	.CO(mult_66_n92),
	.S(mult_66_n93));
   FA_X1 mult_66_U85 (.A(mult_66_n141),
	.B(mult_66_n134),
	.CI(mult_66_n93),
	.CO(mult_66_n90),
	.S(mult_66_n91));
   HA_X1 mult_66_U84 (.A(mult_66_n119),
	.B(mult_66_n112),
	.CO(mult_66_n88),
	.S(mult_66_n89));
   FA_X1 mult_66_U83 (.A(mult_66_n126),
	.B(mult_66_n89),
	.CI(mult_66_n133),
	.CO(mult_66_n86),
	.S(mult_66_n87));
   FA_X1 mult_66_U79 (.A(mult_66_n83),
	.B(mult_66_n125),
	.CI(mult_66_n139),
	.CO(mult_66_n80),
	.S(mult_66_n81));
   FA_X1 mult_66_U76 (.A(mult_66_n77),
	.B(mult_66_n82),
	.CI(mult_66_n124),
	.CO(mult_66_n74),
	.S(mult_66_n75));
   FA_X1 mult_66_U75 (.A(mult_66_n80),
	.B(mult_66_n131),
	.CI(mult_66_n75),
	.CO(mult_66_n72),
	.S(mult_66_n73));
   FA_X1 mult_66_U74 (.A(mult_66_n117),
	.B(mult_66_n76),
	.CI(mult_66_n130),
	.CO(mult_66_n70),
	.S(mult_66_n71));
   FA_X1 mult_66_U73 (.A(mult_66_n74),
	.B(mult_66_n123),
	.CI(mult_66_n71),
	.CO(mult_66_n68),
	.S(mult_66_n69));
   FA_X1 mult_66_U71 (.A(mult_66_n67),
	.B(mult_66_n122),
	.CI(mult_66_n70),
	.CO(mult_66_n64),
	.S(mult_66_n65));
   XOR2_X1 mult_66_U69 (.A(mult_66_n66),
	.B(mult_66_n62),
	.Z(mult_66_n63));
endmodule

