/*
###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID localhost.localdomain)
#  Generated on:      Tue Nov  9 00:00:56 2021
#  Design:            IIR_filter
#  Command:           saveNetlist IIR_filter.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : O-2018.06-SP4
// Date      : Tue Oct 26 14:11:05 2021
/////////////////////////////////////////////////////////////
module IIR_filter (
	CLK, 
	RST_n, 
	DIN, 
	VIN, 
	b0, 
	b1, 
	a1, 
	DOUT, 
	VOUT);
   input CLK;
   input RST_n;
   input [11:0] DIN;
   input VIN;
   input [11:0] b0;
   input [11:0] b1;
   input [11:0] a1;
   output [11:0] DOUT;
   output VOUT;

   // Internal wires
   wire FE_OFN0_q1;
   wire FE_DBTN6_u_del_vec_0;
   wire FE_DBTN5_u_del_vec_1;
   wire FE_DBTN4_u_del_vec_2;
   wire FE_DBTN3_u_del_vec_3;
   wire FE_DBTN2_u_del_vec_4;
   wire FE_DBTN1_u_del_vec_5;
   wire FE_DBTN0_u_del_vec_6;
   wire q1;
   wire regX0_n21;
   wire regX0_n20;
   wire regX0_n19;
   wire regX0_n18;
   wire regX0_n17;
   wire regX0_n16;
   wire regX0_n15;
   wire regX0_n14;
   wire regX0_n13;
   wire regX0_n12;
   wire regX0_n11;
   wire regX0_n10;
   wire regX0_n9;
   wire regX0_n8;
   wire regX0_n7;
   wire regX0_n6;
   wire regX0_n5;
   wire regX0_n4;
   wire regX0_n3;
   wire regX0_n2;
   wire regX0_n1;
   wire regU_n24;
   wire regU_n23;
   wire regU_n22;
   wire regU_n21;
   wire regU_n20;
   wire regU_n19;
   wire regU_n18;
   wire regU_n17;
   wire regU_n16;
   wire regU_n15;
   wire regU_n14;
   wire regU_n13;
   wire regU_n12;
   wire regU_n11;
   wire regU_n10;
   wire regU_n9;
   wire regU_n8;
   wire regU_n7;
   wire regU_n6;
   wire regU_n5;
   wire regU_n4;
   wire regU_n3;
   wire regU_n2;
   wire regU_n1;
   wire regY_n50;
   wire regY_n49;
   wire regY_n48;
   wire regY_n47;
   wire regY_n46;
   wire regY_n45;
   wire regY_n44;
   wire regY_n43;
   wire regY_n42;
   wire regY_n41;
   wire regY_n40;
   wire regY_n39;
   wire regY_n38;
   wire regY_n37;
   wire regY_n36;
   wire regY_n35;
   wire regY_n34;
   wire regY_n33;
   wire regY_n32;
   wire regY_n31;
   wire regY_n30;
   wire regY_n29;
   wire regY_n28;
   wire regY_n27;
   wire add_72_n2;
   wire add_56_n1;
   wire mult_64_n208;
   wire mult_64_n207;
   wire mult_64_n206;
   wire mult_64_n205;
   wire mult_64_n204;
   wire mult_64_n203;
   wire mult_64_n202;
   wire mult_64_n201;
   wire mult_64_n200;
   wire mult_64_n199;
   wire mult_64_n198;
   wire mult_64_n197;
   wire mult_64_n196;
   wire mult_64_n195;
   wire mult_64_n194;
   wire mult_64_n193;
   wire mult_64_n192;
   wire mult_64_n191;
   wire mult_64_n188;
   wire mult_64_n186;
   wire mult_64_n184;
   wire mult_64_n183;
   wire mult_64_n180;
   wire mult_64_n136;
   wire mult_64_n135;
   wire mult_64_n134;
   wire mult_64_n133;
   wire mult_64_n131;
   wire mult_64_n129;
   wire mult_64_n128;
   wire mult_64_n127;
   wire mult_64_n126;
   wire mult_64_n125;
   wire mult_64_n124;
   wire mult_64_n123;
   wire mult_64_n121;
   wire mult_64_n120;
   wire mult_64_n119;
   wire mult_64_n118;
   wire mult_64_n117;
   wire mult_64_n116;
   wire mult_64_n115;
   wire mult_64_n114;
   wire mult_64_n113;
   wire mult_64_n112;
   wire mult_64_n111;
   wire mult_64_n110;
   wire mult_64_n109;
   wire mult_64_n108;
   wire mult_64_n107;
   wire mult_64_n106;
   wire mult_64_n105;
   wire mult_64_n103;
   wire mult_64_n102;
   wire mult_64_n101;
   wire mult_64_n100;
   wire mult_64_n99;
   wire mult_64_n98;
   wire mult_64_n97;
   wire mult_64_n96;
   wire mult_64_n95;
   wire mult_64_n94;
   wire mult_64_n93;
   wire mult_64_n91;
   wire mult_64_n90;
   wire mult_64_n89;
   wire mult_64_n88;
   wire mult_64_n87;
   wire mult_64_n86;
   wire mult_64_n84;
   wire mult_64_n83;
   wire mult_64_n82;
   wire mult_64_n81;
   wire mult_64_n80;
   wire mult_64_n79;
   wire mult_64_n78;
   wire mult_64_n77;
   wire mult_64_n76;
   wire mult_64_n75;
   wire mult_64_n74;
   wire mult_64_n73;
   wire mult_64_n72;
   wire mult_64_n71;
   wire mult_64_n70;
   wire mult_64_n69;
   wire mult_64_n68;
   wire mult_64_n67;
   wire mult_64_n66;
   wire mult_64_n65;
   wire mult_64_n64;
   wire mult_64_n63;
   wire mult_64_n62;
   wire mult_64_n61;
   wire mult_64_n60;
   wire mult_64_n59;
   wire mult_64_n58;
   wire mult_64_n57;
   wire mult_64_n56;
   wire mult_64_n55;
   wire mult_64_n54;
   wire mult_64_n52;
   wire mult_64_n51;
   wire mult_64_n50;
   wire mult_64_n49;
   wire mult_64_n48;
   wire mult_64_n47;
   wire mult_64_n46;
   wire mult_64_n45;
   wire mult_64_n44;
   wire mult_64_n43;
   wire mult_64_n42;
   wire mult_64_n41;
   wire mult_64_n40;
   wire mult_64_n39;
   wire mult_64_n38;
   wire mult_64_n37;
   wire mult_64_n36;
   wire mult_64_n35;
   wire mult_64_n34;
   wire mult_64_n33;
   wire mult_64_n32;
   wire mult_64_n31;
   wire mult_64_n30;
   wire mult_64_n29;
   wire mult_64_n28;
   wire mult_64_n27;
   wire mult_64_n26;
   wire mult_64_n25;
   wire mult_64_n24;
   wire mult_64_n23;
   wire mult_64_n22;
   wire mult_64_n21;
   wire mult_64_n20;
   wire mult_64_n19;
   wire mult_64_n18;
   wire mult_64_n17;
   wire mult_64_n16;
   wire mult_64_n15;
   wire mult_64_n8;
   wire mult_64_n7;
   wire mult_64_n6;
   wire mult_64_n5;
   wire mult_64_n4;
   wire mult_64_n3;
   wire mult_64_n2;
   wire mult_68_n208;
   wire mult_68_n207;
   wire mult_68_n206;
   wire mult_68_n205;
   wire mult_68_n204;
   wire mult_68_n203;
   wire mult_68_n202;
   wire mult_68_n201;
   wire mult_68_n200;
   wire mult_68_n199;
   wire mult_68_n198;
   wire mult_68_n197;
   wire mult_68_n196;
   wire mult_68_n195;
   wire mult_68_n194;
   wire mult_68_n193;
   wire mult_68_n192;
   wire mult_68_n191;
   wire mult_68_n188;
   wire mult_68_n186;
   wire mult_68_n184;
   wire mult_68_n183;
   wire mult_68_n180;
   wire mult_68_n136;
   wire mult_68_n135;
   wire mult_68_n134;
   wire mult_68_n133;
   wire mult_68_n131;
   wire mult_68_n129;
   wire mult_68_n128;
   wire mult_68_n127;
   wire mult_68_n126;
   wire mult_68_n125;
   wire mult_68_n124;
   wire mult_68_n123;
   wire mult_68_n121;
   wire mult_68_n120;
   wire mult_68_n119;
   wire mult_68_n118;
   wire mult_68_n117;
   wire mult_68_n116;
   wire mult_68_n115;
   wire mult_68_n114;
   wire mult_68_n113;
   wire mult_68_n112;
   wire mult_68_n111;
   wire mult_68_n110;
   wire mult_68_n109;
   wire mult_68_n108;
   wire mult_68_n107;
   wire mult_68_n106;
   wire mult_68_n105;
   wire mult_68_n103;
   wire mult_68_n102;
   wire mult_68_n101;
   wire mult_68_n100;
   wire mult_68_n99;
   wire mult_68_n98;
   wire mult_68_n97;
   wire mult_68_n96;
   wire mult_68_n95;
   wire mult_68_n94;
   wire mult_68_n93;
   wire mult_68_n91;
   wire mult_68_n90;
   wire mult_68_n89;
   wire mult_68_n88;
   wire mult_68_n87;
   wire mult_68_n86;
   wire mult_68_n84;
   wire mult_68_n83;
   wire mult_68_n82;
   wire mult_68_n81;
   wire mult_68_n80;
   wire mult_68_n79;
   wire mult_68_n78;
   wire mult_68_n77;
   wire mult_68_n76;
   wire mult_68_n75;
   wire mult_68_n74;
   wire mult_68_n73;
   wire mult_68_n72;
   wire mult_68_n71;
   wire mult_68_n70;
   wire mult_68_n69;
   wire mult_68_n68;
   wire mult_68_n67;
   wire mult_68_n66;
   wire mult_68_n65;
   wire mult_68_n64;
   wire mult_68_n63;
   wire mult_68_n62;
   wire mult_68_n61;
   wire mult_68_n60;
   wire mult_68_n59;
   wire mult_68_n58;
   wire mult_68_n57;
   wire mult_68_n56;
   wire mult_68_n55;
   wire mult_68_n54;
   wire mult_68_n52;
   wire mult_68_n51;
   wire mult_68_n50;
   wire mult_68_n49;
   wire mult_68_n48;
   wire mult_68_n47;
   wire mult_68_n46;
   wire mult_68_n45;
   wire mult_68_n44;
   wire mult_68_n43;
   wire mult_68_n42;
   wire mult_68_n41;
   wire mult_68_n40;
   wire mult_68_n39;
   wire mult_68_n38;
   wire mult_68_n37;
   wire mult_68_n36;
   wire mult_68_n35;
   wire mult_68_n34;
   wire mult_68_n33;
   wire mult_68_n32;
   wire mult_68_n31;
   wire mult_68_n30;
   wire mult_68_n29;
   wire mult_68_n28;
   wire mult_68_n27;
   wire mult_68_n26;
   wire mult_68_n25;
   wire mult_68_n24;
   wire mult_68_n23;
   wire mult_68_n22;
   wire mult_68_n21;
   wire mult_68_n20;
   wire mult_68_n19;
   wire mult_68_n18;
   wire mult_68_n17;
   wire mult_68_n16;
   wire mult_68_n15;
   wire mult_68_n8;
   wire mult_68_n7;
   wire mult_68_n6;
   wire mult_68_n5;
   wire mult_68_n4;
   wire mult_68_n3;
   wire mult_68_n2;
   wire mult_66_n208;
   wire mult_66_n207;
   wire mult_66_n206;
   wire mult_66_n205;
   wire mult_66_n204;
   wire mult_66_n203;
   wire mult_66_n202;
   wire mult_66_n201;
   wire mult_66_n200;
   wire mult_66_n199;
   wire mult_66_n198;
   wire mult_66_n197;
   wire mult_66_n196;
   wire mult_66_n195;
   wire mult_66_n194;
   wire mult_66_n193;
   wire mult_66_n192;
   wire mult_66_n191;
   wire mult_66_n190;
   wire mult_66_n189;
   wire mult_66_n188;
   wire mult_66_n187;
   wire mult_66_n186;
   wire mult_66_n185;
   wire mult_66_n184;
   wire mult_66_n183;
   wire mult_66_n182;
   wire mult_66_n181;
   wire mult_66_n180;
   wire mult_66_n179;
   wire mult_66_n136;
   wire mult_66_n135;
   wire mult_66_n134;
   wire mult_66_n133;
   wire mult_66_n131;
   wire mult_66_n129;
   wire mult_66_n128;
   wire mult_66_n127;
   wire mult_66_n126;
   wire mult_66_n125;
   wire mult_66_n124;
   wire mult_66_n123;
   wire mult_66_n121;
   wire mult_66_n120;
   wire mult_66_n119;
   wire mult_66_n118;
   wire mult_66_n117;
   wire mult_66_n116;
   wire mult_66_n115;
   wire mult_66_n114;
   wire mult_66_n113;
   wire mult_66_n112;
   wire mult_66_n111;
   wire mult_66_n110;
   wire mult_66_n109;
   wire mult_66_n108;
   wire mult_66_n107;
   wire mult_66_n106;
   wire mult_66_n105;
   wire mult_66_n103;
   wire mult_66_n102;
   wire mult_66_n101;
   wire mult_66_n100;
   wire mult_66_n99;
   wire mult_66_n98;
   wire mult_66_n97;
   wire mult_66_n96;
   wire mult_66_n95;
   wire mult_66_n94;
   wire mult_66_n93;
   wire mult_66_n91;
   wire mult_66_n90;
   wire mult_66_n89;
   wire mult_66_n88;
   wire mult_66_n87;
   wire mult_66_n86;
   wire mult_66_n84;
   wire mult_66_n83;
   wire mult_66_n82;
   wire mult_66_n81;
   wire mult_66_n80;
   wire mult_66_n79;
   wire mult_66_n78;
   wire mult_66_n77;
   wire mult_66_n76;
   wire mult_66_n75;
   wire mult_66_n74;
   wire mult_66_n73;
   wire mult_66_n72;
   wire mult_66_n71;
   wire mult_66_n70;
   wire mult_66_n69;
   wire mult_66_n68;
   wire mult_66_n67;
   wire mult_66_n66;
   wire mult_66_n65;
   wire mult_66_n64;
   wire mult_66_n63;
   wire mult_66_n62;
   wire mult_66_n61;
   wire mult_66_n60;
   wire mult_66_n59;
   wire mult_66_n58;
   wire mult_66_n57;
   wire mult_66_n56;
   wire mult_66_n55;
   wire mult_66_n54;
   wire mult_66_n52;
   wire mult_66_n51;
   wire mult_66_n50;
   wire mult_66_n49;
   wire mult_66_n48;
   wire mult_66_n47;
   wire mult_66_n46;
   wire mult_66_n45;
   wire mult_66_n44;
   wire mult_66_n43;
   wire mult_66_n42;
   wire mult_66_n41;
   wire mult_66_n40;
   wire mult_66_n39;
   wire mult_66_n38;
   wire mult_66_n37;
   wire mult_66_n36;
   wire mult_66_n35;
   wire mult_66_n34;
   wire mult_66_n33;
   wire mult_66_n32;
   wire mult_66_n31;
   wire mult_66_n30;
   wire mult_66_n29;
   wire mult_66_n28;
   wire mult_66_n27;
   wire mult_66_n26;
   wire mult_66_n25;
   wire mult_66_n24;
   wire mult_66_n23;
   wire mult_66_n22;
   wire mult_66_n21;
   wire mult_66_n20;
   wire mult_66_n19;
   wire mult_66_n18;
   wire mult_66_n17;
   wire mult_66_n16;
   wire mult_66_n15;
   wire mult_66_n8;
   wire mult_66_n7;
   wire mult_66_n6;
   wire mult_66_n5;
   wire mult_66_n4;
   wire mult_66_n3;
   wire mult_66_n2;
   wire [6:0] din_del;
   wire [7:0] u;
   wire [7:0] u_del_vec;
   wire [12:6] mula1;
   wire [12:6] mulb0;
   wire [12:6] mulb1;
   wire [7:0] y;
   wire [7:2] add_72_carry;
   wire [7:2] add_56_carry;

   assign DOUT[0] = 1'b0 ;
   assign DOUT[1] = 1'b0 ;
   assign DOUT[2] = 1'b0 ;
   assign DOUT[3] = 1'b0 ;

   CLKBUF_X2 FE_OFC0_q1 (.A(q1),
	.Z(FE_OFN0_q1));
   INV_X1 FE_DBTC6_u_del_vec_0 (.A(u_del_vec[0]),
	.ZN(FE_DBTN6_u_del_vec_0));
   INV_X1 FE_DBTC5_u_del_vec_1 (.A(u_del_vec[1]),
	.ZN(FE_DBTN5_u_del_vec_1));
   INV_X1 FE_DBTC4_u_del_vec_2 (.A(u_del_vec[2]),
	.ZN(FE_DBTN4_u_del_vec_2));
   INV_X1 FE_DBTC3_u_del_vec_3 (.A(u_del_vec[3]),
	.ZN(FE_DBTN3_u_del_vec_3));
   INV_X1 FE_DBTC2_u_del_vec_4 (.A(u_del_vec[4]),
	.ZN(FE_DBTN2_u_del_vec_4));
   INV_X1 FE_DBTC1_u_del_vec_5 (.A(u_del_vec[5]),
	.ZN(FE_DBTN1_u_del_vec_5));
   INV_X1 FE_DBTC0_u_del_vec_6 (.A(u_del_vec[6]),
	.ZN(FE_DBTN0_u_del_vec_6));
   NAND2_X1 regX0_U15 (.A1(DIN[11]),
	.A2(VIN),
	.ZN(regX0_n7));
   OAI21_X1 regX0_U14 (.A(regX0_n7),
	.B1(regX0_n14),
	.B2(VIN),
	.ZN(regX0_n21));
   NAND2_X1 regX0_U13 (.A1(DIN[10]),
	.A2(VIN),
	.ZN(regX0_n6));
   OAI21_X1 regX0_U12 (.A(regX0_n6),
	.B1(regX0_n13),
	.B2(VIN),
	.ZN(regX0_n20));
   NAND2_X1 regX0_U11 (.A1(DIN[9]),
	.A2(VIN),
	.ZN(regX0_n5));
   OAI21_X1 regX0_U10 (.A(regX0_n5),
	.B1(regX0_n12),
	.B2(VIN),
	.ZN(regX0_n19));
   NAND2_X1 regX0_U9 (.A1(DIN[8]),
	.A2(VIN),
	.ZN(regX0_n4));
   OAI21_X1 regX0_U8 (.A(regX0_n4),
	.B1(regX0_n11),
	.B2(VIN),
	.ZN(regX0_n18));
   NAND2_X1 regX0_U7 (.A1(DIN[7]),
	.A2(VIN),
	.ZN(regX0_n3));
   OAI21_X1 regX0_U6 (.A(regX0_n3),
	.B1(regX0_n10),
	.B2(VIN),
	.ZN(regX0_n17));
   NAND2_X1 regX0_U5 (.A1(DIN[6]),
	.A2(VIN),
	.ZN(regX0_n2));
   OAI21_X1 regX0_U4 (.A(regX0_n2),
	.B1(regX0_n9),
	.B2(VIN),
	.ZN(regX0_n16));
   NAND2_X1 regX0_U3 (.A1(VIN),
	.A2(DIN[5]),
	.ZN(regX0_n1));
   OAI21_X1 regX0_U2 (.A(regX0_n1),
	.B1(regX0_n8),
	.B2(VIN),
	.ZN(regX0_n15));
   DFFR_X1 regX0_Q_reg_0_ (.D(regX0_n15),
	.RN(RST_n),
	.CK(CLK),
	.Q(din_del[0]),
	.QN(regX0_n8));
   DFFR_X1 regX0_Q_reg_1_ (.D(regX0_n16),
	.RN(RST_n),
	.CK(CLK),
	.Q(din_del[1]),
	.QN(regX0_n9));
   DFFR_X1 regX0_Q_reg_2_ (.D(regX0_n17),
	.RN(RST_n),
	.CK(CLK),
	.Q(din_del[2]),
	.QN(regX0_n10));
   DFFR_X1 regX0_Q_reg_3_ (.D(regX0_n18),
	.RN(RST_n),
	.CK(CLK),
	.Q(din_del[3]),
	.QN(regX0_n11));
   DFFR_X1 regX0_Q_reg_4_ (.D(regX0_n19),
	.RN(RST_n),
	.CK(CLK),
	.Q(din_del[4]),
	.QN(regX0_n12));
   DFFR_X1 regX0_Q_reg_5_ (.D(regX0_n20),
	.RN(RST_n),
	.CK(CLK),
	.Q(din_del[5]),
	.QN(regX0_n13));
   DFFR_X1 regX0_Q_reg_6_ (.D(regX0_n21),
	.RN(RST_n),
	.CK(CLK),
	.Q(din_del[6]),
	.QN(regX0_n14));
   NAND2_X1 regU_U17 (.A1(u[3]),
	.A2(FE_OFN0_q1),
	.ZN(regU_n4));
   OAI21_X1 regU_U16 (.A(regU_n4),
	.B1(regU_n12),
	.B2(FE_OFN0_q1),
	.ZN(regU_n20));
   NAND2_X1 regU_U15 (.A1(u[2]),
	.A2(FE_OFN0_q1),
	.ZN(regU_n3));
   OAI21_X1 regU_U14 (.A(regU_n3),
	.B1(regU_n11),
	.B2(FE_OFN0_q1),
	.ZN(regU_n19));
   NAND2_X1 regU_U13 (.A1(u[1]),
	.A2(FE_OFN0_q1),
	.ZN(regU_n2));
   OAI21_X1 regU_U12 (.A(regU_n2),
	.B1(regU_n10),
	.B2(FE_OFN0_q1),
	.ZN(regU_n18));
   NAND2_X1 regU_U11 (.A1(FE_OFN0_q1),
	.A2(u[0]),
	.ZN(regU_n1));
   OAI21_X1 regU_U10 (.A(regU_n1),
	.B1(regU_n9),
	.B2(FE_OFN0_q1),
	.ZN(regU_n17));
   NAND2_X1 regU_U9 (.A1(u[7]),
	.A2(FE_OFN0_q1),
	.ZN(regU_n8));
   OAI21_X1 regU_U8 (.A(regU_n8),
	.B1(regU_n16),
	.B2(FE_OFN0_q1),
	.ZN(regU_n24));
   NAND2_X1 regU_U7 (.A1(u[6]),
	.A2(FE_OFN0_q1),
	.ZN(regU_n7));
   OAI21_X1 regU_U6 (.A(regU_n7),
	.B1(regU_n15),
	.B2(FE_OFN0_q1),
	.ZN(regU_n23));
   NAND2_X1 regU_U5 (.A1(u[5]),
	.A2(FE_OFN0_q1),
	.ZN(regU_n6));
   OAI21_X1 regU_U4 (.A(regU_n6),
	.B1(regU_n14),
	.B2(FE_OFN0_q1),
	.ZN(regU_n22));
   NAND2_X1 regU_U3 (.A1(u[4]),
	.A2(FE_OFN0_q1),
	.ZN(regU_n5));
   OAI21_X1 regU_U2 (.A(regU_n5),
	.B1(regU_n13),
	.B2(FE_OFN0_q1),
	.ZN(regU_n21));
   DFFR_X1 regU_Q_reg_0_ (.D(regU_n17),
	.RN(RST_n),
	.CK(CLK),
	.Q(u_del_vec[0]),
	.QN(regU_n9));
   DFFR_X1 regU_Q_reg_1_ (.D(regU_n18),
	.RN(RST_n),
	.CK(CLK),
	.Q(u_del_vec[1]),
	.QN(regU_n10));
   DFFR_X1 regU_Q_reg_2_ (.D(regU_n19),
	.RN(RST_n),
	.CK(CLK),
	.Q(u_del_vec[2]),
	.QN(regU_n11));
   DFFR_X1 regU_Q_reg_3_ (.D(regU_n20),
	.RN(RST_n),
	.CK(CLK),
	.Q(u_del_vec[3]),
	.QN(regU_n12));
   DFFR_X1 regU_Q_reg_4_ (.D(regU_n21),
	.RN(RST_n),
	.CK(CLK),
	.Q(u_del_vec[4]),
	.QN(regU_n13));
   DFFR_X1 regU_Q_reg_5_ (.D(regU_n22),
	.RN(RST_n),
	.CK(CLK),
	.Q(u_del_vec[5]),
	.QN(regU_n14));
   DFFR_X1 regU_Q_reg_6_ (.D(regU_n23),
	.RN(RST_n),
	.CK(CLK),
	.Q(u_del_vec[6]),
	.QN(regU_n15));
   DFFR_X1 regU_Q_reg_7_ (.D(regU_n24),
	.RN(RST_n),
	.CK(CLK),
	.Q(u_del_vec[7]),
	.QN(regU_n16));
   NAND2_X1 regY_U17 (.A1(FE_OFN0_q1),
	.A2(y[0]),
	.ZN(regY_n50));
   OAI21_X1 regY_U16 (.A(regY_n50),
	.B1(regY_n42),
	.B2(FE_OFN0_q1),
	.ZN(regY_n34));
   NAND2_X1 regY_U15 (.A1(y[7]),
	.A2(FE_OFN0_q1),
	.ZN(regY_n43));
   OAI21_X1 regY_U14 (.A(regY_n43),
	.B1(regY_n35),
	.B2(FE_OFN0_q1),
	.ZN(regY_n27));
   NAND2_X1 regY_U13 (.A1(y[6]),
	.A2(FE_OFN0_q1),
	.ZN(regY_n44));
   OAI21_X1 regY_U12 (.A(regY_n44),
	.B1(regY_n36),
	.B2(FE_OFN0_q1),
	.ZN(regY_n28));
   NAND2_X1 regY_U11 (.A1(y[5]),
	.A2(FE_OFN0_q1),
	.ZN(regY_n45));
   OAI21_X1 regY_U10 (.A(regY_n45),
	.B1(regY_n37),
	.B2(FE_OFN0_q1),
	.ZN(regY_n29));
   NAND2_X1 regY_U9 (.A1(y[4]),
	.A2(FE_OFN0_q1),
	.ZN(regY_n46));
   OAI21_X1 regY_U8 (.A(regY_n46),
	.B1(regY_n38),
	.B2(FE_OFN0_q1),
	.ZN(regY_n30));
   NAND2_X1 regY_U7 (.A1(y[3]),
	.A2(FE_OFN0_q1),
	.ZN(regY_n47));
   OAI21_X1 regY_U6 (.A(regY_n47),
	.B1(regY_n39),
	.B2(FE_OFN0_q1),
	.ZN(regY_n31));
   NAND2_X1 regY_U5 (.A1(y[2]),
	.A2(FE_OFN0_q1),
	.ZN(regY_n48));
   OAI21_X1 regY_U4 (.A(regY_n48),
	.B1(regY_n40),
	.B2(FE_OFN0_q1),
	.ZN(regY_n32));
   NAND2_X1 regY_U3 (.A1(y[1]),
	.A2(FE_OFN0_q1),
	.ZN(regY_n49));
   OAI21_X1 regY_U2 (.A(regY_n49),
	.B1(regY_n41),
	.B2(FE_OFN0_q1),
	.ZN(regY_n33));
   DFFR_X1 regY_Q_reg_0_ (.D(regY_n34),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[4]),
	.QN(regY_n42));
   DFFR_X1 regY_Q_reg_1_ (.D(regY_n33),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[5]),
	.QN(regY_n41));
   DFFR_X1 regY_Q_reg_2_ (.D(regY_n32),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[6]),
	.QN(regY_n40));
   DFFR_X1 regY_Q_reg_3_ (.D(regY_n31),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[7]),
	.QN(regY_n39));
   DFFR_X1 regY_Q_reg_4_ (.D(regY_n30),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[8]),
	.QN(regY_n38));
   DFFR_X1 regY_Q_reg_5_ (.D(regY_n29),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[9]),
	.QN(regY_n37));
   DFFR_X1 regY_Q_reg_6_ (.D(regY_n28),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[10]),
	.QN(regY_n36));
   DFFR_X1 regY_Q_reg_7_ (.D(regY_n27),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[11]),
	.QN(regY_n35));
   DFFR_X1 ff1_Q_reg (.D(VIN),
	.RN(RST_n),
	.CK(CLK),
	.Q(q1));
   DFFR_X1 ff2_Q_reg (.D(FE_OFN0_q1),
	.RN(RST_n),
	.CK(CLK),
	.Q(VOUT));
   AND2_X1 add_72_U2 (.A1(mulb1[6]),
	.A2(mulb0[6]),
	.ZN(add_72_n2));
   XOR2_X1 add_72_U1 (.A(mulb1[6]),
	.B(mulb0[6]),
	.Z(y[0]));
   FA_X1 add_72_U1_1 (.A(mulb0[7]),
	.B(mulb1[7]),
	.CI(add_72_n2),
	.CO(add_72_carry[2]),
	.S(y[1]));
   FA_X1 add_72_U1_2 (.A(mulb0[8]),
	.B(mulb1[8]),
	.CI(add_72_carry[2]),
	.CO(add_72_carry[3]),
	.S(y[2]));
   FA_X1 add_72_U1_3 (.A(mulb0[9]),
	.B(mulb1[9]),
	.CI(add_72_carry[3]),
	.CO(add_72_carry[4]),
	.S(y[3]));
   FA_X1 add_72_U1_4 (.A(mulb0[10]),
	.B(mulb1[10]),
	.CI(add_72_carry[4]),
	.CO(add_72_carry[5]),
	.S(y[4]));
   FA_X1 add_72_U1_5 (.A(mulb0[11]),
	.B(mulb1[11]),
	.CI(add_72_carry[5]),
	.CO(add_72_carry[6]),
	.S(y[5]));
   FA_X1 add_72_U1_6 (.A(mulb0[12]),
	.B(mulb1[12]),
	.CI(add_72_carry[6]),
	.CO(add_72_carry[7]),
	.S(y[6]));
   FA_X1 add_72_U1_7 (.A(mulb0[12]),
	.B(mulb1[12]),
	.CI(add_72_carry[7]),
	.S(y[7]));
   XOR2_X1 add_56_U2 (.A(mula1[6]),
	.B(din_del[0]),
	.Z(u[0]));
   AND2_X1 add_56_U1 (.A1(mula1[6]),
	.A2(din_del[0]),
	.ZN(add_56_n1));
   FA_X1 add_56_U1_1 (.A(din_del[1]),
	.B(mula1[7]),
	.CI(add_56_n1),
	.CO(add_56_carry[2]),
	.S(u[1]));
   FA_X1 add_56_U1_2 (.A(din_del[2]),
	.B(mula1[8]),
	.CI(add_56_carry[2]),
	.CO(add_56_carry[3]),
	.S(u[2]));
   FA_X1 add_56_U1_3 (.A(din_del[3]),
	.B(mula1[9]),
	.CI(add_56_carry[3]),
	.CO(add_56_carry[4]),
	.S(u[3]));
   FA_X1 add_56_U1_4 (.A(din_del[4]),
	.B(mula1[10]),
	.CI(add_56_carry[4]),
	.CO(add_56_carry[5]),
	.S(u[4]));
   FA_X1 add_56_U1_5 (.A(din_del[5]),
	.B(mula1[11]),
	.CI(add_56_carry[5]),
	.CO(add_56_carry[6]),
	.S(u[5]));
   FA_X1 add_56_U1_6 (.A(din_del[6]),
	.B(mula1[12]),
	.CI(add_56_carry[6]),
	.CO(add_56_carry[7]),
	.S(u[6]));
   FA_X1 add_56_U1_7 (.A(din_del[6]),
	.B(mula1[12]),
	.CI(add_56_carry[7]),
	.S(u[7]));
   NOR2_X1 mult_64_U203 (.A1(FE_DBTN0_u_del_vec_6),
	.A2(mult_64_n192),
	.ZN(mult_64_n100));
   NOR2_X1 mult_64_U202 (.A1(mult_64_n192),
	.A2(FE_DBTN1_u_del_vec_5),
	.ZN(mult_64_n101));
   NOR2_X1 mult_64_U201 (.A1(mult_64_n192),
	.A2(FE_DBTN2_u_del_vec_4),
	.ZN(mult_64_n102));
   NOR2_X1 mult_64_U200 (.A1(mult_64_n192),
	.A2(FE_DBTN3_u_del_vec_3),
	.ZN(mult_64_n103));
   NOR2_X1 mult_64_U199 (.A1(mult_64_n192),
	.A2(FE_DBTN5_u_del_vec_1),
	.ZN(mult_64_n105));
   NOR2_X1 mult_64_U198 (.A1(mult_64_n192),
	.A2(FE_DBTN6_u_del_vec_0),
	.ZN(mult_64_n106));
   NAND2_X1 mult_64_U197 (.A1(a1[8]),
	.A2(u_del_vec[7]),
	.ZN(mult_64_n107));
   NOR2_X1 mult_64_U196 (.A1(FE_DBTN0_u_del_vec_6),
	.A2(mult_64_n193),
	.ZN(mult_64_n108));
   NOR2_X1 mult_64_U195 (.A1(FE_DBTN1_u_del_vec_5),
	.A2(mult_64_n193),
	.ZN(mult_64_n109));
   NOR2_X1 mult_64_U194 (.A1(FE_DBTN2_u_del_vec_4),
	.A2(mult_64_n193),
	.ZN(mult_64_n110));
   NOR2_X1 mult_64_U193 (.A1(FE_DBTN3_u_del_vec_3),
	.A2(mult_64_n193),
	.ZN(mult_64_n111));
   NOR2_X1 mult_64_U192 (.A1(FE_DBTN4_u_del_vec_2),
	.A2(mult_64_n193),
	.ZN(mult_64_n112));
   NOR2_X1 mult_64_U191 (.A1(FE_DBTN5_u_del_vec_1),
	.A2(mult_64_n193),
	.ZN(mult_64_n113));
   NOR2_X1 mult_64_U190 (.A1(FE_DBTN6_u_del_vec_0),
	.A2(mult_64_n193),
	.ZN(mult_64_n114));
   NAND2_X1 mult_64_U189 (.A1(a1[7]),
	.A2(u_del_vec[7]),
	.ZN(mult_64_n115));
   NOR2_X1 mult_64_U188 (.A1(FE_DBTN0_u_del_vec_6),
	.A2(mult_64_n194),
	.ZN(mult_64_n116));
   NOR2_X1 mult_64_U187 (.A1(FE_DBTN1_u_del_vec_5),
	.A2(mult_64_n194),
	.ZN(mult_64_n117));
   NOR2_X1 mult_64_U186 (.A1(FE_DBTN2_u_del_vec_4),
	.A2(mult_64_n194),
	.ZN(mult_64_n118));
   NOR2_X1 mult_64_U185 (.A1(FE_DBTN3_u_del_vec_3),
	.A2(mult_64_n194),
	.ZN(mult_64_n119));
   NOR2_X1 mult_64_U184 (.A1(FE_DBTN4_u_del_vec_2),
	.A2(mult_64_n194),
	.ZN(mult_64_n120));
   NOR2_X1 mult_64_U183 (.A1(FE_DBTN5_u_del_vec_1),
	.A2(mult_64_n194),
	.ZN(mult_64_n121));
   NAND2_X1 mult_64_U182 (.A1(a1[6]),
	.A2(u_del_vec[7]),
	.ZN(mult_64_n123));
   NOR2_X1 mult_64_U181 (.A1(FE_DBTN0_u_del_vec_6),
	.A2(mult_64_n195),
	.ZN(mult_64_n124));
   NOR2_X1 mult_64_U180 (.A1(FE_DBTN1_u_del_vec_5),
	.A2(mult_64_n195),
	.ZN(mult_64_n125));
   NOR2_X1 mult_64_U179 (.A1(FE_DBTN2_u_del_vec_4),
	.A2(mult_64_n195),
	.ZN(mult_64_n126));
   NOR2_X1 mult_64_U178 (.A1(FE_DBTN3_u_del_vec_3),
	.A2(mult_64_n195),
	.ZN(mult_64_n127));
   NOR2_X1 mult_64_U177 (.A1(FE_DBTN4_u_del_vec_2),
	.A2(mult_64_n195),
	.ZN(mult_64_n128));
   NOR2_X1 mult_64_U176 (.A1(FE_DBTN5_u_del_vec_1),
	.A2(mult_64_n195),
	.ZN(mult_64_n129));
   NAND2_X1 mult_64_U175 (.A1(a1[5]),
	.A2(u_del_vec[7]),
	.ZN(mult_64_n131));
   NOR2_X1 mult_64_U174 (.A1(FE_DBTN1_u_del_vec_5),
	.A2(mult_64_n196),
	.ZN(mult_64_n133));
   NOR2_X1 mult_64_U173 (.A1(FE_DBTN2_u_del_vec_4),
	.A2(mult_64_n196),
	.ZN(mult_64_n134));
   NOR2_X1 mult_64_U172 (.A1(FE_DBTN3_u_del_vec_3),
	.A2(mult_64_n196),
	.ZN(mult_64_n135));
   NOR2_X1 mult_64_U171 (.A1(FE_DBTN4_u_del_vec_2),
	.A2(mult_64_n196),
	.ZN(mult_64_n136));
   NAND2_X1 mult_64_U170 (.A1(u_del_vec[2]),
	.A2(a1[10]),
	.ZN(mult_64_n54));
   NAND2_X1 mult_64_U169 (.A1(a1[5]),
	.A2(u_del_vec[6]),
	.ZN(mult_64_n208));
   NAND2_X1 mult_64_U168 (.A1(u_del_vec[2]),
	.A2(a1[9]),
	.ZN(mult_64_n207));
   NAND2_X1 mult_64_U167 (.A1(mult_64_n208),
	.A2(mult_64_n207),
	.ZN(mult_64_n63));
   XNOR2_X1 mult_64_U166 (.A(mult_64_n207),
	.B(mult_64_n208),
	.ZN(mult_64_n64));
   NOR4_X1 mult_64_U165 (.A1(mult_64_n195),
	.A2(mult_64_n196),
	.A3(FE_DBTN5_u_del_vec_1),
	.A4(FE_DBTN6_u_del_vec_0),
	.ZN(mult_64_n205));
   NOR2_X1 mult_64_U164 (.A1(mult_64_n194),
	.A2(FE_DBTN6_u_del_vec_0),
	.ZN(mult_64_n206));
   AOI222_X1 mult_64_U163 (.A1(mult_64_n84),
	.A2(mult_64_n205),
	.B1(mult_64_n206),
	.B2(mult_64_n84),
	.C1(mult_64_n206),
	.C2(mult_64_n205),
	.ZN(mult_64_n204));
   OAI222_X1 mult_64_U162 (.A1(mult_64_n204),
	.A2(mult_64_n184),
	.B1(mult_64_n184),
	.B2(mult_64_n188),
	.C1(mult_64_n204),
	.C2(mult_64_n188),
	.ZN(mult_64_n203));
   AOI222_X1 mult_64_U161 (.A1(mult_64_n203),
	.A2(mult_64_n74),
	.B1(mult_64_n203),
	.B2(mult_64_n76),
	.C1(mult_64_n76),
	.C2(mult_64_n74),
	.ZN(mult_64_n202));
   OAI222_X1 mult_64_U160 (.A1(mult_64_n202),
	.A2(mult_64_n180),
	.B1(mult_64_n202),
	.B2(mult_64_n183),
	.C1(mult_64_n183),
	.C2(mult_64_n180),
	.ZN(mult_64_n8));
   NAND2_X1 mult_64_U159 (.A1(u_del_vec[5]),
	.A2(a1[11]),
	.ZN(mult_64_n86));
   NAND2_X1 mult_64_U158 (.A1(u_del_vec[4]),
	.A2(a1[11]),
	.ZN(mult_64_n87));
   NAND2_X1 mult_64_U157 (.A1(u_del_vec[3]),
	.A2(a1[11]),
	.ZN(mult_64_n88));
   NAND2_X1 mult_64_U156 (.A1(u_del_vec[2]),
	.A2(a1[11]),
	.ZN(mult_64_n89));
   NAND2_X1 mult_64_U155 (.A1(u_del_vec[1]),
	.A2(a1[11]),
	.ZN(mult_64_n90));
   NAND2_X1 mult_64_U154 (.A1(u_del_vec[0]),
	.A2(a1[11]),
	.ZN(mult_64_n91));
   NOR2_X1 mult_64_U153 (.A1(mult_64_n191),
	.A2(FE_DBTN0_u_del_vec_6),
	.ZN(mult_64_n93));
   NOR2_X1 mult_64_U152 (.A1(mult_64_n191),
	.A2(FE_DBTN1_u_del_vec_5),
	.ZN(mult_64_n94));
   NOR2_X1 mult_64_U151 (.A1(mult_64_n191),
	.A2(FE_DBTN2_u_del_vec_4),
	.ZN(mult_64_n95));
   NOR2_X1 mult_64_U150 (.A1(mult_64_n191),
	.A2(FE_DBTN3_u_del_vec_3),
	.ZN(mult_64_n96));
   NOR2_X1 mult_64_U149 (.A1(mult_64_n191),
	.A2(FE_DBTN5_u_del_vec_1),
	.ZN(mult_64_n97));
   NOR2_X1 mult_64_U148 (.A1(mult_64_n191),
	.A2(FE_DBTN6_u_del_vec_0),
	.ZN(mult_64_n98));
   NAND2_X1 mult_64_U147 (.A1(a1[9]),
	.A2(u_del_vec[7]),
	.ZN(mult_64_n99));
   XNOR2_X1 mult_64_U146 (.A(mult_64_n2),
	.B(mult_64_n17),
	.ZN(mult_64_n201));
   XOR2_X1 mult_64_U145 (.A(mult_64_n201),
	.B(mult_64_n15),
	.Z(mult_64_n197));
   NAND2_X1 mult_64_U144 (.A1(u_del_vec[7]),
	.A2(a1[10]),
	.ZN(mult_64_n199));
   AND2_X1 mult_64_U143 (.A1(a1[11]),
	.A2(u_del_vec[6]),
	.ZN(mult_64_n200));
   XOR2_X1 mult_64_U142 (.A(mult_64_n199),
	.B(mult_64_n200),
	.Z(mult_64_n198));
   XOR2_X1 mult_64_U141 (.A(mult_64_n197),
	.B(mult_64_n198),
	.Z(mula1[12]));
   INV_X1 mult_64_U140 (.A(a1[5]),
	.ZN(mult_64_n196));
   INV_X1 mult_64_U136 (.A(a1[9]),
	.ZN(mult_64_n192));
   INV_X1 mult_64_U135 (.A(a1[10]),
	.ZN(mult_64_n191));
   INV_X1 mult_64_U130 (.A(a1[8]),
	.ZN(mult_64_n193));
   INV_X1 mult_64_U129 (.A(a1[7]),
	.ZN(mult_64_n194));
   INV_X1 mult_64_U128 (.A(a1[6]),
	.ZN(mult_64_n195));
   INV_X1 mult_64_U127 (.A(mult_64_n54),
	.ZN(mult_64_n186));
   INV_X1 mult_64_U126 (.A(mult_64_n80),
	.ZN(mult_64_n184));
   INV_X1 mult_64_U125 (.A(mult_64_n66),
	.ZN(mult_64_n180));
   INV_X1 mult_64_U124 (.A(mult_64_n73),
	.ZN(mult_64_n183));
   INV_X1 mult_64_U123 (.A(mult_64_n82),
	.ZN(mult_64_n188));
   HA_X1 mult_64_U51 (.A(mult_64_n129),
	.B(mult_64_n136),
	.CO(mult_64_n83),
	.S(mult_64_n84));
   HA_X1 mult_64_U50 (.A(mult_64_n114),
	.B(mult_64_n121),
	.CO(mult_64_n81),
	.S(mult_64_n82));
   FA_X1 mult_64_U49 (.A(mult_64_n128),
	.B(mult_64_n135),
	.CI(mult_64_n83),
	.CO(mult_64_n79),
	.S(mult_64_n80));
   HA_X1 mult_64_U48 (.A(mult_64_n106),
	.B(mult_64_n113),
	.CO(mult_64_n77),
	.S(mult_64_n78));
   FA_X1 mult_64_U47 (.A(mult_64_n120),
	.B(mult_64_n134),
	.CI(mult_64_n127),
	.CO(mult_64_n75),
	.S(mult_64_n76));
   FA_X1 mult_64_U46 (.A(mult_64_n78),
	.B(mult_64_n81),
	.CI(mult_64_n79),
	.CO(mult_64_n73),
	.S(mult_64_n74));
   HA_X1 mult_64_U45 (.A(mult_64_n98),
	.B(mult_64_n105),
	.CO(mult_64_n71),
	.S(mult_64_n72));
   FA_X1 mult_64_U44 (.A(mult_64_n112),
	.B(mult_64_n133),
	.CI(mult_64_n119),
	.CO(mult_64_n69),
	.S(mult_64_n70));
   FA_X1 mult_64_U43 (.A(mult_64_n77),
	.B(mult_64_n126),
	.CI(mult_64_n72),
	.CO(mult_64_n67),
	.S(mult_64_n68));
   FA_X1 mult_64_U42 (.A(mult_64_n70),
	.B(mult_64_n75),
	.CI(mult_64_n68),
	.CO(mult_64_n65),
	.S(mult_64_n66));
   FA_X1 mult_64_U39 (.A(mult_64_n97),
	.B(mult_64_n125),
	.CI(mult_64_n111),
	.CO(mult_64_n61),
	.S(mult_64_n62));
   FA_X1 mult_64_U38 (.A(mult_64_n91),
	.B(mult_64_n118),
	.CI(mult_64_n71),
	.CO(mult_64_n59),
	.S(mult_64_n60));
   FA_X1 mult_64_U37 (.A(mult_64_n69),
	.B(mult_64_n64),
	.CI(mult_64_n62),
	.CO(mult_64_n57),
	.S(mult_64_n58));
   FA_X1 mult_64_U36 (.A(mult_64_n60),
	.B(mult_64_n67),
	.CI(mult_64_n58),
	.CO(mult_64_n55),
	.S(mult_64_n56));
   FA_X1 mult_64_U34 (.A(mult_64_n103),
	.B(mult_64_n110),
	.CI(mult_64_n124),
	.CO(mult_64_n51),
	.S(mult_64_n52));
   FA_X1 mult_64_U33 (.A(mult_64_n131),
	.B(mult_64_n117),
	.CI(mult_64_n90),
	.CO(mult_64_n49),
	.S(mult_64_n50));
   FA_X1 mult_64_U32 (.A(mult_64_n63),
	.B(mult_64_n54),
	.CI(mult_64_n61),
	.CO(mult_64_n47),
	.S(mult_64_n48));
   FA_X1 mult_64_U31 (.A(mult_64_n52),
	.B(mult_64_n59),
	.CI(mult_64_n50),
	.CO(mult_64_n45),
	.S(mult_64_n46));
   FA_X1 mult_64_U30 (.A(mult_64_n48),
	.B(mult_64_n57),
	.CI(mult_64_n46),
	.CO(mult_64_n43),
	.S(mult_64_n44));
   FA_X1 mult_64_U29 (.A(mult_64_n102),
	.B(mult_64_n186),
	.CI(mult_64_n96),
	.CO(mult_64_n41),
	.S(mult_64_n42));
   FA_X1 mult_64_U28 (.A(mult_64_n116),
	.B(mult_64_n109),
	.CI(mult_64_n123),
	.CO(mult_64_n39),
	.S(mult_64_n40));
   FA_X1 mult_64_U27 (.A(mult_64_n51),
	.B(mult_64_n89),
	.CI(mult_64_n49),
	.CO(mult_64_n37),
	.S(mult_64_n38));
   FA_X1 mult_64_U26 (.A(mult_64_n40),
	.B(mult_64_n42),
	.CI(mult_64_n47),
	.CO(mult_64_n35),
	.S(mult_64_n36));
   FA_X1 mult_64_U25 (.A(mult_64_n38),
	.B(mult_64_n45),
	.CI(mult_64_n36),
	.CO(mult_64_n33),
	.S(mult_64_n34));
   FA_X1 mult_64_U24 (.A(mult_64_n95),
	.B(mult_64_n101),
	.CI(mult_64_n108),
	.CO(mult_64_n31),
	.S(mult_64_n32));
   FA_X1 mult_64_U23 (.A(mult_64_n88),
	.B(mult_64_n115),
	.CI(mult_64_n41),
	.CO(mult_64_n29),
	.S(mult_64_n30));
   FA_X1 mult_64_U22 (.A(mult_64_n32),
	.B(mult_64_n39),
	.CI(mult_64_n37),
	.CO(mult_64_n27),
	.S(mult_64_n28));
   FA_X1 mult_64_U21 (.A(mult_64_n35),
	.B(mult_64_n30),
	.CI(mult_64_n28),
	.CO(mult_64_n25),
	.S(mult_64_n26));
   FA_X1 mult_64_U20 (.A(mult_64_n94),
	.B(mult_64_n100),
	.CI(mult_64_n107),
	.CO(mult_64_n23),
	.S(mult_64_n24));
   FA_X1 mult_64_U19 (.A(mult_64_n31),
	.B(mult_64_n87),
	.CI(mult_64_n24),
	.CO(mult_64_n21),
	.S(mult_64_n22));
   FA_X1 mult_64_U18 (.A(mult_64_n27),
	.B(mult_64_n29),
	.CI(mult_64_n22),
	.CO(mult_64_n19),
	.S(mult_64_n20));
   FA_X1 mult_64_U17 (.A(mult_64_n99),
	.B(mult_64_n93),
	.CI(mult_64_n86),
	.CO(mult_64_n17),
	.S(mult_64_n18));
   FA_X1 mult_64_U16 (.A(mult_64_n18),
	.B(mult_64_n23),
	.CI(mult_64_n21),
	.CO(mult_64_n15),
	.S(mult_64_n16));
   FA_X1 mult_64_U8 (.A(mult_64_n56),
	.B(mult_64_n65),
	.CI(mult_64_n8),
	.CO(mult_64_n7),
	.S(mula1[6]));
   FA_X1 mult_64_U7 (.A(mult_64_n44),
	.B(mult_64_n55),
	.CI(mult_64_n7),
	.CO(mult_64_n6),
	.S(mula1[7]));
   FA_X1 mult_64_U6 (.A(mult_64_n34),
	.B(mult_64_n43),
	.CI(mult_64_n6),
	.CO(mult_64_n5),
	.S(mula1[8]));
   FA_X1 mult_64_U5 (.A(mult_64_n26),
	.B(mult_64_n33),
	.CI(mult_64_n5),
	.CO(mult_64_n4),
	.S(mula1[9]));
   FA_X1 mult_64_U4 (.A(mult_64_n20),
	.B(mult_64_n25),
	.CI(mult_64_n4),
	.CO(mult_64_n3),
	.S(mula1[10]));
   FA_X1 mult_64_U3 (.A(mult_64_n19),
	.B(mult_64_n16),
	.CI(mult_64_n3),
	.CO(mult_64_n2),
	.S(mula1[11]));
   NOR2_X1 mult_68_U203 (.A1(FE_DBTN0_u_del_vec_6),
	.A2(mult_68_n192),
	.ZN(mult_68_n100));
   NOR2_X1 mult_68_U202 (.A1(mult_68_n192),
	.A2(FE_DBTN1_u_del_vec_5),
	.ZN(mult_68_n101));
   NOR2_X1 mult_68_U201 (.A1(mult_68_n192),
	.A2(FE_DBTN2_u_del_vec_4),
	.ZN(mult_68_n102));
   NOR2_X1 mult_68_U200 (.A1(mult_68_n192),
	.A2(FE_DBTN3_u_del_vec_3),
	.ZN(mult_68_n103));
   NOR2_X1 mult_68_U199 (.A1(mult_68_n192),
	.A2(FE_DBTN5_u_del_vec_1),
	.ZN(mult_68_n105));
   NOR2_X1 mult_68_U198 (.A1(mult_68_n192),
	.A2(FE_DBTN6_u_del_vec_0),
	.ZN(mult_68_n106));
   NAND2_X1 mult_68_U197 (.A1(b1[8]),
	.A2(u_del_vec[7]),
	.ZN(mult_68_n107));
   NOR2_X1 mult_68_U196 (.A1(FE_DBTN0_u_del_vec_6),
	.A2(mult_68_n193),
	.ZN(mult_68_n108));
   NOR2_X1 mult_68_U195 (.A1(FE_DBTN1_u_del_vec_5),
	.A2(mult_68_n193),
	.ZN(mult_68_n109));
   NOR2_X1 mult_68_U194 (.A1(FE_DBTN2_u_del_vec_4),
	.A2(mult_68_n193),
	.ZN(mult_68_n110));
   NOR2_X1 mult_68_U193 (.A1(FE_DBTN3_u_del_vec_3),
	.A2(mult_68_n193),
	.ZN(mult_68_n111));
   NOR2_X1 mult_68_U192 (.A1(FE_DBTN4_u_del_vec_2),
	.A2(mult_68_n193),
	.ZN(mult_68_n112));
   NOR2_X1 mult_68_U191 (.A1(FE_DBTN5_u_del_vec_1),
	.A2(mult_68_n193),
	.ZN(mult_68_n113));
   NOR2_X1 mult_68_U190 (.A1(FE_DBTN6_u_del_vec_0),
	.A2(mult_68_n193),
	.ZN(mult_68_n114));
   NAND2_X1 mult_68_U189 (.A1(b1[7]),
	.A2(u_del_vec[7]),
	.ZN(mult_68_n115));
   NOR2_X1 mult_68_U188 (.A1(FE_DBTN0_u_del_vec_6),
	.A2(mult_68_n194),
	.ZN(mult_68_n116));
   NOR2_X1 mult_68_U187 (.A1(FE_DBTN1_u_del_vec_5),
	.A2(mult_68_n194),
	.ZN(mult_68_n117));
   NOR2_X1 mult_68_U186 (.A1(FE_DBTN2_u_del_vec_4),
	.A2(mult_68_n194),
	.ZN(mult_68_n118));
   NOR2_X1 mult_68_U185 (.A1(FE_DBTN3_u_del_vec_3),
	.A2(mult_68_n194),
	.ZN(mult_68_n119));
   NOR2_X1 mult_68_U184 (.A1(FE_DBTN4_u_del_vec_2),
	.A2(mult_68_n194),
	.ZN(mult_68_n120));
   NOR2_X1 mult_68_U183 (.A1(FE_DBTN5_u_del_vec_1),
	.A2(mult_68_n194),
	.ZN(mult_68_n121));
   NAND2_X1 mult_68_U182 (.A1(b1[6]),
	.A2(u_del_vec[7]),
	.ZN(mult_68_n123));
   NOR2_X1 mult_68_U181 (.A1(FE_DBTN0_u_del_vec_6),
	.A2(mult_68_n195),
	.ZN(mult_68_n124));
   NOR2_X1 mult_68_U180 (.A1(FE_DBTN1_u_del_vec_5),
	.A2(mult_68_n195),
	.ZN(mult_68_n125));
   NOR2_X1 mult_68_U179 (.A1(FE_DBTN2_u_del_vec_4),
	.A2(mult_68_n195),
	.ZN(mult_68_n126));
   NOR2_X1 mult_68_U178 (.A1(FE_DBTN3_u_del_vec_3),
	.A2(mult_68_n195),
	.ZN(mult_68_n127));
   NOR2_X1 mult_68_U177 (.A1(FE_DBTN4_u_del_vec_2),
	.A2(mult_68_n195),
	.ZN(mult_68_n128));
   NOR2_X1 mult_68_U176 (.A1(FE_DBTN5_u_del_vec_1),
	.A2(mult_68_n195),
	.ZN(mult_68_n129));
   NAND2_X1 mult_68_U175 (.A1(b1[5]),
	.A2(u_del_vec[7]),
	.ZN(mult_68_n131));
   NOR2_X1 mult_68_U174 (.A1(FE_DBTN1_u_del_vec_5),
	.A2(mult_68_n196),
	.ZN(mult_68_n133));
   NOR2_X1 mult_68_U173 (.A1(FE_DBTN2_u_del_vec_4),
	.A2(mult_68_n196),
	.ZN(mult_68_n134));
   NOR2_X1 mult_68_U172 (.A1(FE_DBTN3_u_del_vec_3),
	.A2(mult_68_n196),
	.ZN(mult_68_n135));
   NOR2_X1 mult_68_U171 (.A1(FE_DBTN4_u_del_vec_2),
	.A2(mult_68_n196),
	.ZN(mult_68_n136));
   NAND2_X1 mult_68_U170 (.A1(u_del_vec[2]),
	.A2(b1[10]),
	.ZN(mult_68_n54));
   NAND2_X1 mult_68_U169 (.A1(b1[5]),
	.A2(u_del_vec[6]),
	.ZN(mult_68_n208));
   NAND2_X1 mult_68_U168 (.A1(u_del_vec[2]),
	.A2(b1[9]),
	.ZN(mult_68_n207));
   NAND2_X1 mult_68_U167 (.A1(mult_68_n208),
	.A2(mult_68_n207),
	.ZN(mult_68_n63));
   XNOR2_X1 mult_68_U166 (.A(mult_68_n207),
	.B(mult_68_n208),
	.ZN(mult_68_n64));
   NOR4_X1 mult_68_U165 (.A1(mult_68_n195),
	.A2(mult_68_n196),
	.A3(FE_DBTN5_u_del_vec_1),
	.A4(FE_DBTN6_u_del_vec_0),
	.ZN(mult_68_n205));
   NOR2_X1 mult_68_U164 (.A1(mult_68_n194),
	.A2(FE_DBTN6_u_del_vec_0),
	.ZN(mult_68_n206));
   AOI222_X1 mult_68_U163 (.A1(mult_68_n84),
	.A2(mult_68_n205),
	.B1(mult_68_n206),
	.B2(mult_68_n84),
	.C1(mult_68_n206),
	.C2(mult_68_n205),
	.ZN(mult_68_n204));
   OAI222_X1 mult_68_U162 (.A1(mult_68_n204),
	.A2(mult_68_n184),
	.B1(mult_68_n184),
	.B2(mult_68_n188),
	.C1(mult_68_n204),
	.C2(mult_68_n188),
	.ZN(mult_68_n203));
   AOI222_X1 mult_68_U161 (.A1(mult_68_n203),
	.A2(mult_68_n74),
	.B1(mult_68_n203),
	.B2(mult_68_n76),
	.C1(mult_68_n76),
	.C2(mult_68_n74),
	.ZN(mult_68_n202));
   OAI222_X1 mult_68_U160 (.A1(mult_68_n202),
	.A2(mult_68_n180),
	.B1(mult_68_n202),
	.B2(mult_68_n183),
	.C1(mult_68_n183),
	.C2(mult_68_n180),
	.ZN(mult_68_n8));
   NAND2_X1 mult_68_U159 (.A1(u_del_vec[5]),
	.A2(b1[11]),
	.ZN(mult_68_n86));
   NAND2_X1 mult_68_U158 (.A1(u_del_vec[4]),
	.A2(b1[11]),
	.ZN(mult_68_n87));
   NAND2_X1 mult_68_U157 (.A1(u_del_vec[3]),
	.A2(b1[11]),
	.ZN(mult_68_n88));
   NAND2_X1 mult_68_U156 (.A1(u_del_vec[2]),
	.A2(b1[11]),
	.ZN(mult_68_n89));
   NAND2_X1 mult_68_U155 (.A1(u_del_vec[1]),
	.A2(b1[11]),
	.ZN(mult_68_n90));
   NAND2_X1 mult_68_U154 (.A1(u_del_vec[0]),
	.A2(b1[11]),
	.ZN(mult_68_n91));
   NOR2_X1 mult_68_U153 (.A1(mult_68_n191),
	.A2(FE_DBTN0_u_del_vec_6),
	.ZN(mult_68_n93));
   NOR2_X1 mult_68_U152 (.A1(mult_68_n191),
	.A2(FE_DBTN1_u_del_vec_5),
	.ZN(mult_68_n94));
   NOR2_X1 mult_68_U151 (.A1(mult_68_n191),
	.A2(FE_DBTN2_u_del_vec_4),
	.ZN(mult_68_n95));
   NOR2_X1 mult_68_U150 (.A1(mult_68_n191),
	.A2(FE_DBTN3_u_del_vec_3),
	.ZN(mult_68_n96));
   NOR2_X1 mult_68_U149 (.A1(mult_68_n191),
	.A2(FE_DBTN5_u_del_vec_1),
	.ZN(mult_68_n97));
   NOR2_X1 mult_68_U148 (.A1(mult_68_n191),
	.A2(FE_DBTN6_u_del_vec_0),
	.ZN(mult_68_n98));
   NAND2_X1 mult_68_U147 (.A1(b1[9]),
	.A2(u_del_vec[7]),
	.ZN(mult_68_n99));
   XNOR2_X1 mult_68_U146 (.A(mult_68_n2),
	.B(mult_68_n17),
	.ZN(mult_68_n201));
   XOR2_X1 mult_68_U145 (.A(mult_68_n201),
	.B(mult_68_n15),
	.Z(mult_68_n197));
   NAND2_X1 mult_68_U144 (.A1(u_del_vec[7]),
	.A2(b1[10]),
	.ZN(mult_68_n199));
   AND2_X1 mult_68_U143 (.A1(b1[11]),
	.A2(u_del_vec[6]),
	.ZN(mult_68_n200));
   XOR2_X1 mult_68_U142 (.A(mult_68_n199),
	.B(mult_68_n200),
	.Z(mult_68_n198));
   XOR2_X1 mult_68_U141 (.A(mult_68_n197),
	.B(mult_68_n198),
	.Z(mulb1[12]));
   INV_X1 mult_68_U136 (.A(b1[5]),
	.ZN(mult_68_n196));
   INV_X1 mult_68_U133 (.A(b1[9]),
	.ZN(mult_68_n192));
   INV_X1 mult_68_U132 (.A(b1[10]),
	.ZN(mult_68_n191));
   INV_X1 mult_68_U130 (.A(b1[8]),
	.ZN(mult_68_n193));
   INV_X1 mult_68_U129 (.A(b1[7]),
	.ZN(mult_68_n194));
   INV_X1 mult_68_U128 (.A(b1[6]),
	.ZN(mult_68_n195));
   INV_X1 mult_68_U127 (.A(mult_68_n54),
	.ZN(mult_68_n186));
   INV_X1 mult_68_U126 (.A(mult_68_n80),
	.ZN(mult_68_n184));
   INV_X1 mult_68_U125 (.A(mult_68_n66),
	.ZN(mult_68_n180));
   INV_X1 mult_68_U124 (.A(mult_68_n73),
	.ZN(mult_68_n183));
   INV_X1 mult_68_U123 (.A(mult_68_n82),
	.ZN(mult_68_n188));
   HA_X1 mult_68_U51 (.A(mult_68_n129),
	.B(mult_68_n136),
	.CO(mult_68_n83),
	.S(mult_68_n84));
   HA_X1 mult_68_U50 (.A(mult_68_n114),
	.B(mult_68_n121),
	.CO(mult_68_n81),
	.S(mult_68_n82));
   FA_X1 mult_68_U49 (.A(mult_68_n128),
	.B(mult_68_n135),
	.CI(mult_68_n83),
	.CO(mult_68_n79),
	.S(mult_68_n80));
   HA_X1 mult_68_U48 (.A(mult_68_n106),
	.B(mult_68_n113),
	.CO(mult_68_n77),
	.S(mult_68_n78));
   FA_X1 mult_68_U47 (.A(mult_68_n120),
	.B(mult_68_n134),
	.CI(mult_68_n127),
	.CO(mult_68_n75),
	.S(mult_68_n76));
   FA_X1 mult_68_U46 (.A(mult_68_n78),
	.B(mult_68_n81),
	.CI(mult_68_n79),
	.CO(mult_68_n73),
	.S(mult_68_n74));
   HA_X1 mult_68_U45 (.A(mult_68_n98),
	.B(mult_68_n105),
	.CO(mult_68_n71),
	.S(mult_68_n72));
   FA_X1 mult_68_U44 (.A(mult_68_n112),
	.B(mult_68_n133),
	.CI(mult_68_n119),
	.CO(mult_68_n69),
	.S(mult_68_n70));
   FA_X1 mult_68_U43 (.A(mult_68_n77),
	.B(mult_68_n126),
	.CI(mult_68_n72),
	.CO(mult_68_n67),
	.S(mult_68_n68));
   FA_X1 mult_68_U42 (.A(mult_68_n70),
	.B(mult_68_n75),
	.CI(mult_68_n68),
	.CO(mult_68_n65),
	.S(mult_68_n66));
   FA_X1 mult_68_U39 (.A(mult_68_n97),
	.B(mult_68_n125),
	.CI(mult_68_n111),
	.CO(mult_68_n61),
	.S(mult_68_n62));
   FA_X1 mult_68_U38 (.A(mult_68_n91),
	.B(mult_68_n118),
	.CI(mult_68_n71),
	.CO(mult_68_n59),
	.S(mult_68_n60));
   FA_X1 mult_68_U37 (.A(mult_68_n69),
	.B(mult_68_n64),
	.CI(mult_68_n62),
	.CO(mult_68_n57),
	.S(mult_68_n58));
   FA_X1 mult_68_U36 (.A(mult_68_n60),
	.B(mult_68_n67),
	.CI(mult_68_n58),
	.CO(mult_68_n55),
	.S(mult_68_n56));
   FA_X1 mult_68_U34 (.A(mult_68_n103),
	.B(mult_68_n110),
	.CI(mult_68_n124),
	.CO(mult_68_n51),
	.S(mult_68_n52));
   FA_X1 mult_68_U33 (.A(mult_68_n131),
	.B(mult_68_n117),
	.CI(mult_68_n90),
	.CO(mult_68_n49),
	.S(mult_68_n50));
   FA_X1 mult_68_U32 (.A(mult_68_n63),
	.B(mult_68_n54),
	.CI(mult_68_n61),
	.CO(mult_68_n47),
	.S(mult_68_n48));
   FA_X1 mult_68_U31 (.A(mult_68_n52),
	.B(mult_68_n59),
	.CI(mult_68_n50),
	.CO(mult_68_n45),
	.S(mult_68_n46));
   FA_X1 mult_68_U30 (.A(mult_68_n48),
	.B(mult_68_n57),
	.CI(mult_68_n46),
	.CO(mult_68_n43),
	.S(mult_68_n44));
   FA_X1 mult_68_U29 (.A(mult_68_n102),
	.B(mult_68_n186),
	.CI(mult_68_n96),
	.CO(mult_68_n41),
	.S(mult_68_n42));
   FA_X1 mult_68_U28 (.A(mult_68_n116),
	.B(mult_68_n109),
	.CI(mult_68_n123),
	.CO(mult_68_n39),
	.S(mult_68_n40));
   FA_X1 mult_68_U27 (.A(mult_68_n51),
	.B(mult_68_n89),
	.CI(mult_68_n49),
	.CO(mult_68_n37),
	.S(mult_68_n38));
   FA_X1 mult_68_U26 (.A(mult_68_n40),
	.B(mult_68_n42),
	.CI(mult_68_n47),
	.CO(mult_68_n35),
	.S(mult_68_n36));
   FA_X1 mult_68_U25 (.A(mult_68_n38),
	.B(mult_68_n45),
	.CI(mult_68_n36),
	.CO(mult_68_n33),
	.S(mult_68_n34));
   FA_X1 mult_68_U24 (.A(mult_68_n95),
	.B(mult_68_n101),
	.CI(mult_68_n108),
	.CO(mult_68_n31),
	.S(mult_68_n32));
   FA_X1 mult_68_U23 (.A(mult_68_n88),
	.B(mult_68_n115),
	.CI(mult_68_n41),
	.CO(mult_68_n29),
	.S(mult_68_n30));
   FA_X1 mult_68_U22 (.A(mult_68_n32),
	.B(mult_68_n39),
	.CI(mult_68_n37),
	.CO(mult_68_n27),
	.S(mult_68_n28));
   FA_X1 mult_68_U21 (.A(mult_68_n35),
	.B(mult_68_n30),
	.CI(mult_68_n28),
	.CO(mult_68_n25),
	.S(mult_68_n26));
   FA_X1 mult_68_U20 (.A(mult_68_n94),
	.B(mult_68_n100),
	.CI(mult_68_n107),
	.CO(mult_68_n23),
	.S(mult_68_n24));
   FA_X1 mult_68_U19 (.A(mult_68_n31),
	.B(mult_68_n87),
	.CI(mult_68_n24),
	.CO(mult_68_n21),
	.S(mult_68_n22));
   FA_X1 mult_68_U18 (.A(mult_68_n27),
	.B(mult_68_n29),
	.CI(mult_68_n22),
	.CO(mult_68_n19),
	.S(mult_68_n20));
   FA_X1 mult_68_U17 (.A(mult_68_n99),
	.B(mult_68_n93),
	.CI(mult_68_n86),
	.CO(mult_68_n17),
	.S(mult_68_n18));
   FA_X1 mult_68_U16 (.A(mult_68_n18),
	.B(mult_68_n23),
	.CI(mult_68_n21),
	.CO(mult_68_n15),
	.S(mult_68_n16));
   FA_X1 mult_68_U8 (.A(mult_68_n56),
	.B(mult_68_n65),
	.CI(mult_68_n8),
	.CO(mult_68_n7),
	.S(mulb1[6]));
   FA_X1 mult_68_U7 (.A(mult_68_n44),
	.B(mult_68_n55),
	.CI(mult_68_n7),
	.CO(mult_68_n6),
	.S(mulb1[7]));
   FA_X1 mult_68_U6 (.A(mult_68_n34),
	.B(mult_68_n43),
	.CI(mult_68_n6),
	.CO(mult_68_n5),
	.S(mulb1[8]));
   FA_X1 mult_68_U5 (.A(mult_68_n26),
	.B(mult_68_n33),
	.CI(mult_68_n5),
	.CO(mult_68_n4),
	.S(mulb1[9]));
   FA_X1 mult_68_U4 (.A(mult_68_n20),
	.B(mult_68_n25),
	.CI(mult_68_n4),
	.CO(mult_68_n3),
	.S(mulb1[10]));
   FA_X1 mult_68_U3 (.A(mult_68_n19),
	.B(mult_68_n16),
	.CI(mult_68_n3),
	.CO(mult_68_n2),
	.S(mulb1[11]));
   NOR2_X1 mult_66_U203 (.A1(mult_66_n179),
	.A2(mult_66_n192),
	.ZN(mult_66_n100));
   NOR2_X1 mult_66_U202 (.A1(mult_66_n192),
	.A2(mult_66_n181),
	.ZN(mult_66_n101));
   NOR2_X1 mult_66_U201 (.A1(mult_66_n192),
	.A2(mult_66_n182),
	.ZN(mult_66_n102));
   NOR2_X1 mult_66_U200 (.A1(mult_66_n192),
	.A2(mult_66_n185),
	.ZN(mult_66_n103));
   NOR2_X1 mult_66_U199 (.A1(mult_66_n192),
	.A2(mult_66_n189),
	.ZN(mult_66_n105));
   NOR2_X1 mult_66_U198 (.A1(mult_66_n192),
	.A2(mult_66_n190),
	.ZN(mult_66_n106));
   NAND2_X1 mult_66_U197 (.A1(b0[8]),
	.A2(u[7]),
	.ZN(mult_66_n107));
   NOR2_X1 mult_66_U196 (.A1(mult_66_n179),
	.A2(mult_66_n193),
	.ZN(mult_66_n108));
   NOR2_X1 mult_66_U195 (.A1(mult_66_n181),
	.A2(mult_66_n193),
	.ZN(mult_66_n109));
   NOR2_X1 mult_66_U194 (.A1(mult_66_n182),
	.A2(mult_66_n193),
	.ZN(mult_66_n110));
   NOR2_X1 mult_66_U193 (.A1(mult_66_n185),
	.A2(mult_66_n193),
	.ZN(mult_66_n111));
   NOR2_X1 mult_66_U192 (.A1(mult_66_n187),
	.A2(mult_66_n193),
	.ZN(mult_66_n112));
   NOR2_X1 mult_66_U191 (.A1(mult_66_n189),
	.A2(mult_66_n193),
	.ZN(mult_66_n113));
   NOR2_X1 mult_66_U190 (.A1(mult_66_n190),
	.A2(mult_66_n193),
	.ZN(mult_66_n114));
   NAND2_X1 mult_66_U189 (.A1(b0[7]),
	.A2(u[7]),
	.ZN(mult_66_n115));
   NOR2_X1 mult_66_U188 (.A1(mult_66_n179),
	.A2(mult_66_n194),
	.ZN(mult_66_n116));
   NOR2_X1 mult_66_U187 (.A1(mult_66_n181),
	.A2(mult_66_n194),
	.ZN(mult_66_n117));
   NOR2_X1 mult_66_U186 (.A1(mult_66_n182),
	.A2(mult_66_n194),
	.ZN(mult_66_n118));
   NOR2_X1 mult_66_U185 (.A1(mult_66_n185),
	.A2(mult_66_n194),
	.ZN(mult_66_n119));
   NOR2_X1 mult_66_U184 (.A1(mult_66_n187),
	.A2(mult_66_n194),
	.ZN(mult_66_n120));
   NOR2_X1 mult_66_U183 (.A1(mult_66_n189),
	.A2(mult_66_n194),
	.ZN(mult_66_n121));
   NAND2_X1 mult_66_U182 (.A1(b0[6]),
	.A2(u[7]),
	.ZN(mult_66_n123));
   NOR2_X1 mult_66_U181 (.A1(mult_66_n179),
	.A2(mult_66_n195),
	.ZN(mult_66_n124));
   NOR2_X1 mult_66_U180 (.A1(mult_66_n181),
	.A2(mult_66_n195),
	.ZN(mult_66_n125));
   NOR2_X1 mult_66_U179 (.A1(mult_66_n182),
	.A2(mult_66_n195),
	.ZN(mult_66_n126));
   NOR2_X1 mult_66_U178 (.A1(mult_66_n185),
	.A2(mult_66_n195),
	.ZN(mult_66_n127));
   NOR2_X1 mult_66_U177 (.A1(mult_66_n187),
	.A2(mult_66_n195),
	.ZN(mult_66_n128));
   NOR2_X1 mult_66_U176 (.A1(mult_66_n189),
	.A2(mult_66_n195),
	.ZN(mult_66_n129));
   NAND2_X1 mult_66_U175 (.A1(b0[5]),
	.A2(u[7]),
	.ZN(mult_66_n131));
   NOR2_X1 mult_66_U174 (.A1(mult_66_n181),
	.A2(mult_66_n196),
	.ZN(mult_66_n133));
   NOR2_X1 mult_66_U173 (.A1(mult_66_n182),
	.A2(mult_66_n196),
	.ZN(mult_66_n134));
   NOR2_X1 mult_66_U172 (.A1(mult_66_n185),
	.A2(mult_66_n196),
	.ZN(mult_66_n135));
   NOR2_X1 mult_66_U171 (.A1(mult_66_n187),
	.A2(mult_66_n196),
	.ZN(mult_66_n136));
   NAND2_X1 mult_66_U170 (.A1(u[2]),
	.A2(b0[10]),
	.ZN(mult_66_n54));
   NAND2_X1 mult_66_U169 (.A1(b0[5]),
	.A2(u[6]),
	.ZN(mult_66_n208));
   NAND2_X1 mult_66_U168 (.A1(u[2]),
	.A2(b0[9]),
	.ZN(mult_66_n207));
   NAND2_X1 mult_66_U167 (.A1(mult_66_n208),
	.A2(mult_66_n207),
	.ZN(mult_66_n63));
   XNOR2_X1 mult_66_U166 (.A(mult_66_n207),
	.B(mult_66_n208),
	.ZN(mult_66_n64));
   NOR4_X1 mult_66_U165 (.A1(mult_66_n195),
	.A2(mult_66_n196),
	.A3(mult_66_n189),
	.A4(mult_66_n190),
	.ZN(mult_66_n205));
   NOR2_X1 mult_66_U164 (.A1(mult_66_n194),
	.A2(mult_66_n190),
	.ZN(mult_66_n206));
   AOI222_X1 mult_66_U163 (.A1(mult_66_n84),
	.A2(mult_66_n205),
	.B1(mult_66_n206),
	.B2(mult_66_n84),
	.C1(mult_66_n206),
	.C2(mult_66_n205),
	.ZN(mult_66_n204));
   OAI222_X1 mult_66_U162 (.A1(mult_66_n204),
	.A2(mult_66_n184),
	.B1(mult_66_n184),
	.B2(mult_66_n188),
	.C1(mult_66_n204),
	.C2(mult_66_n188),
	.ZN(mult_66_n203));
   AOI222_X1 mult_66_U161 (.A1(mult_66_n203),
	.A2(mult_66_n74),
	.B1(mult_66_n203),
	.B2(mult_66_n76),
	.C1(mult_66_n76),
	.C2(mult_66_n74),
	.ZN(mult_66_n202));
   OAI222_X1 mult_66_U160 (.A1(mult_66_n202),
	.A2(mult_66_n180),
	.B1(mult_66_n202),
	.B2(mult_66_n183),
	.C1(mult_66_n183),
	.C2(mult_66_n180),
	.ZN(mult_66_n8));
   NAND2_X1 mult_66_U159 (.A1(u[5]),
	.A2(b0[11]),
	.ZN(mult_66_n86));
   NAND2_X1 mult_66_U158 (.A1(u[4]),
	.A2(b0[11]),
	.ZN(mult_66_n87));
   NAND2_X1 mult_66_U157 (.A1(u[3]),
	.A2(b0[11]),
	.ZN(mult_66_n88));
   NAND2_X1 mult_66_U156 (.A1(u[2]),
	.A2(b0[11]),
	.ZN(mult_66_n89));
   NAND2_X1 mult_66_U155 (.A1(u[1]),
	.A2(b0[11]),
	.ZN(mult_66_n90));
   NAND2_X1 mult_66_U154 (.A1(u[0]),
	.A2(b0[11]),
	.ZN(mult_66_n91));
   NOR2_X1 mult_66_U153 (.A1(mult_66_n191),
	.A2(mult_66_n179),
	.ZN(mult_66_n93));
   NOR2_X1 mult_66_U152 (.A1(mult_66_n191),
	.A2(mult_66_n181),
	.ZN(mult_66_n94));
   NOR2_X1 mult_66_U151 (.A1(mult_66_n191),
	.A2(mult_66_n182),
	.ZN(mult_66_n95));
   NOR2_X1 mult_66_U150 (.A1(mult_66_n191),
	.A2(mult_66_n185),
	.ZN(mult_66_n96));
   NOR2_X1 mult_66_U149 (.A1(mult_66_n191),
	.A2(mult_66_n189),
	.ZN(mult_66_n97));
   NOR2_X1 mult_66_U148 (.A1(mult_66_n191),
	.A2(mult_66_n190),
	.ZN(mult_66_n98));
   NAND2_X1 mult_66_U147 (.A1(b0[9]),
	.A2(u[7]),
	.ZN(mult_66_n99));
   XNOR2_X1 mult_66_U146 (.A(mult_66_n2),
	.B(mult_66_n17),
	.ZN(mult_66_n201));
   XOR2_X1 mult_66_U145 (.A(mult_66_n201),
	.B(mult_66_n15),
	.Z(mult_66_n197));
   NAND2_X1 mult_66_U144 (.A1(u[7]),
	.A2(b0[10]),
	.ZN(mult_66_n199));
   AND2_X1 mult_66_U143 (.A1(b0[11]),
	.A2(u[6]),
	.ZN(mult_66_n200));
   XOR2_X1 mult_66_U142 (.A(mult_66_n199),
	.B(mult_66_n200),
	.Z(mult_66_n198));
   XOR2_X1 mult_66_U141 (.A(mult_66_n197),
	.B(mult_66_n198),
	.Z(mulb0[12]));
   INV_X1 mult_66_U140 (.A(b0[5]),
	.ZN(mult_66_n196));
   INV_X1 mult_66_U139 (.A(b0[9]),
	.ZN(mult_66_n192));
   INV_X1 mult_66_U138 (.A(b0[10]),
	.ZN(mult_66_n191));
   INV_X1 mult_66_U137 (.A(b0[8]),
	.ZN(mult_66_n193));
   INV_X1 mult_66_U136 (.A(b0[7]),
	.ZN(mult_66_n194));
   INV_X1 mult_66_U135 (.A(b0[6]),
	.ZN(mult_66_n195));
   INV_X1 mult_66_U134 (.A(u[0]),
	.ZN(mult_66_n190));
   INV_X1 mult_66_U133 (.A(u[2]),
	.ZN(mult_66_n187));
   INV_X1 mult_66_U132 (.A(u[6]),
	.ZN(mult_66_n179));
   INV_X1 mult_66_U131 (.A(mult_66_n54),
	.ZN(mult_66_n186));
   INV_X1 mult_66_U130 (.A(u[1]),
	.ZN(mult_66_n189));
   INV_X1 mult_66_U129 (.A(u[3]),
	.ZN(mult_66_n185));
   INV_X1 mult_66_U128 (.A(u[4]),
	.ZN(mult_66_n182));
   INV_X1 mult_66_U127 (.A(u[5]),
	.ZN(mult_66_n181));
   INV_X1 mult_66_U126 (.A(mult_66_n73),
	.ZN(mult_66_n183));
   INV_X1 mult_66_U125 (.A(mult_66_n80),
	.ZN(mult_66_n184));
   INV_X1 mult_66_U124 (.A(mult_66_n82),
	.ZN(mult_66_n188));
   INV_X1 mult_66_U123 (.A(mult_66_n66),
	.ZN(mult_66_n180));
   HA_X1 mult_66_U51 (.A(mult_66_n129),
	.B(mult_66_n136),
	.CO(mult_66_n83),
	.S(mult_66_n84));
   HA_X1 mult_66_U50 (.A(mult_66_n114),
	.B(mult_66_n121),
	.CO(mult_66_n81),
	.S(mult_66_n82));
   FA_X1 mult_66_U49 (.A(mult_66_n128),
	.B(mult_66_n135),
	.CI(mult_66_n83),
	.CO(mult_66_n79),
	.S(mult_66_n80));
   HA_X1 mult_66_U48 (.A(mult_66_n106),
	.B(mult_66_n113),
	.CO(mult_66_n77),
	.S(mult_66_n78));
   FA_X1 mult_66_U47 (.A(mult_66_n120),
	.B(mult_66_n134),
	.CI(mult_66_n127),
	.CO(mult_66_n75),
	.S(mult_66_n76));
   FA_X1 mult_66_U46 (.A(mult_66_n78),
	.B(mult_66_n81),
	.CI(mult_66_n79),
	.CO(mult_66_n73),
	.S(mult_66_n74));
   HA_X1 mult_66_U45 (.A(mult_66_n98),
	.B(mult_66_n105),
	.CO(mult_66_n71),
	.S(mult_66_n72));
   FA_X1 mult_66_U44 (.A(mult_66_n112),
	.B(mult_66_n133),
	.CI(mult_66_n119),
	.CO(mult_66_n69),
	.S(mult_66_n70));
   FA_X1 mult_66_U43 (.A(mult_66_n77),
	.B(mult_66_n126),
	.CI(mult_66_n72),
	.CO(mult_66_n67),
	.S(mult_66_n68));
   FA_X1 mult_66_U42 (.A(mult_66_n70),
	.B(mult_66_n75),
	.CI(mult_66_n68),
	.CO(mult_66_n65),
	.S(mult_66_n66));
   FA_X1 mult_66_U39 (.A(mult_66_n97),
	.B(mult_66_n125),
	.CI(mult_66_n111),
	.CO(mult_66_n61),
	.S(mult_66_n62));
   FA_X1 mult_66_U38 (.A(mult_66_n91),
	.B(mult_66_n118),
	.CI(mult_66_n71),
	.CO(mult_66_n59),
	.S(mult_66_n60));
   FA_X1 mult_66_U37 (.A(mult_66_n69),
	.B(mult_66_n64),
	.CI(mult_66_n62),
	.CO(mult_66_n57),
	.S(mult_66_n58));
   FA_X1 mult_66_U36 (.A(mult_66_n60),
	.B(mult_66_n67),
	.CI(mult_66_n58),
	.CO(mult_66_n55),
	.S(mult_66_n56));
   FA_X1 mult_66_U34 (.A(mult_66_n103),
	.B(mult_66_n110),
	.CI(mult_66_n124),
	.CO(mult_66_n51),
	.S(mult_66_n52));
   FA_X1 mult_66_U33 (.A(mult_66_n131),
	.B(mult_66_n117),
	.CI(mult_66_n90),
	.CO(mult_66_n49),
	.S(mult_66_n50));
   FA_X1 mult_66_U32 (.A(mult_66_n63),
	.B(mult_66_n54),
	.CI(mult_66_n61),
	.CO(mult_66_n47),
	.S(mult_66_n48));
   FA_X1 mult_66_U31 (.A(mult_66_n52),
	.B(mult_66_n59),
	.CI(mult_66_n50),
	.CO(mult_66_n45),
	.S(mult_66_n46));
   FA_X1 mult_66_U30 (.A(mult_66_n48),
	.B(mult_66_n57),
	.CI(mult_66_n46),
	.CO(mult_66_n43),
	.S(mult_66_n44));
   FA_X1 mult_66_U29 (.A(mult_66_n102),
	.B(mult_66_n186),
	.CI(mult_66_n96),
	.CO(mult_66_n41),
	.S(mult_66_n42));
   FA_X1 mult_66_U28 (.A(mult_66_n116),
	.B(mult_66_n109),
	.CI(mult_66_n123),
	.CO(mult_66_n39),
	.S(mult_66_n40));
   FA_X1 mult_66_U27 (.A(mult_66_n51),
	.B(mult_66_n89),
	.CI(mult_66_n49),
	.CO(mult_66_n37),
	.S(mult_66_n38));
   FA_X1 mult_66_U26 (.A(mult_66_n40),
	.B(mult_66_n42),
	.CI(mult_66_n47),
	.CO(mult_66_n35),
	.S(mult_66_n36));
   FA_X1 mult_66_U25 (.A(mult_66_n38),
	.B(mult_66_n45),
	.CI(mult_66_n36),
	.CO(mult_66_n33),
	.S(mult_66_n34));
   FA_X1 mult_66_U24 (.A(mult_66_n95),
	.B(mult_66_n101),
	.CI(mult_66_n108),
	.CO(mult_66_n31),
	.S(mult_66_n32));
   FA_X1 mult_66_U23 (.A(mult_66_n88),
	.B(mult_66_n115),
	.CI(mult_66_n41),
	.CO(mult_66_n29),
	.S(mult_66_n30));
   FA_X1 mult_66_U22 (.A(mult_66_n32),
	.B(mult_66_n39),
	.CI(mult_66_n37),
	.CO(mult_66_n27),
	.S(mult_66_n28));
   FA_X1 mult_66_U21 (.A(mult_66_n35),
	.B(mult_66_n30),
	.CI(mult_66_n28),
	.CO(mult_66_n25),
	.S(mult_66_n26));
   FA_X1 mult_66_U20 (.A(mult_66_n94),
	.B(mult_66_n100),
	.CI(mult_66_n107),
	.CO(mult_66_n23),
	.S(mult_66_n24));
   FA_X1 mult_66_U19 (.A(mult_66_n31),
	.B(mult_66_n87),
	.CI(mult_66_n24),
	.CO(mult_66_n21),
	.S(mult_66_n22));
   FA_X1 mult_66_U18 (.A(mult_66_n27),
	.B(mult_66_n29),
	.CI(mult_66_n22),
	.CO(mult_66_n19),
	.S(mult_66_n20));
   FA_X1 mult_66_U17 (.A(mult_66_n99),
	.B(mult_66_n93),
	.CI(mult_66_n86),
	.CO(mult_66_n17),
	.S(mult_66_n18));
   FA_X1 mult_66_U16 (.A(mult_66_n18),
	.B(mult_66_n23),
	.CI(mult_66_n21),
	.CO(mult_66_n15),
	.S(mult_66_n16));
   FA_X1 mult_66_U8 (.A(mult_66_n56),
	.B(mult_66_n65),
	.CI(mult_66_n8),
	.CO(mult_66_n7),
	.S(mulb0[6]));
   FA_X1 mult_66_U7 (.A(mult_66_n44),
	.B(mult_66_n55),
	.CI(mult_66_n7),
	.CO(mult_66_n6),
	.S(mulb0[7]));
   FA_X1 mult_66_U6 (.A(mult_66_n34),
	.B(mult_66_n43),
	.CI(mult_66_n6),
	.CO(mult_66_n5),
	.S(mulb0[8]));
   FA_X1 mult_66_U5 (.A(mult_66_n26),
	.B(mult_66_n33),
	.CI(mult_66_n5),
	.CO(mult_66_n4),
	.S(mulb0[9]));
   FA_X1 mult_66_U4 (.A(mult_66_n20),
	.B(mult_66_n25),
	.CI(mult_66_n4),
	.CO(mult_66_n3),
	.S(mulb0[10]));
   FA_X1 mult_66_U3 (.A(mult_66_n19),
	.B(mult_66_n16),
	.CI(mult_66_n3),
	.CO(mult_66_n2),
	.S(mulb0[11]));
endmodule

